// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 4UL

#define resource_Texture0_OFFSET 80UL
#define resource_Texture1_OFFSET 100UL
#define resource_Texture2_OFFSET 120UL
#define resource_Texture3_OFFSET 140UL
