// Automatically generated by the bundler tool from Resource.rdf

#define Resource_NUM_RESOURCES 7UL

#define Resource_EnvMap_OFFSET 144UL
#define Resource_LobbyXP_OFFSET 164UL
#define Resource_LobbyXN_OFFSET 184UL
#define Resource_LobbyYP_OFFSET 204UL
#define Resource_LobbyYN_OFFSET 224UL
#define Resource_LobbyZP_OFFSET 244UL
#define Resource_LobbyZN_OFFSET 264UL
