// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 4UL

#define resource_Flame1_OFFSET 80UL
#define resource_ForestGround_OFFSET 100UL
#define resource_GryDirt1_OFFSET 120UL
#define resource_WaterBumps_OFFSET 140UL
