// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 6UL

#define resource_M0CM0_OFFSET 128UL
#define resource_M0BM0_OFFSET 148UL
#define resource_M1CM0_OFFSET 168UL
#define resource_M1BM0_OFFSET 188UL
#define resource_M2CM0_OFFSET 208UL
#define resource_M2BM0_OFFSET 228UL
