//
// XactSounds.h - generated by xactbld from the XACT project (.xap).
// Do not edit.
//

#ifndef __XACTSOUNDS_H__
#define __XACTSOUNDS_H__

// Sound categories
typedef enum XACT_CATEGORY
{
    XACT_CATEGORY_BGMUSIC = 0,
    XACT_CATEGORY_COUNT = 1,
} XACT_CATEGORY;

// Sound bank "sample" cue indices
typedef enum XACT_SOUNDBANK_SAMPLE
{
    XACT_SOUNDBANK_SAMPLE_CUE1 = 0,
    XACT_SOUNDBANK_SAMPLE_CUE_COUNT = 1,
} XACT_SOUNDBANK_SAMPLE;

// Wave bank "sample" entry indices
typedef enum XACT_WAVEBANK_SAMPLE
{
    XACT_WAVEBANK_SAMPLE_SMALL = 0,
    XACT_WAVEBANK_SAMPLE_ENTRY_COUNT = 1,
} XACT_WAVEBANK_SAMPLE;

#endif
