//-----------------------------------------------------------------------------
// File: CallStackLog.cpp
//
// Desc: Xbox application demonstrating the use of DmCaptureStackBackTrace
//       to collect a call stack at runtime.  A log file is created
//       containing a list of loaded modules and the addresses of functions
//       in a call stack.
//
//       This sample is meant to be used in conjunction with the
//       CallStackLookup sample, which is run on the development machine.
//       Copy the log file generated by CallStackLog off the Xbox
//       and use CallStackLookup to turn addresses in the log into
//       function names.
//
//       Call stacks will not work reliably for standard Release or Profile builds.
//       The reason is that the frame pointer omission optimization creates stacks
//       that the DmCaptureStackBackTrace is not able to analyze.  If you need to
//       use DmCaptureStackBackTrace, turn that optimization off by adding this
//       compiler flag:
//          /Oy-
//       It can be added in the Visual Studio project properties under C/C++,
//       Command Line, Addition Options.
//
// Hist: 11.15.02 - Created for December 2002 XDK release.
// Hist: 06.27.03 - Add note about limitations with release builds.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------
#include <xbapp.h>
#include <xbfont.h>
#include <xbhelp.h>
#include <xgraphics.h>
#include <xbdm.h>
#include "LogFile.h"




//-----------------------------------------------------------------------------
// Callouts for labelling the gamepad on the help screen
//-----------------------------------------------------------------------------
XBHELP_CALLOUT g_HelpCallouts[] = 
{
    { XBHELP_BACK_BUTTON,  XBHELP_PLACEMENT_1, L"Display help" },
    { XBHELP_A_BUTTON,     XBHELP_PLACEMENT_2, L"Add stack in\nFunctionA" },
    { XBHELP_B_BUTTON,     XBHELP_PLACEMENT_2, L"Add stack in\nFunctionB" },
};

#define NUM_HELP_CALLOUTS ( sizeof( g_HelpCallouts ) / sizeof( g_HelpCallouts[0] ) )

// The log goes to the title's scratch drive. On a devkit D: is the writable sample share,
// but booting from a disc makes it a read-only DVD and the log cannot be created at all.
const CHAR *g_LogFilename = "t:\\Log.txt";




//-----------------------------------------------------------------------------
// Name: class CXBoxSample
// Desc: Main class to run this application. Most functionality is inherited
//       from the CXBApplication base class.
//-----------------------------------------------------------------------------
class CXBoxSample : public CXBApplication
{
    CXBFont         m_Font;             // Font object
    CXBHelp         m_Help;             // Help object
    BOOL            m_bDrawHelp;        // TRUE to draw help screen

    HANDLE          m_hLogFile;         // Log file where call stacks are written
    const WCHAR *   m_strLastLogged;    // Used to update UI to confirm functions logged

public:
    HRESULT WriteToLog( const CHAR *str, DWORD dwBytesToWrite );
    HRESULT LogModuleInfo(); // Write address ranges of program modules
    HRESULT LogCallStack();  // Write current call stack addresses to log

    // Dummy functions just used for the purpose of generating two different
    // call stacks.  Make sure they don't get inlined, for demonstration purposes
    // so that they show up as distinct functions in call stacks.
    __declspec(noinline) void FunctionA();
    __declspec(noinline) void FunctionB();

    virtual HRESULT Initialize();
    virtual HRESULT Render();
    virtual HRESULT FrameMove();

    CXBoxSample();
};




//-----------------------------------------------------------------------------
// Name: main()
// Desc: Entry point to the program.
//-----------------------------------------------------------------------------
VOID __cdecl main()
{
    CXBoxSample xbApp;
    if( FAILED( xbApp.Create() ) )
        return;
    xbApp.Run();
}




//-----------------------------------------------------------------------------
// Name: CXBoxSample::WriteToFile()
// Desc: Writes the given string to the log file.
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::WriteToLog( const CHAR *str, DWORD dwBytesToWrite )
{
    DWORD dwBytesWritten;
    if( 0 == WriteFile( m_hLogFile,
                        str,
                        dwBytesToWrite,
                        &dwBytesWritten,
                        NULL ) )
        return E_FAIL;
    if( dwBytesToWrite != dwBytesWritten )
        return E_FAIL;

    // Flush the file buffers.  Because we assume the log file will stay open
    // until the application is reset or the Xbox is turned off, we want to force
    // a flush after each write.  If we didn't do this, there could be data cached
    // in memory that hasn't been written to disk, leaving the log file incomplete.
    if( 0 == FlushFileBuffers( m_hLogFile ) )
        return E_FAIL;

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: CXBoxSample::LogModuleInfo()
// Desc: Must be called once at startup to write address ranges of program
//       modules.  This information is needed later in order to look up
//       function addresses.
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::LogModuleInfo()
{
    // Iterate over the list of loaded modules.
    PDM_WALK_MODULES pWalkMod = NULL; // Must be initialized to NULL to begin the walk
    DMN_MODLOAD module;
    while( XBDM_NOERR == DmWalkLoadedModules( &pWalkMod, &module ) )
    {
        // Create a string containing the loaded module info.
        // NOTE: For demonstration purposes, this sample uses a text-based
        //       format so that you can easily see what's going on by
        //       looking at the log in notepad.  If you are going to be
        //       collecting lots of call stack data, you may prefer
        //       to save the data directly into a binary format for
        //       performance reasons.
        CHAR strFormattedOutput[g_iModuleOutputMaxChars];
        DWORD dwOutputChars = sprintf(strFormattedOutput,
                                      "%s%s%s0x%08lx%s0x%08lx%s0x%08lx%s",
                                      g_strModuleOutputStart,
                                      module.Name,
                                      g_strModuleOutputSeparator,
                                      (ULONG)(ULONG_PTR)module.BaseAddress,
                                      g_strModuleOutputSeparator,
                                      module.Size,
                                      g_strModuleOutputSeparator,
                                      module.TimeStamp,
                                      g_strModuleOutputEnd);

        // Write formatted string to the log file.
        if( FAILED( WriteToLog( strFormattedOutput, dwOutputChars ) ) )
            return E_FAIL;
    }
    DmCloseLoadedModules(pWalkMod);
    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: CXBoxSample::LogCallStack()
// Desc: Writes the addresses of the current call stack into the log file
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::LogCallStack()
{
    // The stack will be returned as an array of addresses, each representing
    // the address of one function on the stack.
    VOID *CapturedAddresses[g_ulNumFramesToCapture];

    // Get the actual stack data
    if( FAILED( DmCaptureStackBackTrace( g_ulNumFramesToCapture, CapturedAddresses ) ) )
        return E_FAIL;

    // Create a string containing the loaded module info.
    // NOTE: For demonstration purposes, this sample uses a text-based
    //       format so that you can easily see what's going on by
    //       looking at the log in notepad.  If you are going to be
    //       collecting lots of call stack data, you may prefer
    //       to save the data directly into a binary format for
    //       performance reasons.
    CHAR strFormattedOutput[g_iStackOutputMaxChars];

    // Copy beginng of stack string.
    strcpy( strFormattedOutput, g_strStackOutputStart );

    // This will track the current position in the output buffer as text is written.
    CHAR *pOutputWrite = strFormattedOutput + g_iCharCountStackOutputStart;

    // Iterate over each stack level that was returned.
    // Note that we're starting at one instead of zero.  Because the first
    //    function is always going to be this one (CXBoxSample::LogCallStack),
    //    there's no need to include it.
    for( int i = 1; i < g_ulNumFramesToCapture; ++i )
    {
        DWORD dwCurrentAddress = (DWORD)CapturedAddresses[i];

        // DmCaptureStackBackTrace will have set this value to zero
        // when we've reached the end of the stack.  (There often aren't
        // as many levels as we requested.)
        if( dwCurrentAddress == 0 )
            break; // bail out of the loop

        sprintf(pOutputWrite, "0x%08lx%s", dwCurrentAddress, g_strStackOutputSeparator);
        pOutputWrite += 10 + g_iCharCountStackOutputSeparator;
    }

    // Throw out the separator following the last item and copy the end
    // of the stack string.
    pOutputWrite -= g_iCharCountStackOutputSeparator;
    strcpy( pOutputWrite, g_strStackOutputEnd );

    // Write formatted string to the log file.
    DWORD dwBytesToWrite = pOutputWrite - strFormattedOutput + g_iCharCountStackOutputEnd;
    if( FAILED( WriteToLog( strFormattedOutput, dwBytesToWrite ) ) )
        return E_FAIL;

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: CXBoxSample::FunctionA()
// Desc: Dummy function used to generating a call stack with "FunctionA"
//-----------------------------------------------------------------------------
__declspec(noinline) void CXBoxSample::FunctionA()
{
    if ( SUCCEEDED( LogCallStack() ) )
        m_strLastLogged = L"CXBoxSample::FunctionA";
}




//-----------------------------------------------------------------------------
// Name: CXBoxSample::FunctionB()
// Desc: Dummy function used to generating a call stack with "FunctionB"
//-----------------------------------------------------------------------------
__declspec(noinline) void CXBoxSample::FunctionB()
{
    if ( SUCCEEDED( LogCallStack() ) )
        m_strLastLogged = L"CXBoxSample::FunctionB";
}




//-----------------------------------------------------------------------------
// Name: CXBoxSample()
// Desc: Constructor for CXBoxSample class
//-----------------------------------------------------------------------------
CXBoxSample::CXBoxSample() 
            :CXBApplication()
{
    m_bDrawHelp = FALSE;
    m_hLogFile = NULL;
    m_strLastLogged = NULL;
}




//-----------------------------------------------------------------------------
// Name: Initialize()
// Desc: Performs initialization
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::Initialize()
{
    // Create a font
    if( FAILED( m_Font.Create( "Font.xpr" ) ) )
        return XBAPPERR_MEDIANOTFOUND;

    // Create help
    if( FAILED( m_Help.Create( "Gamepad.xpr" ) ) )
        return XBAPPERR_MEDIANOTFOUND;

    // Open log file
    m_hLogFile = CreateFile( g_LogFilename,
                             GENERIC_WRITE,
                             0,
                             NULL,
                             CREATE_ALWAYS,
                             FILE_ATTRIBUTE_NORMAL,
                             NULL );
    if( m_hLogFile == INVALID_HANDLE_VALUE )
        return E_FAIL;

    // Initialize the log with module info
    if ( FAILED( LogModuleInfo() ) )
        return E_FAIL;

    // Log the current call stack.  This isn't required but we'll do it
    // for the purpose of the sample just to make sure at least one call
    // stack always shows up in the log even if you don't hit any buttons.
    if ( SUCCEEDED( LogCallStack() ) )
        m_strLastLogged = L"CXBoxSample::Initialize";

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: FrameMove()
// Desc: Performs per-frame updates
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::FrameMove()
{
    // Toggle help
    if( m_DefaultGamepad.wPressedButtons & XINPUT_GAMEPAD_BACK ) 
    {
        m_bDrawHelp = !m_bDrawHelp;
    }

    // Call functions that log call stacks
    if( m_DefaultGamepad.bPressedAnalogButtons[XINPUT_GAMEPAD_A] )
        FunctionA();
    if( m_DefaultGamepad.bPressedAnalogButtons[XINPUT_GAMEPAD_B] )
        FunctionB();

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: Render()
// Desc: Renders the scene
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::Render()
{
    // Draw a gradient filled background and clear the zbuffer
    RenderGradientBackground( 0xff404040, 0xff404080 );

    // Show title, frame rate, and help
    if( m_bDrawHelp )
        m_Help.Render( &m_Font, g_HelpCallouts, NUM_HELP_CALLOUTS );
    else
    {
        m_Font.Begin();

        m_Font.DrawText(  64, 50, 0xffffffff, L"CallStackLog" );
        m_Font.DrawText( 450, 50, 0xffffff00, m_strFrameRate );

        if ( m_strLastLogged )
        {
            m_Font.DrawText(100, 150, 0xff00ffff, m_strLastLogged);
            m_Font.DrawText(150, 175, 0xff008080, L"call stack written to log.txt file");
        }

        m_Font.End();
    }

    // Present the scene
    m_pd3dDevice->Present( NULL, NULL, NULL, NULL );

    return S_OK;
}
