// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 3UL

#define resource_Crystal_OFFSET 64UL
#define resource_XRay1_OFFSET 84UL
#define resource_XRay2_OFFSET 104UL
