// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 14UL

#define resource_Crypt_skybox_back_OFFSET 368UL
#define resource_Crypt_skybox_front_OFFSET 388UL
#define resource_Crypt_skybox_left_OFFSET 408UL
#define resource_Crypt_skybox_right_OFFSET 428UL
#define resource_Crypt_skybox_up_OFFSET 448UL
#define resource_DesertMap_OFFSET 468UL
#define resource_DoorShuttersInside_OFFSET 488UL
#define resource_DoorShuttersOutside_OFFSET 508UL
#define resource_Exterior_Crypt_OFFSET 528UL
#define resource_FirePit_OFFSET 548UL
#define resource_Floor_OFFSET 568UL
#define resource_Interior_OFFSET 588UL
#define resource_Trogmap3_OFFSET 608UL
#define resource_Hud_OFFSET 628UL
