// Automatically generated by the bundler tool from OnlineIconsFont.rdf

#define OnlineIconsFont_NUM_RESOURCES 2UL

#define OnlineIconsFont_Font_OFFSET 0UL
#define OnlineIconsFont_FontData_OFFSET 20UL
