// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 3UL

#define resource_Scene_OFFSET 64UL
#define resource_SphMap1_OFFSET 84UL
#define resource_SphMap2_OFFSET 104UL
