//-----------------------------------------------------------------------------
// File: QualityOfService.cpp
//
// Desc: Illustrates Quality of Service calls on Xbox.
//       Allows the user to do QoS probes to other System Link consoles,
//       Online consoles, and Online Security Gateways.
//
// Hist: 05.24.01 - New for June release 
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------
#include "QualityOfService.h"
#include "MatchSimDefs.h"
#include "xbmemunit.h"
#include "xbVoice.h"
#include <cassert>
#pragma warning( disable: 4355 )




//-----------------------------------------------------------------------------
// Constants
//-----------------------------------------------------------------------------
const WORD  BROADCAST_PORT    = 1001;   // Takes advantage of XNet packet optimization

const DWORD DEFAULT_SAMPLES          = 8;         // Default samples/probe
const DWORD DEFAULT_LISTEN_BANDWIDTH = 16 * 1000; // Default QoS listen bandwidth
const DWORD DEFAULT_LOOKUP_BANDWIDTH = 16 * 1000; // Default QoS lookup bandwidth

const DWORD LISTEN_BANDWIDTH_CHUNK   = 4 * 1000;  // Slider increment
const DWORD LOOKUP_BANDWIDTH_CHUNK   = 4 * 1000;  // Slider increment

const DWORD MIN_LISTEN_BANDWIDTH     = 4 * 1000;  // Minimum listen bandwidth
const DWORD MIN_LOOKUP_BANDWIDTH     = 4 * 1000;  // Minimum lookup bandwidth
const DWORD MAX_SESSIONS             = 6;         // For this sample (to avoid scroll)

// TCR Session Discovery Time for System Link Play
const FLOAT SESSION_SEARCH_TIME = 1.0f;   // 1 seconds (may not exceed 3)



// The following search ID has been custom-designed specifically for this sample
// using the MatchSim tool.
const DWORD SEARCH_ID_CUSTOM_1 = 1;




//-----------------------------------------------------------------------------
// Message IDs
//-----------------------------------------------------------------------------
enum
{
    MSG_FIND_SESSION,
    MSG_SESSION_FOUND,
};




//-----------------------------------------------------------------------------
// Message payloads
//-----------------------------------------------------------------------------
// Pack to minimize network traffic
#pragma pack( push )
#pragma pack( 1 )

//-----------------------------------------------------------------------------
// Broadcast by a SysLink client looking for available sessions
//-----------------------------------------------------------------------------
struct MsgFindSession
{
    Nonce nonce;    // Generated by client; used to verify host response
};

//-----------------------------------------------------------------------------
// Broadcast by a SysLink host in response to a MSG_FIND_SESSION
//-----------------------------------------------------------------------------
struct MsgSessionFound
{
    Nonce  nonce;   // used for client verification
    XNADDR xnAddr;  // host XNet address
    XNKID  xnKid;   // host key ID
    XNKEY  xnKey;   // host key
};

#pragma pack( pop )




//-----------------------------------------------------------------------------
// Name: class Message
// Desc: Message object
//-----------------------------------------------------------------------------
class Message
{
    BYTE m_byMessageId;

    union
    {
        MsgFindSession     m_FindSession;
        MsgSessionFound    m_SessionFound;
    };

public:

    explicit Message( BYTE byMessageId = 0 ) : m_byMessageId( byMessageId ) {}
    ~Message() {}

    BYTE GetId() const      { return m_byMessageId; }
    INT  GetMaxSize() const { return sizeof(*this); }

    MsgFindSession&     GetFindSession()     { return m_FindSession;     }
    MsgSessionFound&    GetSessionFound()    { return m_SessionFound;    }

    INT GetSize() const
    { 
        switch( m_byMessageId )
        {
            case MSG_FIND_SESSION:     return sizeof(BYTE) + sizeof(MsgFindSession);
            case MSG_SESSION_FOUND:    return sizeof(BYTE) + sizeof(MsgSessionFound);
            default: assert( FALSE ); return 0;
        }
    }

private:

    // Disabled
    Message( const Message& );
    Message& operator=( const Message& );

};




//-----------------------------------------------------------------------------
// Name: main()
// Desc: Entry point to the program.
//-----------------------------------------------------------------------------
VOID __cdecl main()
{
    CXBoxSample xbApp;
    if( FAILED( xbApp.Create() ) )
        return;
    xbApp.Run();
}




//-----------------------------------------------------------------------------
// Name: SessionList
// Desc: Constructor
//-----------------------------------------------------------------------------
SessionList::SessionList()
{
    // Reserve space for the list of sessions
    m_SessionList.reserve( MAX_SESSIONS );
    m_xnAddrList.reserve( MAX_SESSIONS );
    m_xnKidList.reserve( MAX_SESSIONS );
    m_xnKeyList.reserve( MAX_SESSIONS );
}




//-----------------------------------------------------------------------------
// Name: empty()
// Desc: true if list is empty (emulates STL empty)
//-----------------------------------------------------------------------------
bool SessionList::empty() const
{
    return m_SessionList.empty();
}




//-----------------------------------------------------------------------------
// Name: size()
// Desc: Get the number of sessions in the list (emulates STL size)
//-----------------------------------------------------------------------------
DWORD SessionList::size() const
{
    return m_SessionList.size();
}




//-----------------------------------------------------------------------------
// Name: push_back()
// Desc: Add a session to the list (emulates STL push_back)
//-----------------------------------------------------------------------------
void SessionList::push_back( const XNADDR& xnAddr, const XNKID& xnKid, 
                             const XNKEY& xnKey )
{
    SessionData info;
    CopyMemory( &info.xnAddr, &xnAddr, sizeof( xnAddr ) );
    CopyMemory( &info.xnKid,  &xnKid,  sizeof( xnKid ) );
    CopyMemory( &info.xnKey,  &xnKey,  sizeof( xnKey ) );
    m_SessionList.push_back( info );

    SessionData* pInfo = &m_SessionList.back();

    // Save the addresses
    m_xnAddrList.push_back( &pInfo->xnAddr );
    m_xnKidList.push_back( &pInfo->xnKid );
    m_xnKeyList.push_back( &pInfo->xnKey );
}




//-----------------------------------------------------------------------------
// Name: clear()
// Desc: Remove all sessions from the list (emulates STL clear)
//-----------------------------------------------------------------------------
void SessionList::clear()
{
    // Remove items without freeing the memory
    m_SessionList.erase( m_SessionList.begin(), m_SessionList.end() );
    m_xnAddrList.erase( m_xnAddrList.begin(), m_xnAddrList.end() );
    m_xnKidList.erase( m_xnKidList.begin(), m_xnKidList.end() );
    m_xnKeyList.erase( m_xnKeyList.begin(), m_xnKeyList.end() );
}




//-----------------------------------------------------------------------------
// Name: GetXnAddrs()
// Desc: Get list of XNADDRs
//-----------------------------------------------------------------------------

const XNADDR** SessionList::GetXnAddrs()
{
    assert( !empty() );
    return &m_xnAddrList[0];
}




//-----------------------------------------------------------------------------
// Name: GetXnKids()
// Desc: Get list of XNKIDs
//-----------------------------------------------------------------------------
const XNKID** SessionList::GetXnKids()
{
    assert( !empty() );
    return &m_xnKidList[0];
}




//-----------------------------------------------------------------------------
// Name: GetXnKeys()
// Desc: Get list of XNKEYs
//-----------------------------------------------------------------------------
const XNKEY** SessionList::GetXnKeys()
{
    assert( !empty() );
    return &m_xnKeyList[0];
}




//-----------------------------------------------------------------------------
// Name: GetXnAddr()
// Desc: Get the XNADDR at the given location in the list
//-----------------------------------------------------------------------------
XNADDR SessionList::GetXnAddr( DWORD i ) const
{
    assert( i < MAX_SESSIONS );
    assert( i < size() );
    return *m_xnAddrList[ i ];
}




//-----------------------------------------------------------------------------
// Name: CXBoxSample()
// Desc: Constructor
//-----------------------------------------------------------------------------
CXBoxSample::CXBoxSample()
{
    m_State     = STATE_SELECT_MODE;
    m_NextState = STATE_SELECT_MODE;
    
    // Login to matchmaking service
    m_pServices[0] = XONLINE_MATCHMAKING_SERVICE;
    
    m_dwCurrItem  = 0;
    m_dwCurrUser  = 0;
    m_dwUserIndex = 0;
    
    m_bIsSessionRegistered = FALSE;
    m_bListen              = FALSE;
    m_bIsSignedIn          = FALSE;
    
    m_dwListenBandwidth = DEFAULT_LISTEN_BANDWIDTH;
    m_dwLookupBandwidth = DEFAULT_LOOKUP_BANDWIDTH;
    m_dwSamples         = DEFAULT_SAMPLES;
    
    *m_strSessionName = 0;
    
    ZeroMemory( &m_xnTitleAddress, sizeof( m_xnTitleAddress ) );
    ZeroMemory( &m_xnSessionID, sizeof( m_xnSessionID ) );
    ZeroMemory( &m_xnKeyExchangeKey, sizeof( m_xnKeyExchangeKey ) );

    // These structs are allocated by XNetQos[Service]Lookup and freed by
    // XNetQosRelease
    m_pxnQos = NULL;
    m_pxnServiceQos = NULL;
}




//-----------------------------------------------------------------------------
// Name: Initialize()
// Desc: Initialize device-dependant objects
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::Initialize()
{
    // Initialize game UI
    if( FAILED( m_UI.Initialize() ) )
        return E_FAIL;
    
    // Initialize the network stack
    if( FAILED( XBNet_OnlineInit( XNET_STARTUP_BYPASS_SECURITY ) ) ) // &&&
        return E_FAIL;
    
    // Generate a session name that we can use with the probe data
    XBRandName_GetRandomName( m_strSessionName, MAX_SESSION_NAME );
    m_UI.SetSessionName( m_strSessionName );

    // Asynchronous local address acquisition. This would normally occur
    // during the game startup sequence. Only required for System Link.
    for( ;; )
    {
        DWORD dwStatus = XNetGetTitleXnAddr( &m_xnTitleAddress );
        assert( dwStatus != XNET_GET_XNADDR_NONE );

        // If we've retrieved the local address, we're done
        BOOL bHaveLocalAddr = ( dwStatus != XNET_GET_XNADDR_PENDING );
        if( bHaveLocalAddr )
            break;
    }

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: FrameMove()
// Desc: Called once per frame, the call is the entry point for animating
//       the scene.
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::FrameMove()
{
    // Check the physical connection
    if( !m_NetLink.IsActive() )
    {
        m_UI.SetErrorStr( L"This Xbox has lost its network connection" );
        Reset();
    }

    // Maintain our connection once we've logged on
    if( m_bIsSignedIn )
    {
        HRESULT hr = m_hOnlineTask.Continue();    
        if( FAILED( hr ) )
        {
            m_UI.SetErrorStr( hr == XONLINE_E_LOGON_KICKED_BY_DUPLICATE_LOGON ?
                              L"You have been signed out because your\n"
                              L"account signed in on another Xbox." :
                              L"This Xbox has lost its network connection" );
            Reset();
        }
    }
    
    Event ev = GetEvent();
    
    switch( m_State )
    {
    // System Link
    case STATE_SYSLINK_SEARCH:       UpdateStateSysLinkSearch( ev );      break;

    // Online
    case STATE_CREATE_ACCOUNT:       UpdateStateCreateAccount( ev );      break;
    case STATE_SELECT_ACCOUNT:       UpdateStateSelectAccount( ev );      break;
    case STATE_SIGNING_IN:           UpdateStateSigningIn( ev );          break;
    case STATE_ONLINE_CREATE:        UpdateStateOnlineCreate( ev );       break;
    case STATE_ONLINE_SEARCH:        UpdateStateOnlineSearch( ev );       break;

    // Generic
    case STATE_SELECT_MODE:          UpdateStateSelectMode( ev );         break;
    case STATE_SELECT_LISTEN_PARAMS: UpdateStateSelectListenParams( ev ); break;
    case STATE_SESSION_LIST:         UpdateStateSessionList( ev );        break;
    case STATE_SHOW_PROBE_DATA:      UpdateStateShowProbeData( ev );      break;
    case STATE_ERROR:                UpdateStateError( ev );              break;
    case STATE_HELP:                 UpdateStateHelp( ev );               break;

    default:                         assert( FALSE );                     break;
    }
    
    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: Render()
// Desc: Called once per frame, the call is the entry point for 3D
//       rendering. This function sets up render states, clears the
//       viewport, and renders the scene.
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::Render()
{
    // Clear the viewport
    m_pd3dDevice->Clear( 0L, NULL, D3DCLEAR_TARGET|D3DCLEAR_ZBUFFER|D3DCLEAR_STENCIL, 
        0x000A0A6A, 1.0f, 0L );
    
    switch( m_State )
    {
    case STATE_SYSLINK_SEARCH: m_UI.RenderSysLinkSearch();       break;
    case STATE_CREATE_ACCOUNT: m_UI.RenderCreateAccount( TRUE ); break;
    case STATE_SIGNING_IN:     m_UI.RenderSigningIn();           break;
    case STATE_ONLINE_CREATE:  m_UI.RenderOnlineCreate();        break;
    case STATE_ONLINE_SEARCH:  m_UI.RenderOnlineSearch();        break;
    case STATE_SELECT_MODE:    m_UI.RenderMode( m_dwCurrItem );  break;
    case STATE_ERROR:          m_UI.RenderError();               break;
    case STATE_HELP:           m_UI.RenderHelp();                break;

    case STATE_SELECT_LISTEN_PARAMS:
        m_UI.RenderListenParams( m_dwCurrItem, m_bListen, m_dwSamples, 
                                 m_dwListenBandwidth, m_dwLookupBandwidth, 
                                 m_bIsSignedIn );
        break;
    case STATE_SESSION_LIST:
        m_UI.RenderSessionList( m_dwCurrItem, m_xnTitleAddress, m_Sessions, 
                                m_pxnQos, m_pxnServiceQos,
                                m_dwSamples, m_bIsSignedIn ); 
        break;
    case STATE_SHOW_PROBE_DATA:
        m_UI.RenderProbeData( m_dwCurrItem, m_strSessionName, m_xnTitleAddress,
                              m_Sessions, m_pxnQos, m_pxnServiceQos, m_bIsSignedIn );
        break;
    case STATE_SELECT_ACCOUNT:
        m_UI.RenderSelectAccount( m_dwCurrItem, m_UserList );
        break;
    default:
        assert( FALSE );
        break;
    }
    
    // Present the scene
    m_pd3dDevice->Present( NULL, NULL, NULL, NULL );
    
    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: GetOnlineUsers()
// Desc: Initialize online user list
//-----------------------------------------------------------------------------
VOID CXBoxSample::GetOnlineUsers()
{
    // Get information on all accounts for this Xbox
    m_UserList.clear();
    if( FAILED( XBOnline_GetUserList( m_UserList ) ) || m_UserList.empty() )
    {
        m_State = STATE_CREATE_ACCOUNT;
    }
    CXBMemUnit::GetMemUnitSnapshot();     

}



    
//-----------------------------------------------------------------------------
// Name: GetEvent()
// Desc: Return the state of the controller
//-----------------------------------------------------------------------------
CXBoxSample::Event CXBoxSample::GetEvent() const
{
    // "A" or "Start"
    if( m_DefaultGamepad.bPressedAnalogButtons[ XINPUT_GAMEPAD_A ] ||
        m_DefaultGamepad.wPressedButtons & XINPUT_GAMEPAD_START )
    {
        return EV_BUTTON_A;
    }
    
    // "B"
    if( m_DefaultGamepad.bPressedAnalogButtons[ XINPUT_GAMEPAD_B ] )
        return EV_BUTTON_B;
    
    // "Back"
    if( m_DefaultGamepad.wPressedButtons & XINPUT_GAMEPAD_BACK )
        return EV_BUTTON_BACK;

     // "White"
    if( m_DefaultGamepad.bPressedAnalogButtons[ XINPUT_GAMEPAD_WHITE ] )
        return EV_BUTTON_WHITE;
   
    // Movement
    if( m_DefaultGamepad.wPressedButtons & XINPUT_GAMEPAD_DPAD_UP )
        return EV_UP;
    if( m_DefaultGamepad.wPressedButtons & XINPUT_GAMEPAD_DPAD_DOWN )
        return EV_DOWN;
    if( m_DefaultGamepad.wPressedButtons & XINPUT_GAMEPAD_DPAD_LEFT )
        return EV_LEFT;
    if( m_DefaultGamepad.wPressedButtons & XINPUT_GAMEPAD_DPAD_RIGHT )
        return EV_RIGHT;
    
    return EV_NULL;
}



//-----------------------------------------------------------------------------
// Name: UpdateStateSelectMode()
// Desc: Choose between System Link and Online
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateSelectMode( Event ev )
{
    switch( ev )
    {
        default: break;
    case EV_BUTTON_A:
        switch( m_dwCurrItem )
        {
        case MENU_SYSLINK:
            EndOnlineListen();
            BeginSysLinkListen();
            m_State = STATE_SELECT_LISTEN_PARAMS;
            m_dwCurrItem = 0;
            break;

        case MENU_ONLINE:
            EndSysLinkListen();
            m_State = STATE_SELECT_ACCOUNT;
            m_dwCurrItem = 0;
            GetOnlineUsers();
            break;

        default:
            assert( false );
            break;
        }
        break;
        
    case EV_UP:
        // Move to previous item; allow wrap to bottom
        if( m_dwCurrItem == 0 )
            m_dwCurrItem = MENU_MODE_MAX - 1;
        else
            --m_dwCurrItem;
        break;
        
    case EV_DOWN:
        // Move to next item; allow wrap to top
        if( m_dwCurrItem == MENU_MODE_MAX - 1 )
            m_dwCurrItem = 0;
        else
            ++m_dwCurrItem;
        break;

    case EV_BUTTON_WHITE:
        m_NextState = m_State;
        m_State = STATE_HELP;
        break;
    }
}




//-----------------------------------------------------------------------------
// Name: UpdateStateSysLinkSearch()
// Desc: Search for SysLink sessions
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateSysLinkSearch( Event ev )
{
    // See if any consoles have replied
    if( ProcessBroadcastMessage() )
        return;

    // We search for up to SESSION_SEARCH_TIME seconds. If the session 
    // search is complete, display the list of sessions. If no sessions
    // were found, display an error message
    if( m_SysLinkSearchTimer.GetElapsedSeconds() > SESSION_SEARCH_TIME )
    {
        m_SysLinkSearchTimer.Stop();
        if( m_Sessions.empty() )
        {
            m_UI.SetErrorStr( L"No System Link sessions available" );
            Reset();
        }
        else // at least one session
        {
            BeginQosLookup();
            m_State = STATE_SESSION_LIST;
        }
    }
}




//-----------------------------------------------------------------------------
// Name: UpdateStateCreateAccount()
// Desc: Inform player that account must be generated using external tool
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateCreateAccount( Event ev )
{
    switch( ev )
    {
    case EV_BUTTON_A:
        // Return to Dashboard. Retail Dashboard will include online account 
        // creation. Development XDK includes the XDK Launcher or Xbox 
        // OnlineDash for creating accounts.
        LD_LAUNCH_DASHBOARD ld;
        ZeroMemory( &ld, sizeof(ld) );
        ld.dwReason = XLD_LAUNCH_DASHBOARD_NEW_ACCOUNT_SIGNUP;
        XLaunchNewImage( NULL, PLAUNCH_DATA( &ld ) );
        break;

    case EV_BUTTON_WHITE:
        m_NextState = m_State;
        m_State = STATE_HELP;
        break;

    default:
        // If any MUs are inserted, update the user list
        // and go to account selection if there are any accounts
        DWORD dwInsertions;
        DWORD dwRemovals;
        if( CXBMemUnit::GetMemUnitChanges( dwInsertions, dwRemovals ) )
        {
            m_UserList.clear();
            XBOnline_GetUserList( m_UserList );
            if( !m_UserList.empty() )
            {
                m_dwCurrItem = 0;
                m_State = STATE_SELECT_ACCOUNT;
            }
       }
        break;
        
    }
}




//-----------------------------------------------------------------------------
// Name: UpdateStateSelectAccount()
// Desc: Allow player to select user account
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateSelectAccount( Event ev )
{
    // If player is already logged on, proceed to online session creation
    if( m_bIsSignedIn )
    {
        m_State = STATE_ONLINE_CREATE;
        return;
    }

    switch( ev )
    {
    case EV_BUTTON_A:
        // Save current account information
        m_dwCurrUser = m_dwCurrItem;

        // Sign in
        m_State = STATE_SIGNING_IN;
        BeginSignIn();
        break;
        
    case EV_BUTTON_B:
    case EV_BUTTON_BACK:
        m_dwCurrItem = 0;
        m_State = STATE_SELECT_MODE;
        break;
        
    case EV_UP:
        // Move to previous user account; allow wrap to bottom
        if( m_dwCurrItem == 0 )
            m_dwCurrItem = m_UserList.size() - 1;
        else
            --m_dwCurrItem;
        break;
        
    case EV_DOWN:
        // Move to next user account; allow wrap to top
        if( m_dwCurrItem == m_UserList.size() - 1 )
            m_dwCurrItem = 0;
        else
            ++m_dwCurrItem;
        break;
        
    case EV_BUTTON_WHITE:
        m_NextState = m_State;
        m_State = STATE_HELP;
        break;

    default:
        // If any MUs are inserted/removed, need to update the
        // user account list
        DWORD dwInsertions;
        DWORD dwRemovals;
        if( CXBMemUnit::GetMemUnitChanges( dwInsertions, dwRemovals ) )
        {
            m_UserList.clear();
            XBOnline_GetUserList( m_UserList );
            if( m_UserList.empty() )
                m_State = STATE_CREATE_ACCOUNT;
            else
                m_dwCurrItem = 0;
        }
        break;
    }
}




//-----------------------------------------------------------------------------
// Name: UpdateStateSigningIn()
// Desc: Spin during authentication
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateSigningIn( Event ev )
{
    switch( ev )
    {
        default: break;
    case EV_BUTTON_B:
    case EV_BUTTON_BACK:
        
        // Cancel the task
        m_hOnlineTask.Close();
        m_State = STATE_SELECT_ACCOUNT;
        return;
    }

    // Pump the sign in task    
    HRESULT hr = m_hOnlineTask.Continue();
    
    if( FAILED( hr ) )
    {
        m_UI.SetErrorStr( L"Sign In failed with error %x from TaskContinue", hr );
        m_hOnlineTask.Close();
        m_State = STATE_ERROR;
        m_NextState = STATE_SELECT_ACCOUNT;
        return;
    }
    
    // Check sign in status to see if it has completed
    if( hr == XONLINE_S_LOGON_CONNECTION_ESTABLISHED )
    {
        BOOL bSuccess = TRUE;
        HRESULT hrService = S_OK;
        
        // Next, check if the user was actually logged on
        PXONLINE_USER pLoggedOnUsers = XOnlineGetLogonUsers();
        assert( pLoggedOnUsers );
        hr = pLoggedOnUsers[ m_dwUserIndex ].hr;
        
        if( FAILED( hr ) )
        {
            m_UI.SetErrorStr( L"User Sign In failed with error %x", hr );
            bSuccess = FALSE;
        }
        else
        {
            // Check for service errors
            for( DWORD i = 0; i < NUM_SERVICES; ++i )
            {
                hrService = XOnlineGetServiceInfo( m_pServices[i], NULL );
                if( FAILED( hrService ) )
                {
                    m_UI.SetErrorStr( L"Service %d Sign In failed with error %x",
                                      m_pServices[i], hrService );
                    bSuccess = FALSE;
                    break;
                }
            }
        }
        
        if( bSuccess )
        {
            // We're now authenticated with Xbox Live
            m_bIsSignedIn = TRUE;
            
            // Start up an online session
            m_dwCurrItem = 0;

            m_State = STATE_ONLINE_CREATE;
            BeginOnlineSession();
        }
        else
        {
            // We failed to authenticate
            m_hOnlineTask.Close();
            m_State = STATE_ERROR;
            m_NextState = STATE_SELECT_ACCOUNT;
        }
    }
}




//-----------------------------------------------------------------------------
// Name: UpdateStateOnlineCreate()
// Desc: Creating session
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateOnlineCreate( Event ev )
{
    // If session already exists, proceed to QoS parameters
    if( m_bIsSessionRegistered )
    {
        m_dwCurrItem = 0;
        m_State = STATE_SELECT_LISTEN_PARAMS;
        return;
    }

    // Wait for matchmaking server to save new session info
    HRESULT hr = m_hMatchCreateTask.Continue();
    if( hr == XONLINETASK_S_RUNNING )
        return;

    // Handle errors
    if( FAILED(hr) )
    {
        m_UI.SetErrorStr( L"Session creation failed with error %x", hr );
        Reset();
        return;
    }

    // Extract the new session ID
    hr = XOnlineMatchSessionGetInfo( m_hMatchCreateTask, &m_xnSessionID, 
                                     &m_xnKeyExchangeKey );
    
    // Handle errors
    if( FAILED(hr) )
    {
        m_UI.SetErrorStr( L"XOnlineMatchSessionGetInfo failed with error %x",
                          hr );
        Reset();
        return;
    }

    // Session was created by matchmaking server. Now register the
    // session with this console.
    assert( !m_bIsSessionRegistered );
    INT iKeyRegistered = XNetRegisterKey( &m_xnSessionID, &m_xnKeyExchangeKey );
    if( iKeyRegistered != NO_ERROR )
    {
        m_UI.SetErrorStr( L"XNetRegisterKey failed");
        Reset();
        return;
    }

    // Now that the session is registered, we can begin listening for probes
    // from other consoles.     
    m_hMatchCreateTask.Close();
    m_bIsSessionRegistered = TRUE;
    BeginOnlineListen();

    // Allow user to select parameters
    m_State = STATE_SELECT_LISTEN_PARAMS;
    m_dwCurrItem = 0;
}




//-----------------------------------------------------------------------------
// Name: UpdateStateOnlineSearch()
// Desc: Searching for matching game session(s)
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateOnlineSearch( Event ev )
{
    assert( m_hMatchSearchTask != NULL );

    // Wait for matchmaking server to return results
    HRESULT hr = m_hMatchSearchTask.Continue();
    if( hr == XONLINETASK_S_RUNNING )
        return;

    // Handle errors
    if( FAILED(hr) )
    {
        m_UI.SetErrorStr( L"Session search failed with error %x", hr );
        Reset();
        return;
    }
    
    // Get the list returned by the matchmaking server
    PXONLINE_MATCH_SEARCHRESULT* ppSearchResult;
    DWORD dwResults;
    hr = XOnlineMatchSearchGetResults( m_hMatchSearchTask, &ppSearchResult,
                                       &dwResults );
    
    // Handle errors
    if( FAILED(hr) )
    {
        m_UI.SetErrorStr( L"Session search get results failed with error %x", hr );
        Reset();
        return;
    }

    // Save the results
    m_Sessions.clear();
    for( DWORD i = 0; i < dwResults; ++i )
    {
        m_Sessions.push_back( ppSearchResult[ i ]->HostAddress,
                              ppSearchResult[ i ]->SessionID,
                              ppSearchResult[ i ]->KeyExchangeKey );
    }
    
    // The search is over
    m_hMatchSearchTask.Close();

    // Bail out if no online sessions
    if( m_Sessions.empty() )
    {
        m_UI.SetErrorStr( L"No Online sessions available" );
        Reset();
        return;
    }

    // At least one online session
    BeginQosLookup();
    m_State = STATE_SESSION_LIST;
    m_dwCurrItem = 0;
}




//-----------------------------------------------------------------------------
// Name: UpdateStateSelectListenParams()
// Desc: Set the listener parameters
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateSelectListenParams( Event ev )
{
    // Handle any find session messages
    if( ProcessBroadcastMessage() )
        return;

    switch( ev )
    {
        default: break;
    case EV_BUTTON_A:
        switch( m_dwCurrItem )
        {
        case MENU_START_LOOKUPS:
            if( XNetXnKidIsSystemLink( &m_xnSessionID ) )
            {
                // Search for other System Link consoles running this title ID
                assert( !m_bIsSignedIn );
                m_State = STATE_SYSLINK_SEARCH;

                // Add ourself, to emulate the online case
                m_Sessions.clear();
                m_Sessions.push_back( m_xnTitleAddress, m_xnSessionID, 
                                      m_xnKeyExchangeKey );

                // Start looking for other System Link consoles
                SendFindSession();
                m_SysLinkSearchTimer.StartZero();
            }
            else
            {
                // Search for other Online consoles running this title ID
                assert( m_bIsSignedIn );
                m_State = STATE_ONLINE_SEARCH;
                BeginOnlineSearch();
            }
            break;

        case MENU_SET_LISTEN_STATE:
            // Update the listen state
            m_bListen = !m_bListen;
            SetListenState( m_bListen );
            break;
        
        default:
            break;
        }
        break;
        
    case EV_BUTTON_B:
        m_dwCurrItem = 0;
        m_State = STATE_SELECT_MODE;
        break;
        
    case EV_UP:
        // Move to previous item; allow wrap to bottom
        if( m_dwCurrItem == 0 )
            m_dwCurrItem = MENU_LISTEN_PARAMS_MAX - 1;
        else
            --m_dwCurrItem;
        break;
        
    case EV_DOWN:
        // Move to next item; allow wrap to top
        if( m_dwCurrItem == MENU_LISTEN_PARAMS_MAX - 1 )
            m_dwCurrItem = 0;
        else
            ++m_dwCurrItem;
        break;

    case EV_LEFT:
        // Move sliders
        switch( m_dwCurrItem )
        {
        case MENU_SET_LISTEN_STATE:
            m_bListen = !m_bListen;
            SetListenState( m_bListen );
            break;
        case MENU_NUM_SAMPLES:
            if( m_dwSamples > 0 )
                --m_dwSamples;
            break;
        case MENU_LISTEN_BANDWIDTH:
            if( m_dwListenBandwidth > MIN_LISTEN_BANDWIDTH &&
                m_dwListenBandwidth >= LISTEN_BANDWIDTH_CHUNK )
            {
                m_dwListenBandwidth -= LISTEN_BANDWIDTH_CHUNK;
                SetListenBitsPerSec( m_dwListenBandwidth );
            }
            break;
        case MENU_LOOKUP_BANDWIDTH:
            if( m_dwLookupBandwidth > MIN_LOOKUP_BANDWIDTH &&
                m_dwLookupBandwidth >= LOOKUP_BANDWIDTH_CHUNK )
                m_dwLookupBandwidth -= LOOKUP_BANDWIDTH_CHUNK;
            break;
        }
        break;

    case EV_RIGHT:
        // Move sliders
        switch( m_dwCurrItem )
        {
        case MENU_SET_LISTEN_STATE:
            m_bListen = !m_bListen;
            SetListenState( m_bListen );
            break;
        case MENU_NUM_SAMPLES:
            if( m_dwSamples < MAX_SAMPLES )
                ++m_dwSamples;
            break;
        case MENU_LISTEN_BANDWIDTH:
            if( m_dwListenBandwidth < LISTEN_BANDWIDTH_MAX )
            {
                m_dwListenBandwidth += LISTEN_BANDWIDTH_CHUNK;
                SetListenBitsPerSec( m_dwListenBandwidth );
            }
            break;
        case MENU_LOOKUP_BANDWIDTH:
            if( m_dwLookupBandwidth < LOOKUP_BANDWIDTH_MAX )
                m_dwLookupBandwidth += LOOKUP_BANDWIDTH_CHUNK;
            break;
        }
        break;

    case EV_BUTTON_WHITE:
        m_NextState = m_State;
        m_State = STATE_HELP;
        break;
    }
}




//-----------------------------------------------------------------------------
// Name: UpdateStateSessionList()
// Desc: Choose the desired session from the list
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateSessionList( Event ev )
{
    if( ProcessBroadcastMessage() )
        return;
        
    DWORD dwItems = m_pxnQos->cxnqos - 1;
    if( m_pxnServiceQos && m_bIsSignedIn )
        dwItems += m_pxnServiceQos->cxnqos;

    switch( ev )
    {
        default: break;
    case EV_BUTTON_A:
        m_State = STATE_SHOW_PROBE_DATA;
        break;
        
    case EV_BUTTON_B:
        m_dwCurrItem = 0;
        m_State = STATE_SELECT_LISTEN_PARAMS;
        break;
        
    case EV_UP:
        // Move to previous session; allow wrap to bottom
        if( m_dwCurrItem == 0 )
            m_dwCurrItem = dwItems;
        else
            --m_dwCurrItem;
        break;
        
    case EV_DOWN:
        // Move to next session; allow wrap to top
        if( m_dwCurrItem == dwItems )
            m_dwCurrItem = 0;
        else
            ++m_dwCurrItem;
        break;

    case EV_BUTTON_WHITE:
        m_NextState = m_State;
        m_State = STATE_HELP;
        break;
    }
}




//-----------------------------------------------------------------------------
// Name: UpdateStateShowProbeData()
// Desc: Show the data for a given listener
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateShowProbeData( Event ev )
{
    if( ProcessBroadcastMessage() )
        return;

    switch( ev )
    {
        default: break;
    case EV_BUTTON_B:
        m_State = STATE_SESSION_LIST;
        break;

    case EV_BUTTON_WHITE:
        m_NextState = m_State;
        m_State = STATE_HELP;
        break;
    }
}




//-----------------------------------------------------------------------------
// Name: UpdateStateError()
// Desc: Handle error screen
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateError( Event ev )
{
    switch( ev )
    {
        default: break;
    case EV_BUTTON_A:
        m_State = m_NextState;
        break;
    }
}




//-----------------------------------------------------------------------------
// Name: UpdateStateHelp()
// Desc: Handle help screen
//-----------------------------------------------------------------------------
VOID CXBoxSample::UpdateStateHelp( Event ev )
{
    switch( ev )
    {
        default: break;
    case EV_BUTTON_A:
    case EV_BUTTON_B:
    case EV_BUTTON_WHITE:
        m_State = m_NextState;
        break;
    }
}




//-----------------------------------------------------------------------------
// Name: BeginSignIn()
// Desc: Initiate the authentication process
//-----------------------------------------------------------------------------
VOID CXBoxSample::BeginSignIn()
{
    // Select a reasonable controller for the current player by choosing
    // the first controller found. Game code should do this much more
    // precisely. See below for details.
    for( m_dwUserIndex = 0; m_dwUserIndex < XGetPortCount(); ++m_dwUserIndex )
    {
        if( m_Gamepad[m_dwUserIndex].hDevice )
            break;
    }
    if( m_dwUserIndex >= XGetPortCount() )
        m_dwUserIndex = 0;
    
    // XOnlineLogon() allows a list of up to 4 players (1 per controller)
    // to sign-in in a single call. This sample shows how to authenticate
    // a single user. The list must be a one-to-one match of controller 
    // to player in order for the online system to recognize which player
    // is using which controller.
    XONLINE_USER pUserList[ XGetPortCount() ] = { 0 };
    CopyMemory( &pUserList[ m_dwUserIndex ], &m_UserList[ m_dwCurrUser ],
                sizeof( XONLINE_USER ) );
    
    // Initiate the sign in process. XOnlineTaskContinue() is used to poll
    // the status of the sign in.
    HRESULT hr = XOnlineLogon( pUserList, m_pServices, NUM_SERVICES, 
                               NULL, &m_hOnlineTask );
    
    if( FAILED(hr) )
    {
        m_hOnlineTask.Close();
        m_UI.SetErrorStr( L"Sign In failed to start. Error %x", hr );
        m_State = STATE_ERROR;
        m_NextState = STATE_SELECT_ACCOUNT;
    }
}




//-----------------------------------------------------------------------------
// Name: BeginOnlineSession()
// Desc: Initiate the game session creation process
//-----------------------------------------------------------------------------
VOID CXBoxSample::BeginOnlineSession()
{
    assert( m_hMatchCreateTask == NULL );

    HRESULT hr = XOnlineMatchSessionCreate( 1,  // public filled
                                            2,  // public open
                                            0,  // private filled
                                            0,  // private open
                                            0,  // attributes
                                            NULL,
                                            NULL, &m_hMatchCreateTask );
    
    if( FAILED( hr ) )
    {
        m_UI.SetErrorStr( L"Session failed to start. Error %x", hr );
        m_hOnlineTask.Close();
        m_bIsSignedIn = FALSE;
        m_State = STATE_ERROR;
        m_NextState = STATE_SELECT_ACCOUNT;
    }
}




//-----------------------------------------------------------------------------
// Name: BeginOnlineSearch()
// Desc: Initiate the game search process
//-----------------------------------------------------------------------------
VOID CXBoxSample::BeginOnlineSearch()
{
    assert( m_hMatchSearchTask == NULL );

    HRESULT hr = StartMatchQueryDefault( NULL, &m_hMatchSearchTask );

    if( FAILED(hr) )
    {
        m_UI.SetErrorStr( L"Session search failed to start. Error %x", hr );
        m_hOnlineTask.Close();
        m_bIsSignedIn = FALSE;
        m_State = STATE_ERROR;
        m_NextState = STATE_SELECT_ACCOUNT;
    }
}




//-----------------------------------------------------------------------------
// Name: SetPlayerState()
// Desc: Broadcast current player state for the world
//-----------------------------------------------------------------------------
VOID CXBoxSample::SetPlayerState( DWORD dwState )
{
    assert( m_bIsSignedIn );
    HRESULT hr = XOnlineNotificationSetState( m_dwUserIndex, dwState,
                                              m_xnSessionID, 0, NULL );
    assert( SUCCEEDED( hr ) );
    (VOID)hr; // avoid compiler warning
}




//-----------------------------------------------------------------------------
// Name: SetListenState()
// Desc: Update the QoS listen state for this console
//-----------------------------------------------------------------------------
VOID CXBoxSample::SetListenState( BOOL bListen )
{
    assert( m_bIsSessionRegistered );
    DWORD dwFlags = bListen ? XNET_QOS_LISTEN_ENABLE : XNET_QOS_LISTEN_DISABLE;
    INT iResult = XNetQosListen( &m_xnSessionID, NULL, 0, 0, dwFlags );
    assert( iResult == NO_ERROR );
    (VOID)iResult; // avoid compiler warnings
}




//-----------------------------------------------------------------------------
// Name: SetListenBitsPerSec()
// Desc: Update the QoS listen bits per second for this console
//-----------------------------------------------------------------------------
VOID CXBoxSample::SetListenBitsPerSec( DWORD dwBitsPerSec )
{
    assert( m_bIsSessionRegistered );
    INT iResult = XNetQosListen( &m_xnSessionID, NULL, 0, 
                                 dwBitsPerSec, XNET_QOS_LISTEN_SET_BITSPERSEC );
    assert( iResult == NO_ERROR );
    (VOID)iResult; // avoid compiler warnings
}




//-----------------------------------------------------------------------------
// Name: SetListenData()
// Desc: Update the QoS listen data for this console
//-----------------------------------------------------------------------------
VOID CXBoxSample::SetListenData( const VOID* pData, DWORD dwBytes )
{
    assert( m_bIsSessionRegistered );
    DWORD dwFlags = XNET_QOS_LISTEN_SET_DATA;
    INT iResult = XNetQosListen( &m_xnSessionID, (const BYTE*)pData, dwBytes, 
                                 0, dwFlags );
    assert( iResult == NO_ERROR );
    (VOID)iResult; // avoid compiler warnings
}




//-----------------------------------------------------------------------------
// Name: SendFindSession()
// Desc: Broadcast a MSG_FIND_SESSION from our client to any available host.
//       Used for System Link only
//-----------------------------------------------------------------------------
VOID CXBoxSample::SendFindSession()
{
    Message msgFindSession( MSG_FIND_SESSION );
    MsgFindSession& msg = msgFindSession.GetFindSession();

    // Generate a nonce (random bytes). When a potential host responds with
    // information about a session, he must respond via a broadcast message
    // since a secure session hasn't been established. The broadcast message
    // will contain the same nonce so we can verify that message is really
    // for us. If we receive a broadcast "found session" message with a different
    // nonce, we ignore it, because it was broadcast to a different client
    // than us.
    INT iResult = XNetRandom( (BYTE*)(&msg.nonce), sizeof(msg.nonce) );
    assert( iResult == NO_ERROR );
    (VOID)iResult;

    // Save the nonce for comparison later
    CopyMemory( &m_Nonce, &msg.nonce, sizeof(msg.nonce) );

    SOCKADDR_IN saBroad;
    saBroad.sin_family      = AF_INET;
    saBroad.sin_addr.s_addr = INADDR_BROADCAST;
    saBroad.sin_port        = htons( BROADCAST_PORT );
    INT nBytes = m_BroadSock.SendTo( &msgFindSession, msgFindSession.GetSize(),
                                     &saBroad );
    // This assert was removed because Send no longer is guaranteed to always work
    // If the security association times out, the number of bytes returned will 
    // NOT be equal to the size of the message.  A good thing to do here would
    // be to drop the player
    //assert( nBytes == msgFindSession.GetSize() );
    (VOID)nBytes;
}




//-----------------------------------------------------------------------------
// Name: SendSessionFound()
// Desc: Broadcast a MSG_SESSION_FOUND from our host to the world.
//       Used for System Link only
//-----------------------------------------------------------------------------
VOID CXBoxSample::SendSessionFound( const Nonce& nonceClient )
{
    Message msgSessionFound( MSG_SESSION_FOUND );
    MsgSessionFound& msg = msgSessionFound.GetSessionFound();

    // Resend the nonce that we received from the client so he can verify
    // that this message is really for him
    CopyMemory( &msg.nonce, &nonceClient, sizeof(nonceClient) );

    // Send information about us so the client can issue a QoS lookup
    CopyMemory( &msg.xnAddr, &m_xnTitleAddress,   sizeof(XNADDR) );
    CopyMemory( &msg.xnKid,  &m_xnSessionID,      sizeof(XNKID) );
    CopyMemory( &msg.xnKey,  &m_xnKeyExchangeKey, sizeof(XNKEY) );

    // We don't have the XNADDR of the requesting client, so we
    // can't send this message directly back. Instead, we broadcast the
    // message to everybody on the net. The requesting client can
    // check the nonce to verify that the response is really for them.

    SOCKADDR_IN saBroad;
    saBroad.sin_family      = AF_INET;
    saBroad.sin_addr.s_addr = INADDR_BROADCAST;
    saBroad.sin_port        = htons( BROADCAST_PORT );
    INT nBytes = m_BroadSock.SendTo( &msgSessionFound, msgSessionFound.GetSize(),
                                     &saBroad );
    // This assert was removed because Send no longer is guaranteed to always work
    // If the security association times out, the number of bytes returned will 
    // NOT be equal to the size of the message.  A good thing to do here would
    // be to drop the player
    //assert( nBytes == msgSessionFound.GetSize() );
    (VOID)nBytes;
}




//-----------------------------------------------------------------------------
// Name: ProcessBroadcastMessage()
// Desc: Checks to see if any broadcast messages are waiting on the broadcast
//       socket. If a message is waiting, it is routed and processed.
//       If no messages are waiting, the function returns immediately.
//       Returns TRUE if a message was processed. Used for System Link only.
//-----------------------------------------------------------------------------
BOOL CXBoxSample::ProcessBroadcastMessage()
{
    if( !m_BroadSock.IsOpen() )
        return FALSE;

    // See if a network broadcast message is waiting for us
    Message msg;
    INT iResult = m_BroadSock.Recv( &msg, msg.GetMaxSize() );

    // If message waiting, process it
    if( iResult != SOCKET_ERROR && iResult > 0 )
    {
        assert( iResult == msg.GetSize() );

        // Process the message
        switch( msg.GetId() )
        {
            case MSG_FIND_SESSION:  ProcessFindSession( msg.GetFindSession() ); break;
            case MSG_SESSION_FOUND: ProcessSessionFound( msg.GetSessionFound() ); break;
            default: assert( FALSE ); break;
        }
        return TRUE;
    }
    return FALSE;
}




//-----------------------------------------------------------------------------
// Name: ProcessFindSession()
// Desc: Process the find session message. Used for System Link only.
//-----------------------------------------------------------------------------
VOID CXBoxSample::ProcessFindSession( const MsgFindSession& findSession )
{
    // Respond with the information about this session
    SendSessionFound( findSession.nonce );
}




//-----------------------------------------------------------------------------
// Name: ProcessSessionFound()
// Desc: Process the session found message. Used for System Link only.
//-----------------------------------------------------------------------------
VOID CXBoxSample::ProcessSessionFound( const MsgSessionFound& sessionFound )
{
    // If we didn't send the corresponding "find session" message, we don't
    // care about this particular "session found" message
    if( memcmp( &sessionFound.nonce, &m_Nonce, NONCE_BYTES ) != 0 )
        return;

    // We found a session on another console!
    // Add it to our list of potential sessions

    m_Sessions.push_back( sessionFound.xnAddr, sessionFound.xnKid,
                          sessionFound.xnKey );

    // If the list is full, move on to the next stage
    if( m_Sessions.size() == MAX_SESSIONS )
    {
        BeginQosLookup();
        m_State = STATE_SESSION_LIST;
    }
}




//-----------------------------------------------------------------------------
// Name: BeginQosLookup()
// Desc: Initiate the QoS lookup
//-----------------------------------------------------------------------------
VOID CXBoxSample::BeginQosLookup()
{
    // If online, query the Matchmaking Security Gateway, too. There are 
    // two ways to probe SGs. The deprecated method is to use parameters 
    // 5-7 of XNetQosLookup. The new way is to use XNetQosServiceLookup.
    // For completeness, this code shows both methods.
    
    // NOTE: Resulting bandwidth values are only rough estimates, and are not
    // always accurate indicators of true bandwidth conditions. They are only
    // useful in comparing relative bandwidths of various consoles, and should
    // not be diplayed or used to set player maximums or other similar game 
    // restrictions.
    
    XONLINE_SERVICE_INFO info;
    IN_ADDR* pSecurityGateway = NULL;
    DWORD* pServiceID = NULL;
    DWORD dwSecurityGateway = 0;
    if( m_bIsSignedIn )
    {
        // m_pServices[0] is XONLINE_MATCHMAKING_SERVICE
        HRESULT hr = XOnlineGetServiceInfo( m_pServices[0], &info );
        
        // Obtain the service info for XNetQosLookup
        if( SUCCEEDED(hr) )
        {
            dwSecurityGateway = 1;
            pSecurityGateway = &info.serviceIP;
            pServiceID = &info.dwServiceID;
        }
    }

    INT iResult = XNetQosLookup( m_Sessions.size(),
                                 m_Sessions.GetXnAddrs(),
                                 m_Sessions.GetXnKids(),
                                 m_Sessions.GetXnKeys(),
                                 dwSecurityGateway,   // Security Gateways
                                 pSecurityGateway,    // SG IN_ADDRs
                                 pServiceID,          // SG service IDs
                                 m_dwSamples,         // Probe samples
                                 m_dwLookupBandwidth, // lookup bandwidth max
                                 0,                   // flags
                                 NULL,                // optional event
                                 &m_pxnQos );

    assert( iResult == NO_ERROR );
    (VOID)iResult;

    // The heavyweight method of determining SG bandwidth    
    if( m_bIsSignedIn )
    {
        // Automatically uses 24 probes of significantly larger 
        // sizes than XNetQosLookup to make a better
        // bandwidth estimate (though still far from perfect).
        // Automatically uses a maximum lookup bandwidth of 64 Kb/s.
        iResult = XNetQosServiceLookup( 0, NULL, &m_pxnServiceQos );
        assert( iResult == NO_ERROR );
    }
}




//-----------------------------------------------------------------------------
// Name: Reset()
// Desc: Common clean up and return to start
//-----------------------------------------------------------------------------
VOID CXBoxSample::Reset()
{
    EndOnlineListen();
    EndSysLinkListen();
    m_hMatchCreateTask.Close();
    m_hMatchSearchTask.Close();
    m_SysLinkSearchTimer.Stop();
    m_dwCurrItem = 0;
    m_State = STATE_ERROR;
    m_NextState = STATE_SELECT_MODE;
    XNetQosRelease( m_pxnQos );
    XNetQosRelease( m_pxnServiceQos );
    m_pxnQos = NULL;
    m_pxnServiceQos = NULL;
}




//-----------------------------------------------------------------------------
// Name: BeginOnlineListen()
// Desc: Initialize listener for online mode
//-----------------------------------------------------------------------------
VOID CXBoxSample::BeginOnlineListen()
{
    assert( m_bIsSignedIn );
    assert( m_bIsSessionRegistered );

    // Notify the world of our status
    DWORD dwState = XONLINE_FRIENDSTATE_FLAG_ONLINE;
    if( XBVoice_HasDevice() )
        dwState |= XONLINE_FRIENDSTATE_FLAG_VOICE;
    SetPlayerState( dwState );
            
    // Function required that we've registered an online session 
    // (m_xnSessionID) with Matchmaking

    // Default to listen when System Link is chosen
    m_bListen = TRUE;
    SetListenState( m_bListen );

    // Set the response data to our session name
    SetListenData( m_strSessionName, 
                   ( lstrlenW( m_strSessionName ) + 1 ) * sizeof(WCHAR) );
}




//-----------------------------------------------------------------------------
// Name: EndOnlineListen()
// Desc: Clean up from online mode
//-----------------------------------------------------------------------------
VOID CXBoxSample::EndOnlineListen()
{
    if( !m_bIsSignedIn )
        return;

    // Notify the world of our status
    SetPlayerState( XONLINE_FRIENDSTATE_FLAG_NONE );

    if( m_bIsSessionRegistered )
    {
        // Asynchronous session removal from Matchmaking service. This would normally
        // be pumped by the game in the main loop. For simplicity, this sample
        // pumps the deletion task to completion without yielding.
        CXBOnlineTask hDelete;
        HRESULT hr = XOnlineMatchSessionDelete( m_xnSessionID, NULL, &hDelete );
        if( SUCCEEDED(hr) )
        {
            for( hr = XONLINETASK_S_RUNNING; hr == XONLINETASK_S_RUNNING; )
                hr = hDelete.Continue();
        }

        // XNetUnregisterKey will automatically release the QoS listener
        INT iResult = XNetUnregisterKey( &m_xnSessionID );
        assert( iResult == NO_ERROR );
        (VOID)iResult;
        m_bIsSessionRegistered = FALSE;
        ZeroMemory( &m_xnSessionID, sizeof( XNKID ) );

        m_bIsSessionRegistered = FALSE;
    }

    // Sign off
    m_hOnlineTask.Close();
    m_bIsSignedIn = FALSE;
}




//-----------------------------------------------------------------------------
// Name: BeginSysLinkListen()
// Desc: Initialize for System Link mode
//-----------------------------------------------------------------------------
VOID CXBoxSample::BeginSysLinkListen()
{
    assert( !m_bIsSignedIn );

    if( !m_bIsSessionRegistered )
    {
        // Register the session for System Link
        INT iKeyCreated = XNetCreateKey( &m_xnSessionID, &m_xnKeyExchangeKey );
        assert( iKeyCreated == NO_ERROR );
        (VOID)iKeyCreated; // avoid compiler warnings

        // Register the session
        INT iKeyRegistered = XNetRegisterKey( &m_xnSessionID, &m_xnKeyExchangeKey );
        assert( iKeyRegistered == NO_ERROR );
        (VOID)iKeyRegistered; // avoid compiler warnings

        m_bIsSessionRegistered = TRUE;

        // Default to listen when System Link is chosen
        m_bListen = TRUE;
        SetListenState( m_bListen );

        // Set the response data to our session name
        SetListenData( m_strSessionName, 
                       ( lstrlenW( m_strSessionName ) + 1 ) * sizeof(WCHAR) );
    }

    if( !m_BroadSock.IsOpen() )
    {
        // Create broadcast socket for System Link testing
        // The broadcast socket is a non-blocking socket on port BROADCAST_PORT.
        BOOL bSuccess = m_BroadSock.Open( CXBSocket::Type_UDP );
        assert( bSuccess );
        (VOID)bSuccess;

        SOCKADDR_IN broadAddr;
        broadAddr.sin_family      = AF_INET;
        broadAddr.sin_addr.s_addr = INADDR_ANY;
        broadAddr.sin_port        = htons( BROADCAST_PORT );
        INT iResult = m_BroadSock.Bind( &broadAddr );
        assert( iResult != SOCKET_ERROR );
        DWORD dwNonBlocking = 1;
        iResult = m_BroadSock.IoCtlSocket( FIONBIO, &dwNonBlocking );
        assert( iResult != SOCKET_ERROR );
        BOOL bBroadcast = TRUE;
        iResult = m_BroadSock.SetSockOpt( SOL_SOCKET, SO_BROADCAST,
                                          &bBroadcast, sizeof(bBroadcast) );
        assert( iResult != SOCKET_ERROR );
    }
}




//-----------------------------------------------------------------------------
// Name: EndSysLinkListen()
// Desc: Clean up from System Link mode
//-----------------------------------------------------------------------------
VOID CXBoxSample::EndSysLinkListen()
{
    if( m_bIsSignedIn )
        return;

    // Release the listener and unregister the key
    if( m_bIsSessionRegistered )
    {
        // XNetUnregisterKey will automatically release the QoS listener
        INT iResult = XNetUnregisterKey( &m_xnSessionID );
        assert( iResult == NO_ERROR );
        (VOID)iResult;
        m_bIsSessionRegistered = FALSE;
        ZeroMemory( &m_xnSessionID, sizeof( XNKID ) );
    }

    // Close the socket used to find System Link sessions
    m_BroadSock.Close();
}

