// Automatically generated by the bundler tool from textures.rdf

#define textures_NUM_RESOURCES 12UL

#define textures_Bigmap_OFFSET 352UL
#define textures_Fish_OFFSET 372UL
#define textures_Frond_OFFSET 392UL
#define textures_House_OFFSET 412UL
#define textures_PeninsulaMap_OFFSET 432UL
#define textures_Pier_OFFSET 452UL
#define textures_ShipBurn2_OFFSET 472UL
#define textures_TallRock_OFFSET 492UL
#define textures_TeeRexMap_OFFSET 512UL
#define textures_Tower_OFFSET 532UL
#define textures_Trunk_OFFSET 552UL
#define textures_Weapons_OFFSET 572UL
