// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 13UL

#define resource_Shimmer0_OFFSET 304UL
#define resource_Shimmer1_OFFSET 324UL
#define resource_Shimmer2_OFFSET 344UL
#define resource_DesertSky_front_OFFSET 364UL
#define resource_DesertSky_back_OFFSET 384UL
#define resource_DesertSky_left_OFFSET 404UL
#define resource_DesertSky_right_OFFSET 424UL
#define resource_DesertSky_up_OFFSET 444UL
#define resource_Cactus_OFFSET 464UL
#define resource_Clump_OFFSET 484UL
#define resource_Desert_Color_OFFSET 504UL
#define resource_Rock_OFFSET 524UL
#define resource_Tower_OFFSET 544UL
