// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 8UL

#define resource_Treebark_OFFSET 176UL
#define resource_VolGroun_OFFSET 196UL
#define resource_SkyBoxXN_OFFSET 216UL
#define resource_SkyBoxXP_OFFSET 236UL
#define resource_SkyBoxYN_OFFSET 256UL
#define resource_SkyBoxYP_OFFSET 276UL
#define resource_SkyBoxZN_OFFSET 296UL
#define resource_SkyBoxZP_OFFSET 316UL
