//
// XactSounds.h - generated by xactbld from the XACT project (.xap).
// Do not edit.
//

#ifndef __XACTSOUNDS_H__
#define __XACTSOUNDS_H__

// Sound bank "SoundBank" cue indices
typedef enum XACT_SOUNDBANK_SOUNDBANK
{
    XACT_SOUNDBANK_SOUNDBANK_MUSICMONO = 0,
    XACT_SOUNDBANK_SOUNDBANK_CUE_COUNT = 1,
} XACT_SOUNDBANK_SOUNDBANK;

// Wave bank "WaveBank" entry indices
typedef enum XACT_WAVEBANK_WAVEBANK
{
    XACT_WAVEBANK_WAVEBANK_MUSICMONO = 0,
    XACT_WAVEBANK_WAVEBANK_ENTRY_COUNT = 1,
} XACT_WAVEBANK_WAVEBANK;

#endif
