////////////////////////////////////////////////////////////////////////////////
// STinyObj.cpp
//
// Desc: small object allocator customized. Allocates small blocks faster
// than new/delete. Requires customization to reserve the appropriate
// amount of memory. Usually used via PoolAlloc
//
// Example Usage:
//
//     TinyObjAllocator& allocator = GetTinyObjAllocator();
//     void* ptr = allocator.Allocate(10);
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------

#include "TinyObj.h"
#include <xtl.h>
#include <cassert>
#ifdef  _DEBUG
#include <cstdio>
#endif


// Default to using gobs of memory. Define this to use a more refined amount of memory.
// #define USE_TUNED_MEMORY_AMOUNTS

TinyObjAllocator::TinyObjAllocator()
{
#ifdef  USE_TUNED_MEMORY_AMOUNTS
    // Set minimumNumBlocks to some appropriate number to help ensure
    // that enough memory is always reserved.
    int minimumNumBlocks = 100;

    // Set safetyMargin to some small number greater than one to leave room
    // for more memory allocations than expected. Setting it too large
    // wastes memory, setting it too slow risks running out of memory.
    float safetyMargin = 2;

    // This table was generated by calling DumpStats in a place assumed to use
    // near the maximum amount of memory. This ensures that the appropriate
    // amount of each type of memory is allocated.
    size_t maxAllocations[kNumBlockSizes] =
    {
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
        int(minimumNumBlocks + 0 * safetyMargin),
    };
#endif

    size_t totalMemoryUsage = 0;
    for (int i = 0; i < kNumBlockSizes; ++i)
    {
#ifdef  USE_TUNED_MEMORY_AMOUNTS
        // Reserve just the right amount of memory, determined by previous runs.
        size_t numBlocks = maxAllocations[i];
#else
        // Default to allocating a huge number of blocks - handy for getting going,
        // but very wasteful.
        size_t numBlocks = 20000;
#endif
        totalMemoryUsage += numBlocks * (i + 1) * kGranularity;
        m_allocators[i].Init((i + 1) * kGranularity, numBlocks);
    }
#ifdef  _DEBUG
    char    buffer[1000];
    sprintf(buffer, "%d bytes reserved by TinyObjAllocator\n", totalMemoryUsage);
    OutputDebugStringA(buffer);
#endif

    // With a granularity of 4, allocations from 1-4 bytes all use allocator zero,
    // allocations 5-8 bytes all use allocator one, and so on.
    for (int size = 0; size < (sizeof(m_pAllocators) / sizeof(m_pAllocators[0])); ++size)
    {
        int index;
        if (size == 0)
            index = 0;
        else
            index = (size - 1) / kGranularity;
        m_pAllocators[size] = &m_allocators[index];
    }
}

#ifdef  _DEBUG
void TinyObjAllocator::DumpStats() const
{
    // Use these stats to initialize the allocators to appropriate sizes.
    char    outputBuffer[5000] = "";
    char*   output = outputBuffer;
    output += sprintf(output, "// Paste this array into the TinyObjAllocator constructor, define\n"
                              "// USE_TUNED_MEMORY_AMOUNTS and adjust safetyMargin and minimumNumBlocks\n"
                              "// to tune TinyObjAllocator to reserve the appropriate amount of memory.\n");
    output += sprintf(output, "size_t maxAllocations[kNumBlockSizes] =\n{\n");
    size_t currentlyAllocated = 0;
    for (int i = 0; i < sizeof(m_allocators) / sizeof(m_allocators[0]); ++i)
    {
        output += sprintf(output, "\tint(minimumNumBlocks + %d * safetyMargin),\n", m_allocators[i].m_maximumAllocated);
        currentlyAllocated += m_allocators[i].m_allocated * m_allocators[i].m_blockSize;
    }
    output += sprintf(output, "};\n");
    output += sprintf(output, "\n%d bytes currently allocated by TinyObjAllocator.\n", currentlyAllocated);
    OutputDebugStringA(outputBuffer);
}
#endif

TinyObjAllocator::~TinyObjAllocator()
{
    // Shouldn't ever get here.
    __asm {int 3}
}

void* TinyObjAllocator::Allocate(size_t size)
{
    if (size > kGranularity * kNumBlockSizes)
        return operator new(size);

    return m_pAllocators[size]->Allocate();
}

void TinyObjAllocator::Deallocate(void* ptr, size_t size)
{
    if (size > kGranularity * kNumBlockSizes)
        return operator delete(ptr);

    return m_pAllocators[size]->Deallocate(ptr);
}



TinyObjAllocator::FixedBlockAllocator::FixedBlockAllocator()
{
    m_nodes = 0;
#ifdef  _DEBUG
    m_allocated = 0;
    m_maximumAllocated = 0;
    m_blockSize = 0;
    m_numBlocks = 0;
#endif
}

TinyObjAllocator::FixedBlockAllocator::~FixedBlockAllocator()
{
    // Shouldn't ever get here.
    __asm {int 3}
}

void TinyObjAllocator::FixedBlockAllocator::Init(size_t blockSize, size_t numBlocks)
{
#ifdef  _DEBUG
    assert(m_blockSize == 0);
    m_blockSize = blockSize;
    m_numBlocks = numBlocks;
#endif
    char* block = new char[blockSize * numBlocks];
    for (size_t i = 0; i < numBlocks; ++i)
    {
        // Add the new block onto the list.
        char* ptr = block + blockSize * i;
        *((char**)ptr) = m_nodes;
        m_nodes = (char*)ptr;
    }
}

void* TinyObjAllocator::FixedBlockAllocator::Allocate()
{
#ifdef  _DEBUG
    ++m_allocated;
    if (m_allocated > m_maximumAllocated)
        m_maximumAllocated = m_allocated;
#endif

    // Remove the first item from the list and return it.
    char* result = m_nodes;
#ifdef  _DEBUG
    if (!result)
    {
        OutputDebugStringA("Error: ran out of memory in TinyObjAllocator. Use DumpStats to adjust\n"
                          "the TinyObjAllocator constructor to reserve more blocks.\n");
        __asm int 3
    }
#endif
    m_nodes = *((char**)m_nodes);
    return result;
}

void TinyObjAllocator::FixedBlockAllocator::Deallocate(void* ptr)
{
    // STL allocators and operator delete both explicitly promise to
    // handle delete of zero, by doing nothing. So, we have to handle
    // it, or else very bad things happen.
    if (!ptr)
        return;
#ifdef  _DEBUG
    --m_allocated;
#endif

    // Add the freed block onto the list.
    *((char**)ptr) = m_nodes;
    m_nodes = (char*)ptr;
}



// Function to get the global tiny object allocator. The object must be stored
// in a function to guarantee order of initialization. Cache the result for
// best performance.

TinyObjAllocator& GetTinyObjAllocator()
{
    static TinyObjAllocator object;
    return object;
}
