//-----------------------------------------------------------------------------
// File: Main.cpp
//
// Desc: Simple app to play a streaming sound and render the percent completion
//       of the sound.
//
// Hist: 12.15.00 - New for December XDK release
//       03.15.01 - Updated for April XDK 
//       03.06.02 - Added audio level meters for April 02 XDK release
//       10.04.02 - Cleaned up for the November 2002 XDK release
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------
#include <xbapp.h>
#include <xbfont.h>
#include <xbhelp.h>
#include <xbsound.h>
#include <xbutil.h>
#include "wmastream.h"
#include "dsstdfx.h"


//-----------------------------------------------------------------------------
// Callouts for labelling the gamepad on the help screen
//-----------------------------------------------------------------------------
XBHELP_CALLOUT g_HelpCallouts[] = 
{
    { XBHELP_BACK_BUTTON,  XBHELP_PLACEMENT_2, L"Display help" },
    { XBHELP_A_BUTTON,     XBHELP_PLACEMENT_2, L"Pause" },
};

const DWORD NUM_HELP_CALLOUTS = sizeof(g_HelpCallouts) / sizeof(g_HelpCallouts[0]);




//-----------------------------------------------------------------------------
// Name: class CXBoxSample
// Desc: Application class.
//-----------------------------------------------------------------------------
class CXBoxSample : public CXBApplication
{
    CWMAFileStream m_Stream;        // The WMA stream
    CXBFont        m_Font;          // A font to render text
    CXBHelp        m_Help;          // Help object
    BOOL           m_bDrawHelp;     // Should we draw help?
    DWORD          m_dwPercentCompleted;    // Percentage of file processed

    BOOL           m_bPaused;       // Paused?

    LPDIRECTSOUND8 m_pDSound;       // DirectSound object

    HRESULT DownloadEffectsImage( CHAR* strScratchFile );  // downloads a default DSP image to the GP

public:
    virtual HRESULT Initialize();
    virtual HRESULT Render();
    virtual HRESULT FrameMove();

    CXBoxSample();
};




//-----------------------------------------------------------------------------
// Name: Main()
// Desc: Entry point to the program.
//-----------------------------------------------------------------------------
VOID __cdecl main()
{
    CXBoxSample xbApp;
    if( FAILED( xbApp.Create() ) )
        return;
    xbApp.Run();
}




//-----------------------------------------------------------------------------
// Name: CXBoxSample()
// Desc: Constructor
//-----------------------------------------------------------------------------
CXBoxSample::CXBoxSample()
{
}




//-----------------------------------------------------------------------------
// Name: DownloadEffectsImage()
// Desc: Downloads an effects image to the DSP
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::DownloadEffectsImage( CHAR* strScratchFile )
{
    HANDLE hFile;
    DWORD dwSize = 0;
    BYTE* pBuffer = NULL;   // allocated as new BYTE[]; typed so delete[] is well-formed
    HRESULT hr = S_OK;
    LPDSEFFECTIMAGEDESC pDesc;
    DSEFFECTIMAGELOC EffectLoc;

    // Open DSP Image generated by xgpimage or DSPBuilder
    hFile = CreateFile( strScratchFile, GENERIC_READ, 0, NULL,
                        OPEN_EXISTING, 0, NULL );
    if( hFile == INVALID_HANDLE_VALUE )
    {
        OUTPUT_DEBUG_STRING( "Failed to open the dsp image file.\n" );
        DWORD err = GetLastError();
        hr = HRESULT_FROM_WIN32(err);
    }

    if( SUCCEEDED(hr) )
    {
        // Determine the size of the scratch image by seeking to
        // the end of the file
        dwSize = SetFilePointer( hFile, 0, NULL, FILE_END );
        SetFilePointer(hFile, 0, NULL, FILE_BEGIN);
    
        // Allocate memory to read the scratch image from disk
        pBuffer = new BYTE[dwSize];

        // Read the image in
        DWORD dwBytesRead;
        BOOL bResult = ReadFile( hFile, pBuffer, dwSize, &dwBytesRead, 0 );
        if (!bResult)
        {
            OUTPUT_DEBUG_STRING( "\n Failed to open the dsp image file.\n" );
            DWORD err = GetLastError();
            hr = HRESULT_FROM_WIN32(err);
        }
    }

    if( SUCCEEDED(hr) )
    {
        // Call DSound API to download the image..
        EffectLoc.dwI3DL2ReverbIndex = GraphI3DL2_I3DL2Reverb;
        EffectLoc.dwCrosstalkIndex   = GraphXTalk_XTalk;

        hr = m_pDSound->DownloadEffectsImage( pBuffer, dwSize, &EffectLoc, &pDesc );
    }

    delete[] pBuffer;

    if( hFile != INVALID_HANDLE_VALUE ) 
        CloseHandle( hFile );

    return hr;
}




//-----------------------------------------------------------------------------
// Name: Initialize()
// Desc: Performs whatever initialization the sample needs
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::Initialize()
{
    // Create a WMA stream
    if( FAILED( m_Stream.Initialize( "D:\\Media\\Sounds\\Becky.wma" ) ) )
        return E_FAIL;

    // Create a font
    if( FAILED( m_Font.Create( "Font.xpr" ) ) )
        return XBAPPERR_MEDIANOTFOUND;

    // Create help
    if( FAILED( m_Help.Create( "Gamepad.xpr" ) ) )
        return XBAPPERR_MEDIANOTFOUND;

    // Create the DirectSound object
    if( FAILED( DirectSoundCreate( NULL, &m_pDSound, NULL ) ) )
        return E_FAIL;

    // download the standard DirectSound effects image
    if( FAILED( DownloadEffectsImage((CHAR*)"d:\\media\\dsstdfx.bin") ) )
        return E_FAIL;

    m_bDrawHelp = FALSE;
    m_bPaused = FALSE;

    m_dwPercentCompleted = 0;

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: FrameMove()
// Desc: Called once per frame to update state
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::FrameMove()
{
    // Let the WMA decoder do some work
    m_Stream.Process( &m_dwPercentCompleted );
    DirectSoundDoWork();

    // Toggle help
    if( m_DefaultGamepad.wPressedButtons & XINPUT_GAMEPAD_BACK ) 
    {
        m_bDrawHelp = !m_bDrawHelp;
    }

    // Toggle pause
    if( m_DefaultGamepad.bPressedAnalogButtons[ XINPUT_GAMEPAD_A ] )
    {
        m_bPaused = !m_bPaused;
        m_Stream.Pause( m_bPaused ? DSSTREAMPAUSE_PAUSE : DSSTREAMPAUSE_RESUME );
    }

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: Render()
// Desc: Renders the scene
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::Render()
{
    // Render the scene (which is just the progress bar)
    m_pd3dDevice->Clear( 0L, NULL, D3DCLEAR_TARGET, 0xff0000ff, 1.0f, 0L );

    // Temporary buffer for building strings to display
    WCHAR str[256];

    if( E_PENDING == m_Stream.GetOpenResult() )
    {
        m_Font.DrawText( 64, 50, 0xffffffff, L"Loading WMA file..." );
    }
    else if( E_FAIL == m_Stream.GetOpenResult() )
    {
        // If didn't open the WMA file
        wsprintfW( str, L"Failed to load WMA; HRESULT: 0x%X", m_Stream.GetOpenResult() );
        m_Font.DrawText( 64,  50, 0xffffffff, str );
    }
    else
    {
        // Show title, frame rate, and help
        if( m_bDrawHelp )
            m_Help.Render( &m_Font, g_HelpCallouts, NUM_HELP_CALLOUTS );
        else
        {
            // Draw the text
            m_Font.SetScaleFactors( 1.2f, 1.2f );
            m_Font.DrawText( 48, 36, 0xffffffff, L"WMAStream" );
            m_Font.SetScaleFactors( 1.0f, 1.0f );

            // Print out Track Length in ms          
            swprintf( str, L"%d ms", m_Stream.m_WmaFileHeader.dwDuration );
            m_Font.DrawText( 64, 275, 0xffffffff, L"Track Length: " );
            m_Font.DrawText( 0xffffff00, str );

            // Print out Track Name
            m_Font.DrawText( 64, 300, 0xffffffff, L"Track Name: " );
            m_Font.DrawText( 0xffffff00, m_Stream.m_strWmaTitle );

            // Print out Track Name
            m_Font.DrawText( 64, 325, 0xffffffff, L"Author: " );
            m_Font.DrawText( 0xffffff00, m_Stream.m_strWmaAuthor );
        }

        m_Font.DrawText( 64, 375, 0xffffffff, L"Progress:" );
        m_Font.DrawText( 0xff808080, m_bPaused ? L" (paused)" : L"" );

        // Render a simple progress bar to show the percent completed
        struct BACKGROUNDVERTEX { D3DXVECTOR4 p; D3DCOLOR color; };
        BACKGROUNDVERTEX v[8];
        FLOAT x1 = 64;
        FLOAT x2 = x1 + ( 512 * m_dwPercentCompleted ) / 100;
        FLOAT x3 = 64 + 512;
        FLOAT y1 = 400;
        FLOAT y2 = y1 + 20;
        v[0].p = D3DXVECTOR4( x1-0.5f, y1-0.5f, 1.0f, 1.0f );  v[0].color = 0xffffff00;
        v[1].p = D3DXVECTOR4( x2-0.5f, y1-0.5f, 1.0f, 1.0f );  v[1].color = 0xffffff00;
        v[2].p = D3DXVECTOR4( x2-0.5f, y2-0.5f, 1.0f, 1.0f );  v[2].color = 0xffffff00;
        v[3].p = D3DXVECTOR4( x1-0.5f, y2-0.5f, 1.0f, 1.0f );  v[3].color = 0xffffff00;
        v[4].p = D3DXVECTOR4( x2-0.5f, y1-0.5f, 1.0f, 1.0f );  v[4].color = 0xff8080ff;
        v[5].p = D3DXVECTOR4( x3-0.5f, y1-0.5f, 1.0f, 1.0f );  v[5].color = 0xff8080ff;
        v[6].p = D3DXVECTOR4( x3-0.5f, y2-0.5f, 1.0f, 1.0f );  v[6].color = 0xff8080ff;
        v[7].p = D3DXVECTOR4( x2-0.5f, y2-0.5f, 1.0f, 1.0f );  v[7].color = 0xff8080ff;

        m_pd3dDevice->SetTextureStageState( 0, D3DTSS_COLOROP, D3DTOP_DISABLE );
        m_pd3dDevice->SetVertexShader( D3DFVF_XYZRHW|D3DFVF_DIFFUSE );
        m_pd3dDevice->DrawPrimitiveUP( D3DPT_QUADLIST, 2, v, sizeof(v[0]) );
    }
    
    // Draw the on-screen audio level meters
    XBSound_DrawLevelMeters( m_pDSound, 64.0f, 340.0f, 60.0f, 30.0f );

    // Present the scene
    m_pd3dDevice->Present( NULL, NULL, NULL, NULL );

    return S_OK;
}
