// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 9UL

#define resource_Target_OFFSET 176UL
#define resource_BulletHole_OFFSET 196UL
#define resource_MatteBlack_OFFSET 216UL
#define resource_ShinyBlack_OFFSET 236UL
#define resource_GreenGlass_OFFSET 256UL
#define resource_WhiteGlass_OFFSET 276UL
#define resource_RedGlass_OFFSET 296UL
#define resource_BlueGlass_OFFSET 316UL
#define resource_YellowGlass_OFFSET 336UL
