// Automatically generated by the bundler tool from Resource.rdf

#define Resource_NUM_RESOURCES 2UL

#define Resource_SkyBoxColorLookupTable_OFFSET 80UL
#define Resource_SkyBoxLuminanceCubeMap_OFFSET 100UL
