//------------------------------------------------------------------------------
//
// Xbox Competitions Implementations
// Generated by XLAST Competitions Version 1.00.5849.4 at Mon, Nov 29, 2004 11:28
// Title ID: ffedaaab
// Project Name: comps
//------------------------------------------------------------------------------
#include "Comps.h"




//------------------------------------------------------------------------------
// Implementation for the SE competition type
//------------------------------------------------------------------------------
CONST WCHAR wszDefaultSEDisplayName[] = L"Team Competition";
CONST WCHAR wszDefaultSEDescription[] = L"Player Created Team Competition";
CONST WCHAR wszDefaultSEURL[]         = L"http://www.xbox.com";


CONST XONLINE_COMP_SINGLE_ELIMINATION_ATTRIBUTES SECreationStruct =
{
    0,                            // dwPrivateSlots
    0,                            // dwPublicSlots
    0x2,                          // dwMinimumPlayers
    0,                            // ftRegistrationOpen
    0,                            // ftRegistrationClose
    0,                            // ftCompetitionStart
    0,                            // ftRoundOneStart
    0,                            // ftRoundOneEnd
    0x60,                         // dwMatchReminderAdvanceMinutes
    XONLINE_COMP_INTERVAL_MINUTE, // Interval
    30,                           // UnitOrMask
    TRUE,                         // fTeamsCompetition
    0,                            // dwTeamSize
};

CONST XONLINE_ATTRIBUTE_SPEC CSECompetitionsAvailableCompetitionsQueryResults::ResultSpec[SE_COMPETITIONS_AVAILABLE_COMPETITIONS_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER,        sizeof(ULONGLONG) }, // entity_id
    { XONLINE_COMP_ATTR_COMP_START,        sizeof(ULONGLONG) }, // att_comp_start
    { XONLINE_COMP_ATTR_ROUND_FREQUENCY,   sizeof(ULONGLONG) }, // att_round_frequency
    { XONLINE_COMP_ATTR_ROUND_INTERVAL,    sizeof(ULONGLONG) }, // att_round_interval
    { XONLINE_COMP_ATTR_ROUND_DAY_MASK,    sizeof(ULONGLONG) }, // att_round_day_mask
    { XONLINE_COMP_ATTR_ROUND_ONE_START,   sizeof(ULONGLONG) }, // att_round_one_start
    { XONLINE_COMP_ATTR_ROUND_ONE_END,     sizeof(ULONGLONG) }, // att_round_one_end
    { XONLINE_COMP_ATTR_IS_TEAM_COMP,      sizeof(ULONGLONG) }, // att_is_team_comp
    { XONLINE_COMP_ATTR_TEAM_SIZE,         sizeof(ULONGLONG) }, // att_team_size
    { XONLINE_COMP_ATTR_MAX_PUBLIC_SLOTS,  sizeof(ULONGLONG) }, // att_max_public_slots
    { XONLINE_COMP_ATTR_MAX_PRIVATE_SLOTS, sizeof(ULONGLONG) }, // att_max_private_slots
    { XONLINE_COMP_ATTR_PUBLIC_ENTRANTS,   sizeof(ULONGLONG) }, // att_public_entrants
    { XONLINE_COMP_ATTR_PRIVATE_ENTRANTS,  sizeof(ULONGLONG) }, // att_private_entrants
    { XONLINE_COMP_ATTR_STATUS,            sizeof(ULONGLONG) }, // att_status
    { 0x00010001,                          sizeof(ULONGLONG) }, // att_map
    { SE_COMPETITIONS_ATT_NAME,            ATT_COMP_NAME_SIZE }, // att_name
    { 0x00210003,                          400 },                // att_icon
};

CONST XONLINE_ATTRIBUTE_SPEC CSECompetitionsCompetitionsICreatedQueryResults::ResultSpec[SE_COMPETITIONS_COMPETITIONS_I_CREATED_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER,        sizeof(ULONGLONG) }, // entity_id
    { XONLINE_COMP_ATTR_COMP_START,        sizeof(ULONGLONG) }, // att_comp_start
    { XONLINE_COMP_ATTR_ROUND_FREQUENCY,   sizeof(ULONGLONG) }, // att_round_frequency
    { XONLINE_COMP_ATTR_ROUND_INTERVAL,    sizeof(ULONGLONG) }, // att_round_interval
    { XONLINE_COMP_ATTR_ROUND_DAY_MASK,    sizeof(ULONGLONG) }, // att_round_day_mask
    { XONLINE_COMP_ATTR_ROUND_ONE_START,   sizeof(ULONGLONG) }, // att_round_one_start
    { XONLINE_COMP_ATTR_ROUND_ONE_END,     sizeof(ULONGLONG) }, // att_round_one_end
    { XONLINE_COMP_ATTR_IS_TEAM_COMP,      sizeof(ULONGLONG) }, // att_is_team_comp
    { XONLINE_COMP_ATTR_TEAM_SIZE,         sizeof(ULONGLONG) }, // att_team_size
    { XONLINE_COMP_ATTR_MAX_PUBLIC_SLOTS,  sizeof(ULONGLONG) }, // att_max_public_slots
    { XONLINE_COMP_ATTR_MAX_PRIVATE_SLOTS, sizeof(ULONGLONG) }, // att_max_private_slots
    { XONLINE_COMP_ATTR_PUBLIC_ENTRANTS,   sizeof(ULONGLONG) }, // att_public_entrants
    { XONLINE_COMP_ATTR_PRIVATE_ENTRANTS,  sizeof(ULONGLONG) }, // att_private_entrants
    { XONLINE_COMP_ATTR_STATUS,            sizeof(ULONGLONG) }, // att_status
    { 0x00010001,                          sizeof(ULONGLONG) }, // att_map
    { SE_COMPETITIONS_ATT_NAME,            ATT_COMP_NAME_SIZE }, // att_name
    { 0x00210003,                          400 },               // att_icon
};

CONST XONLINE_ATTRIBUTE_SPEC CSECompetitionsCompetitionDetailsQueryResults::ResultSpec[SE_COMPETITIONS_COMPETITION_DETAILS_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER,            sizeof(ULONGLONG) }, // entity_id
    { XONLINE_QUERY_OWNER_PUID,                sizeof(ULONGLONG) }, // owner_id
    { 0x81100001,                              16 },                // owner_gamertag
    { XONLINE_COMP_ATTR_COMP_START,            sizeof(ULONGLONG) }, // att_comp_start
    { XONLINE_COMP_ATTR_COMP_CLEANUP,          sizeof(ULONGLONG) }, // att_comp_cleanup
    { XONLINE_COMP_ATTR_ROUND_FREQUENCY,       sizeof(ULONGLONG) }, // att_round_frequency
    { XONLINE_COMP_ATTR_ROUND_INTERVAL,        sizeof(ULONGLONG) }, // att_round_interval
    { XONLINE_COMP_ATTR_ROUND_DAY_MASK,        sizeof(ULONGLONG) }, // att_round_day_mask
    { XONLINE_COMP_ATTR_IS_TEAM_COMP,          sizeof(ULONGLONG) }, // att_is_team_comp
    { XONLINE_COMP_ATTR_TEAM_SIZE,             sizeof(ULONGLONG) }, // att_team_size
    { XONLINE_COMP_ATTR_REMINDER_MIN,          sizeof(ULONGLONG) }, // att_reminder_min
    { XONLINE_COMP_ATTR_ROUNDS,                sizeof(ULONGLONG) }, // att_rounds
    { XONLINE_COMP_ATTR_CURRENT_ROUND,         sizeof(ULONGLONG) }, // att_current_round
    { XONLINE_COMP_ATTR_CURRENT_ROUND_START,   sizeof(ULONGLONG) }, // att_current_round_start
    { XONLINE_COMP_ATTR_CURRENT_ROUND_END,     sizeof(ULONGLONG) }, // att_current_round_end
    { XONLINE_COMP_ATTR_PUBLIC_ENTRANTS,       sizeof(ULONGLONG) }, // att_public_entrants
    { XONLINE_COMP_ATTR_PRIVATE_ENTRANTS,      sizeof(ULONGLONG) }, // att_private_entrants
    { XONLINE_COMP_ATTR_STATUS,                sizeof(ULONGLONG) }, // att_status
    { XONLINE_COMP_ATTR_ROUND0_LEADERBOARD_ID, sizeof(ULONGLONG) }, // att_leaderboard_id0
    { 0x80010021,                              sizeof(ULONGLONG) }, // att_leaderboard_id1
    { 0x80010022,                              sizeof(ULONGLONG) }, // att_leaderboard_id2
    { 0x00010001,                              sizeof(ULONGLONG) }, // att_map
    { SE_COMPETITIONS_ATT_NAME,                ATT_COMP_NAME_SIZE }, // att_name
    { 0x00210003,                              400 },               // att_icon
};

CONST XONLINE_ATTRIBUTE_SPEC CSEEntrantsMyCompetitionsQueryResults::ResultSpec[SE_ENTRANTS_MY_COMPETITIONS_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER, sizeof(ULONGLONG) }, // entity_id
    { 0x80010000, sizeof(ULONGLONG) },  // att_comp_id
    { 0x8001001d, sizeof(ULONGLONG) },  // att_comp_status
    { 0x80020001, sizeof(ULONGLONG) },  // att_status
    { 0x80020003, sizeof(ULONGLONG) },  // att_current_round
    { 0x80020007, sizeof(ULONGLONG) },  // att_current_event
    { 0x80020008, sizeof(ULONGLONG) },  // att_current_start
    { 0x80020009, sizeof(ULONGLONG) },  // att_sort
    { ATT_ENTRANTS_COMP_NAME_ID, ATT_COMP_NAME_SIZE }, // att_name
};

CONST XONLINE_ATTRIBUTE_SPEC CSEEntrantsCompetitionStandingsQueryResults::ResultSpec[SE_ENTRANTS_COMPETITION_STANDINGS_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER, sizeof(ULONGLONG) }, // entity_id
    { 0x80020000, sizeof(ULONGLONG) }, // att_puid
    { 0x81120000,  16 },               // gamertag
    { 0x80020001, sizeof(ULONGLONG) }, // att_status
    { 0x80020003, sizeof(ULONGLONG) }, // att_current_round
    { 0x80020007, sizeof(ULONGLONG) }, // att_current_event
    { 0x80020008, sizeof(ULONGLONG) }, // att_current_start
    { 0x80020009, sizeof(ULONGLONG) }, // att_sort
};

CONST XONLINE_ATTRIBUTE_SPEC CSEEntrantsCurrentEntrantsQueryResults::ResultSpec[SE_ENTRANTS_CURRENT_ENTRANTS_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER, sizeof(ULONGLONG) }, // entity_id
    { 0x80020000, sizeof(ULONGLONG) }, // att_puid
    { 0x81120000,  16 }, // gamertag
    { 0x80020001, sizeof(ULONGLONG) }, // att_status
    { 0x80020009, sizeof(ULONGLONG) }, // att_sort
};

CONST XONLINE_ATTRIBUTE_SPEC CSEEventsTopologyQueryResults::ResultSpec[SE_EVENTS_TOPOLOGY_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER, sizeof(ULONGLONG) }, // entity_id
    { 0x80030001, sizeof(ULONGLONG) }, // topology_id
    { 0x80030002, sizeof(ULONGLONG) }, // round
    { 0x80030003, sizeof(ULONGLONG) }, // start
    { 0x80030006, sizeof(ULONGLONG) }, // next_entity
    { 0x80030007, sizeof(ULONGLONG) }, // next_start
    { 0x80030008, sizeof(ULONGLONG) }, // player1
    { 0x81130008,  16 }, // p1_gamertag
    { 0x8003000b, sizeof(ULONGLONG) }, // player2
    { 0x8113000b,  16 }, // p2_gamertag
    { 0x8003000e, sizeof(ULONGLONG) }, // winner
    { 0x8003000f, sizeof(ULONGLONG) }, // loser
    { 0x00030001, sizeof(ULONGLONG) }, // att_map
    { 0x00130002,  200 }, // att_name
    { 0x00230003,  400 }, // att_icon
};

