//------------------------------------------------------------------------------
//
// Xbox Competitions Definitions
// Generated by XLAST Competitions Version 1.00.5849.4 at Mon, Nov 29, 2004 11:28
// Title ID: ffedaaab
// Project Name: comps
//------------------------------------------------------------------------------
#pragma once


#include <xtl.h>
#include <xonline.h>
#include <assert.h>






// Helper class for getting/setting blob attributes
#ifndef _XDKTOOL_BLOB
#define _XDKTOOL_BLOB
class CBlob
{
public:
    CBlob() : m_wLength( 0 ), m_pvData( NULL ) {}
    CBlob( WORD wLength, const PVOID pvData ) : m_wLength( wLength), m_pvData( pvData) {}
    CBlob( const CBlob & b ) { *this = b; }
    CBlob & operator=( const CBlob & b )
    { m_wLength = b.Length; m_pvData = b.Data; return *this; }
    BOOL operator==( const CBlob & b ) const
    { return m_wLength == b.Length && memcmp( m_pvData, b.Data, b.Length ) == 0; }
    BOOL IsNull() { return m_pvData == NULL; }
    __declspec( property( put = SetData, get=GetData ) ) const PVOID Data;
    const PVOID GetData() const { return m_pvData; }
    VOID SetData( const PVOID pvData ) { m_pvData = pvData; }
    __declspec( property( put = SetLength, get=GetLength ) ) WORD Length;
    WORD GetLength() const { return m_wLength; }
    VOID SetLength( WORD wLength ) { m_wLength = wLength; }
private:
    WORD m_wLength;
    PVOID m_pvData;
};

// A null blob is defined as having a NULL pointer
#define NULL_BLOB CBlob( 0, NULL )

// Macro for declaring "blob literals" (much like the _T() macro does for strings)
#define B( length, ptr ) CBlob( length, (const PVOID) ptr )
#endif


//----------------------------------------------------------------------------
// ICompetitionQuery is an interface exposed by all queries below.
// This allows you to use inheritance to organize your competition query code
// without going bonkers
//----------------------------------------------------------------------------
#pragma push_macro("INTERFACE")
#undef INTERFACE
#define INTERFACE ICompetitionQuery

DECLARE_INTERFACE(ICompetitionQuery)
{
    STDMETHOD(Process)(THIS)            PURE;
    STDMETHOD(StopTask)(THIS)           PURE;
    STDMETHOD_(VOID, Clear)(THIS)       PURE;
    STDMETHOD_(BOOL, IsDone)(THIS)      CONST PURE;
    STDMETHOD_(BOOL, IsRunning)(THIS)   CONST PURE;
};

#pragma pop_macro("INTERFACE")





//------------------------------------------------------------------------------
// Structures, classes, etc. for the SE competition type
//------------------------------------------------------------------------------
#define SE_COMPETITIONS_ID 0X00000001
#define SE_ENTRANTS_ID 0X00000002
#define SE_EVENTS_ID 0X00000003
#define SE_ID SE_COMPETITIONS_ID
#define SE_COMPETITIONS_ATT_MAP 0X00010001
#define SE_COMPETITIONS_ATT_NAME 0X00110002
#define SE_COMPETITIONS_ATT_ICON 0X00210003
#define SE_COMPETITIONS_ATTRIBUTE_COUNT 0X00000003
#define SE_COMPETITIONS_C_STATUS_PRE_INIT 0X04010000
#define SE_COMPETITIONS_C_STATUS_ACTIVE 0X04010001
#define SE_COMPETITIONS_C_STATUS_COMPLETE 0X04010002
#define SE_COMPETITIONS_C_STATUS_CANCELLED 0X0401000F
#define SE_ENTRANTS_C_STATUS_PRE_INIT 0X04010000
#define SE_ENTRANTS_C_STATUS_ACTIVE 0X04010001
#define SE_ENTRANTS_C_STATUS_COMPLETE 0X04010002
#define SE_ENTRANTS_C_STATUS_CANCELLED 0X0401000F
#define SE_ENTRANTS_C_STATUS_ENTRANT_REGISTERED 0X04020000
#define SE_ENTRANTS_C_STATUS_ENTRANT_PLAYING 0X04020001
#define SE_ENTRANTS_C_STATUS_ENTRANT_FORFEIT 0X04020002
#define SE_ENTRANTS_C_STATUS_ENTRANT_EJECTED 0X04020003
#define SE_ENTRANTS_C_STATUS_ENTRANT_ELIMINATED 0X0402000F
#define SE_EVENTS_ATT_MAP 0X00030001
#define SE_EVENTS_ATT_NAME 0X00130002
#define SE_EVENTS_ATT_ICON 0X00230003
#define SE_EVENTS_ATTRIBUTE_COUNT 0X00000003


extern CONST WCHAR wszDefaultSEDisplayName[];
extern CONST WCHAR wszDefaultSEDescription[];
extern CONST WCHAR wszDefaultSEURL[];

const DWORD ATT_COMP_NAME_SIZE        = 200;
const DWORD ATT_ENTRANTS_COMP_NAME_ID = 0x8011000E;

//------------------------------------------------------------------------------
// This creation struct is created from your configuration settings for this
// competition type.  However, it is not complete.  Certain members must be
// filled in at runtime before being used to create a competition.  See
// the Create functions below for more information
//------------------------------------------------------------------------------
extern CONST XONLINE_COMP_SINGLE_ELIMINATION_ATTRIBUTES SECreationStruct;


//------------------------------------------------------------------------------
// This class can be thought of to represent one competition.  You can declare
// an instance of this class, call Create, pump the task handle (by calling Process)
// and the class automatically records the competition ID.  From there you can do
// other competitions related tasks (such as Cancel, ManageEntrant, SubmitResults).
// You can also set the competition ID manually and perform said operations
//-------------------------------------------------------------------------------
class CSECompetition
{
public:
    CSECompetition(ULONGLONG qwCompetitionID = 0)
    {
        ZeroMemory(&m_CreateResults, sizeof(m_CreateResults));
        m_hTask = NULL;
        m_Status = STATUS_IDLE;
        m_CreateResults.qwCompetitionID = qwCompetitionID;
    }

    ~CSECompetition()
    {
        StopTask();
    }

private:
    // Private copy constructor and assignment operator so that you can't do these things
    CSECompetition(CONST CSECompetition&);
    CSECompetition& operator=(CONST CSECompetition&);
public:

    operator CONST XONLINETASK_HANDLE() CONST { return m_hTask; }

    HRESULT StopTask()
    {
        HRESULT hr = S_FALSE;
        if(m_hTask)
        {
            hr = XOnlineTaskClose(m_hTask);
            m_hTask = NULL;
            m_Status = STATUS_IDLE;
        }
        return hr;
    }

    //------------------------------------------------------------------------------
    // The following two functions allow you to create a competition.  The first
    // function uses the default creation struct (defined above) as a basis, setting
    // the runtime-specified values with the arguments you supply.  The second
    // function allows you to supply a creation structure of your own.  The second
    // is more useful in the case you allow the end-user to specify parameters for
    // the competition.
    //------------------------------------------------------------------------------

    HRESULT Create(
        DWORD    dwUserIndex,
        DWORD    dwPrivateSlots,
        DWORD    dwPublicSlots,
        FILETIME ftRegistrationOpen,
        FILETIME ftRegistrationClose,
        FILETIME ftCompetitionStart,
        FILETIME ftRoundOneStart,
        FILETIME ftRoundOneEnd,
        LPWSTR   pwszDisplayName,
        LPWSTR   pwszDescription,
        LPWSTR   pwszURL,
        DWORD    dwTeamSize,
        ULONGLONG qwTeamID,
        ULONGLONG att_map,
        LPWSTR   att_name,
        CBlob&   att_icon)
    {
        XONLINE_COMP_SINGLE_ELIMINATION_ATTRIBUTES StandardAttrs;

        CopyMemory(&StandardAttrs, &SECreationStruct, sizeof(XONLINE_COMP_SINGLE_ELIMINATION_ATTRIBUTES));

        StandardAttrs.dwPrivateSlots = dwPrivateSlots;
        StandardAttrs.dwPublicSlots = dwPublicSlots;
        StandardAttrs.ftRegistrationOpen = ftRegistrationOpen;
        StandardAttrs.ftRegistrationClose = ftRegistrationClose;
        StandardAttrs.ftRoundOneStart = ftRoundOneStart;
        StandardAttrs.ftRoundOneEnd = ftRoundOneEnd;
        StandardAttrs.dwTeamSize = dwTeamSize;
        return Create(dwUserIndex, &StandardAttrs, pwszDisplayName, pwszDescription, pwszURL, qwTeamID, att_map, att_name, att_icon);
    }

    HRESULT Create(
        DWORD    dwUserIndex,
        CONST XONLINE_COMP_SINGLE_ELIMINATION_ATTRIBUTES* pDefaultAttributes,
        LPWSTR   pwszDisplayName,
        LPWSTR   pwszDescription,
        LPWSTR   pwszURL,
        ULONGLONG qwTeamID,
        ULONGLONG att_map,
        LPWSTR   att_name,
        CBlob&   att_icon)
    {
        DWORD dwAttrCount = 0;
        XONLINE_ATTRIBUTE CustomAttrs[SE_COMPETITIONS_ATTRIBUTE_COUNT + 3];
        ZeroMemory(CustomAttrs, sizeof(CustomAttrs));

        if(pwszDisplayName)
        {
            CustomAttrs[dwAttrCount].dwAttributeID = 0x8011000E;
            CustomAttrs[dwAttrCount++].info.string.lpValue = pwszDisplayName;
        }

        if(pwszDescription)
        {
            CustomAttrs[dwAttrCount].dwAttributeID = 0x8011001E;
            CustomAttrs[dwAttrCount++].info.string.lpValue = pwszDescription;
        }

        if(pwszURL)
        {
            CustomAttrs[dwAttrCount].dwAttributeID = 0x8011001F;
            CustomAttrs[dwAttrCount++].info.string.lpValue = pwszURL;
        }

        CustomAttrs[dwAttrCount].dwAttributeID = SE_COMPETITIONS_ATT_MAP;
        CustomAttrs[dwAttrCount++].info.integer.qwValue = att_map;

        CustomAttrs[dwAttrCount].dwAttributeID = SE_COMPETITIONS_ATT_NAME;
        CustomAttrs[dwAttrCount++].info.string.lpValue = att_name;

        CustomAttrs[dwAttrCount].dwAttributeID = SE_COMPETITIONS_ATT_ICON;
        CustomAttrs[dwAttrCount].info.blob.pvValue = (PVOID)att_icon.GetData();
        CustomAttrs[dwAttrCount++].info.blob.dwLength = att_icon.GetLength();

        HRESULT hr = XOnlineCompetitionCreateSingleElimination(
            dwUserIndex, SE_ID, qwTeamID,
            pDefaultAttributes, dwAttrCount, CustomAttrs, NULL, &m_hTask);
        if(SUCCEEDED(hr)) { m_Status = STATUS_CREATE; }
        return hr;
    }


    HRESULT Cancel(
        DWORD   dwUserIndex,
        ULONGLONG qwTeamID)
    {
        HRESULT hr = XOnlineCompetitionCancel(dwUserIndex, SE_ID, qwTeamID, m_CreateResults.qwCompetitionID, NULL, &m_hTask);
        if(SUCCEEDED(hr)) { m_Status = STATUS_CANCEL; }
        return hr;
    }

    HRESULT Checkin(
        DWORD   dwUserIndex,
        ULONGLONG qwTeamID,
        ULONGLONG qwEventID)
    {
        HRESULT hr = XOnlineCompetitionCheckin(dwUserIndex, SE_ID, qwTeamID, m_CreateResults.qwCompetitionID, qwEventID, NULL, &m_hTask);
        if(SUCCEEDED(hr)) { m_Status = STATUS_CHECKIN; }
        return hr;
    }

    HRESULT ManageEntrant(
        DWORD   dwAction,
        DWORD   dwUserIndex,
        ULONGLONG qwTeamID,
        DWORD   dwNumAttributes,
        CONST XONLINE_ATTRIBUTE *pAttributes)
    {
        HRESULT hr = XOnlineCompetitionManageEntrant(dwAction, dwUserIndex, SE_ID, qwTeamID, m_CreateResults.qwCompetitionID, dwNumAttributes, pAttributes, NULL, &m_hTask);
        if(SUCCEEDED(hr)) { m_Status = STATUS_MANAGE_ENTRANT; }
        return hr;
    }

    HRESULT SessionRegister(
        CONST XONLINE_ARB_ID *pArbitrationID,
        WORD wMaxRoundSeconds,
        DWORD dwArbitrationRegisterFlags)
    {
        HRESULT hr = XOnlineCompetitionSessionRegister(pArbitrationID, wMaxRoundSeconds, dwArbitrationRegisterFlags, NULL, &m_hTask);
        if(SUCCEEDED(hr)) { m_Status = STATUS_SESSION_REGISTER; }
        return hr;
    }

    HRESULT SessionRegisterGetResults(
        DWORD dwRegistrantsBufferCount,
        XONLINE_ARB_REGISTRANT *pRegistrants,
        DWORD *pdwNumRegistrants)
    {
        HRESULT hr = XOnlineCompetitionSessionRegisterGetResults(m_hTask, dwRegistrantsBufferCount, pRegistrants, pdwNumRegistrants);
        StopTask();
        return hr;
    }

    HRESULT SubmitResults(
        CONST XONLINE_ARB_ID *pArbitrationID,
        DWORD dwArbitrationReportFlags,
        CONST XONLINE_ARB_REPORT_DATA *pArbitrationReportData,
        DWORD dwNumStatProcs,
        CONST XONLINE_STAT_PROC *pStatProcs,
        DWORD dwNumAdditionalAttributes,
        CONST XONLINE_ATTRIBUTE *pAdditionalAttributes)
    {
        HRESULT hr = XOnlineCompetitionSubmitResults(SE_ID, m_CreateResults.qwCompetitionID,
            pArbitrationID, dwArbitrationReportFlags, pArbitrationReportData, dwNumStatProcs, pStatProcs,
            dwNumAdditionalAttributes, pAdditionalAttributes, NULL, &m_hTask);
        if(SUCCEEDED(hr)) { m_Status = STATUS_SUBMIT_RESULTS; }
        return hr;
    }

    //--------------------------------------------------------------------------
    // Once you have created a task handle with one of the other functions,
    // call this function approximately once per frame to pump the task handle.
    // The returned HRESULT is the result of XOnlineTaskContinue.  However, in
    // the case that the task to create a competition has completed
    // successfully, the returned value is the return value of
    // XOnlineCompCreateGetResults()
    //--------------------------------------------------------------------------
    HRESULT Process()
    {
        HRESULT hr = S_FALSE;

        if(m_Status == STATUS_IDLE)
        {
            return hr;
        }

        //
        // Continue the task
        //

        hr = XOnlineTaskContinue(m_hTask);
        if(FAILED(hr))
        {
            StopTask();
            return hr;
        }

        if(hr == XONLINETASK_S_RUNNING)
        {
            return hr;
        }

        assert(hr == XONLINETASK_S_SUCCESS || hr == XONLINETASK_S_RESULTS_AVAIL || hr == XONLINETASK_S_RUNNING_IDLE);

        switch(m_Status)
        {
        case STATUS_IDLE:
            // This never happens
            break;

        case STATUS_CREATE:
            // Get the creation results
            hr = XOnlineCompetitionCreateGetResults(m_hTask, &m_CreateResults);
            if(FAILED(hr)) { break; }

            // Falls through

        // Now stop the task since it is completed
        case STATUS_CANCEL:
        case STATUS_CHECKIN:
        case STATUS_MANAGE_ENTRANT:
        case STATUS_SUBMIT_RESULTS:
            StopTask();
            break;

        case STATUS_SESSION_REGISTER:
            // We have to be able to call SessionRegisterGetResults
            // Hence, we can't stop the task here - it will be stopped
            // when SessionRegisterGetResults is called.
            break;
        }

        return hr;
    }

public:
    enum
    {
        STATUS_IDLE = 0,
        STATUS_CREATE = 1,
        STATUS_CANCEL = 2,
        STATUS_CHECKIN = 3,
        STATUS_MANAGE_ENTRANT = 4,
        STATUS_SUBMIT_RESULTS = 5,
        STATUS_SESSION_REGISTER = 6
    } m_Status;

    XONLINE_COMP_CREATE_RESULTS m_CreateResults;
    XONLINETASK_HANDLE m_hTask;
};




//
// CSECompetitionsAvailableCompetitionsQueryResult represents a single return result from the
// SECompetitionsAvailableCompetitionsQuery query
//
#pragma pack(push, 1)
class CSECompetitionsAvailableCompetitionsQueryResult
{
public:
    ULONGLONG bi_entity_id;
    ULONGLONG att_comp_start;
    ULONGLONG att_round_frequency;
    ULONGLONG att_round_interval;
    ULONGLONG att_round_day_mask;
    ULONGLONG att_round_one_start;
    ULONGLONG att_round_one_end;
    ULONGLONG att_is_team_comp;
    ULONGLONG att_team_size;
    ULONGLONG att_max_public_slots;
    ULONGLONG att_max_private_slots;
    ULONGLONG att_public_entrants;
    ULONGLONG att_private_entrants;
    ULONGLONG att_status;
    ULONGLONG att_map;
    WCHAR     att_name[ATT_COMP_NAME_SIZE];
    __declspec( property( get=Getatt_icon ) ) CBlob att_icon;
    CBlob Getatt_icon() { return CBlob( blobatt_iconLength, blobatt_icon ); }
private:
    WORD      blobatt_iconLength;
    BYTE      blobatt_icon[400];
public:
};
#pragma pack(pop)

#define SE_COMPETITIONS_AVAILABLE_COMPETITIONS_NUM_RESULT_ATTRS (16 + 1) // bi_entity_id + custom return values


//  Collection of results for the SECompetitionsAvailableCompetitions query
class CSECompetitionsAvailableCompetitionsQueryResults
{
public:
    CSECompetitionsAvailableCompetitionsQueryResults() { m_dwSize = 0; }

    // This function returns the number of valid
    // elements in the Results vector
    DWORD GetSize() { return m_dwSize; }
    CSECompetitionsAvailableCompetitionsQueryResult &operator[]( DWORD i ) { return v[i]; }

    void Clear() { m_dwSize = 0; }
    void Remove( DWORD i )
    {
        assert( i < m_dwSize );
        if( i < m_dwSize )
        {
            m_dwSize--;
            memcpy( &v[i], &v[i+1], sizeof( v[0] ) * ( m_dwSize - i ) );
        }
    }
    void SetSize( DWORD dwSize ) { m_dwSize = dwSize; }
    friend class CSECompetitionsAvailableCompetitionsQuery;
    CSECompetitionsAvailableCompetitionsQueryResult v[25];
    DWORD m_dwSize;
    static CONST XONLINE_ATTRIBUTE_SPEC ResultSpec[SE_COMPETITIONS_AVAILABLE_COMPETITIONS_NUM_RESULT_ATTRS];
};

#define SE_COMPETITIONS_AVAILABLE_COMPETITIONS_ID 0x1
#define SE_COMPETITIONS_AVAILABLE_COMPETITIONS_P_CURRENT_TIME 0x82000003



//
// Query object for SECompetitionsAvailableCompetitions query (id 0x1)
//
class CSECompetitionsAvailableCompetitionsQuery : public ICompetitionQuery
{
public:
    CSECompetitionsAvailableCompetitionsQuery()
    {
        m_State = STATE_IDLE;
        m_hTask = NULL;
        dwTotalItemsInResult = 0;
        dwItemsReturned = 0;
    }
    ~CSECompetitionsAvailableCompetitionsQuery()
    {
        StopTask();
    }
    CSECompetitionsAvailableCompetitionsQueryResults Results;
    DWORD dwTotalItemsInResult;
    DWORD dwItemsReturned;

    //--------------------------------------------------------------------------
    // After you've called Query to start a query, call this function about
    // once per frame to pump the task handle.  The HRESULT returned by this
    // function is the return value of XOnlineTaskContinue.  If the task has
    // completed successfully, the returned HRESULT is the return value of the
    // "GetResults" function for this type of query.  If no "GetResults"
    // function exists, the return value is that of XOnlineTaskContinue
    // You can test if a query is finished by testing that the returned HR is
    // not XONLINETASK_S_RUNNING.  In this case, it has either failed or
    // completed successfully.  If it has completed successfully, the results
    // of the query (if requested and if any exist) will be in the
    // dwTotalItemsInResult, dwItemsReturned, and Results members
    //--------------------------------------------------------------------------
    STDMETHOD(Process)()
    {
        HRESULT hr = S_FALSE;

        if(m_State == STATE_IDLE)
        {
            return hr;
        }

        //
        // Continue the task.  If it's completed
        // mark us done and close the task
        //

        switch(m_State)
        {
        case STATE_IDLE:
            // This never happens
            break;

        case STATE_RUNNING:
            hr = XOnlineTaskContinue(m_hTask);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // Is the task still running?
            if(hr == XONLINETASK_S_RUNNING)
            {
                break;
            }

            // The task is completed - get the results
            Results.SetSize(sizeof(Results.v));
            hr = XOnlineCompetitionSearchGetResults(m_hTask, &dwTotalItemsInResult, &dwItemsReturned, &Results.m_dwSize, (PBYTE)Results.v);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // On output, Results.m_dwSize is the number of bytes used, rather
            // than the number of elements that are valid
            Results.SetSize(dwItemsReturned);

            // Close the task and mark us done
            StopTask();
            m_State = STATE_DONE;
            break;
        case STATE_DONE:
            break;
        }

        return hr;
    }

    STDMETHOD(StopTask)()
    {
        HRESULT hr = S_FALSE;
        if(m_hTask)
        {
            hr = XOnlineTaskClose(m_hTask);
            m_hTask = NULL;
            m_State = STATE_IDLE;
        }
        return hr;
    }

    STDMETHOD_(VOID, Clear)()
    {
        Results.Clear();
    }

    //--------------------------------------------------------------------------
    // Call this function to start running a query.  You must specify all the
    // arguments listed (there are no optional arguments).
    //--------------------------------------------------------------------------
    STDMETHOD(Query)(
        ULONGLONG p_current_time,
        DWORD dwPage)
    {
        //
        // If any previous query is done, go ahead and
        // honor this request
        //

        if(m_State == STATE_DONE)
        {
            StopTask();
            m_State = STATE_IDLE;
        }

        //
        // If we're still not in the idle state
        // then a query is running, so fail
        //

        if(m_State != STATE_IDLE)
        {
            return E_FAIL;
        }

        //
        // Setup the parameters (if there are any)
        //
        XONLINE_ATTRIBUTE CustomAttrs[1];
        ZeroMemory(CustomAttrs, sizeof(CustomAttrs));

        CustomAttrs[0].dwAttributeID = SE_COMPETITIONS_AVAILABLE_COMPETITIONS_P_CURRENT_TIME;
        CustomAttrs[0].info.integer.qwValue = p_current_time;


        //
        // Run the query
        //

        HRESULT hr = XOnlineCompetitionSearch(SE_COMPETITIONS_AVAILABLE_COMPETITIONS_ID, SE_COMPETITIONS_ID, dwPage,
            sizeof(Results.v)/sizeof(Results.v[0]), sizeof(CustomAttrs)/sizeof(CustomAttrs[0]), CustomAttrs,
            sizeof(Results.ResultSpec)/sizeof(Results.ResultSpec[0]), Results.ResultSpec, NULL, &m_hTask);

        if(SUCCEEDED(hr)) { m_State = STATE_RUNNING; }
        return hr;
    }

    STDMETHOD_(BOOL, IsDone)()     const { return m_State == STATE_DONE; }
    STDMETHOD_(BOOL, IsRunning)()  const { return m_State == STATE_RUNNING; }
public:
    enum STATE
    {
        STATE_IDLE,
        STATE_RUNNING,
        STATE_DONE
    };

    STATE m_State;
    XONLINETASK_HANDLE m_hTask;
};




//
// CSECompetitionsCompetitionsICreatedQueryResult represents a single return result from the
// SECompetitionsCompetitionsICreatedQuery query
//
#pragma pack(push, 1)
class CSECompetitionsCompetitionsICreatedQueryResult
{
public:
    ULONGLONG bi_entity_id;
    ULONGLONG att_comp_start;
    ULONGLONG att_round_frequency;
    ULONGLONG att_round_interval;
    ULONGLONG att_round_day_mask;
    ULONGLONG att_round_one_start;
    ULONGLONG att_round_one_end;
    ULONGLONG att_is_team_comp;
    ULONGLONG att_team_size;
    ULONGLONG att_max_public_slots;
    ULONGLONG att_max_private_slots;
    ULONGLONG att_public_entrants;
    ULONGLONG att_private_entrants;
    ULONGLONG att_status;
    ULONGLONG att_map;
    WCHAR     att_name[ATT_COMP_NAME_SIZE];
    __declspec( property( get=Getatt_icon ) ) CBlob att_icon;
    CBlob Getatt_icon() { return CBlob( blobatt_iconLength, blobatt_icon ); }
private:
    WORD      blobatt_iconLength;
    BYTE      blobatt_icon[400];
public:
};
#pragma pack(pop)

#define SE_COMPETITIONS_COMPETITIONS_I_CREATED_NUM_RESULT_ATTRS (16 + 1) // bi_entity_id + custom return values


//  Collection of results for the SECompetitionsCompetitionsICreated query
class CSECompetitionsCompetitionsICreatedQueryResults
{
public:
    CSECompetitionsCompetitionsICreatedQueryResults() { m_dwSize = 0; }

    // This function returns the number of valid
    // elements in the Results vector
    DWORD GetSize() { return m_dwSize; }
    CSECompetitionsCompetitionsICreatedQueryResult &operator[]( DWORD i ) { return v[i]; }
private:
    void Clear() { m_dwSize = 0; }
    void Remove( DWORD i )
    {
        assert( i < m_dwSize );
        if( i < m_dwSize )
        {
            m_dwSize--;
            memcpy( &v[i], &v[i+1], sizeof( v[0] ) * ( m_dwSize - i ) );
        }
    }
    void SetSize( DWORD dwSize ) { m_dwSize = dwSize; }
    friend class CSECompetitionsCompetitionsICreatedQuery;
    CSECompetitionsCompetitionsICreatedQueryResult v[25];
    DWORD m_dwSize;
    static CONST XONLINE_ATTRIBUTE_SPEC ResultSpec[SE_COMPETITIONS_COMPETITIONS_I_CREATED_NUM_RESULT_ATTRS];
};

#define SE_COMPETITIONS_COMPETITIONS_I_CREATED_ID 0x2
#define SE_COMPETITIONS_COMPETITIONS_I_CREATED_P_OWNER_ID 0x82000001
#define SE_COMPETITIONS_COMPETITIONS_I_CREATED_P_STATUS 0x8201001d



//
// Query object for SECompetitionsCompetitionsICreated query (id 0x2)
//
class CSECompetitionsCompetitionsICreatedQuery : public ICompetitionQuery
{
public:
    CSECompetitionsCompetitionsICreatedQuery()
    {
        m_State = STATE_IDLE;
        m_hTask = NULL;
        dwTotalItemsInResult = 0;
        dwItemsReturned = 0;
    }
    ~CSECompetitionsCompetitionsICreatedQuery()
    {
        StopTask();
    }
    CSECompetitionsCompetitionsICreatedQueryResults Results;
    DWORD dwTotalItemsInResult;
    DWORD dwItemsReturned;

    //--------------------------------------------------------------------------
    // After you've called Query to start a query, call this function about
    // once per frame to pump the task handle.  The HRESULT returned by this
    // function is the return value of XOnlineTaskContinue.  If the task has
    // completed successfully, the returned HRESULT is the return value of the
    // "GetResults" function for this type of query.  If no "GetResults"
    // function exists, the return value is that of XOnlineTaskContinue
    // You can test if a query is finished by testing that the returned HR is
    // not XONLINETASK_S_RUNNING.  In this case, it has either failed or
    // completed successfully.  If it has completed successfully, the results
    // of the query (if requested and if any exist) will be in the
    // dwTotalItemsInResult, dwItemsReturned, and Results members
    //--------------------------------------------------------------------------
    STDMETHOD(Process)()
    {
        HRESULT hr = S_FALSE;

        if(m_State == STATE_IDLE)
        {
            return hr;
        }

        //
        // Continue the task.  If it's completed
        // mark us done and close the task
        //

        switch(m_State)
        {
        case STATE_IDLE:
            // This never happens
            break;

        case STATE_RUNNING:
            hr = XOnlineTaskContinue(m_hTask);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // Is the task still running?
            if(hr == XONLINETASK_S_RUNNING)
            {
                break;
            }

            // The task is completed - get the results
            Results.SetSize(sizeof(Results.v));
            hr = XOnlineCompetitionSearchGetResults(m_hTask, &dwTotalItemsInResult, &dwItemsReturned, &Results.m_dwSize, (PBYTE)Results.v);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // On output, Results.m_dwSize is the number of bytes used, rather
            // than the number of elements that are valid
            Results.SetSize(dwItemsReturned);

            // Close the task and mark us done
            StopTask();
            m_State = STATE_DONE;
            break;
        case STATE_DONE:
            break;
        }

        return hr;
    }

    STDMETHOD(StopTask)()
    {
        HRESULT hr = S_FALSE;
        if(m_hTask)
        {
            hr = XOnlineTaskClose(m_hTask);
            m_hTask = NULL;
            m_State = STATE_IDLE;
        }
        return hr;
    }

    STDMETHOD_(VOID, Clear)()
    {
        Results.Clear();
    }

    //--------------------------------------------------------------------------
    // Call this function to start running a query.  You must specify all the
    // arguments listed (there are no optional arguments).
    //--------------------------------------------------------------------------
    STDMETHOD(Query)(
        ULONGLONG p_owner_id,
        ULONGLONG p_status,
        DWORD dwPage)
    {
        //
        // If any previous query is done, go ahead and
        // honor this request
        //

        if(m_State == STATE_DONE)
        {
            StopTask();
            m_State = STATE_IDLE;
        }

        //
        // If we're still not in the idle state
        // then a query is running, so fail
        //

        if(m_State != STATE_IDLE)
        {
            return E_FAIL;
        }

        //
        // Setup the parameters (if there are any)
        //
        XONLINE_ATTRIBUTE CustomAttrs[2];
        ZeroMemory(CustomAttrs, sizeof(CustomAttrs));

        CustomAttrs[0].dwAttributeID = SE_COMPETITIONS_COMPETITIONS_I_CREATED_P_OWNER_ID;
        CustomAttrs[0].info.integer.qwValue = p_owner_id;

        CustomAttrs[1].dwAttributeID = SE_COMPETITIONS_COMPETITIONS_I_CREATED_P_STATUS;
        CustomAttrs[1].info.integer.qwValue = p_status;


        //
        // Run the query
        //

        HRESULT hr = XOnlineCompetitionSearch(SE_COMPETITIONS_COMPETITIONS_I_CREATED_ID, SE_COMPETITIONS_ID, dwPage,
            sizeof(Results.v)/sizeof(Results.v[0]), sizeof(CustomAttrs)/sizeof(CustomAttrs[0]), CustomAttrs,
            sizeof(Results.ResultSpec)/sizeof(Results.ResultSpec[0]), Results.ResultSpec, NULL, &m_hTask);

        if(SUCCEEDED(hr)) { m_State = STATE_RUNNING; }
        return hr;
    }

    STDMETHOD_(BOOL, IsDone)()     const { return m_State == STATE_DONE; }
    STDMETHOD_(BOOL, IsRunning)()  const { return m_State == STATE_RUNNING; }
public:
    enum STATE
    {
        STATE_IDLE,
        STATE_RUNNING,
        STATE_DONE
    };

    STATE m_State;
    XONLINETASK_HANDLE m_hTask;
};




//
// CSECompetitionsCompetitionDetailsQueryResult represents a single return result from the
// SECompetitionsCompetitionDetailsQuery query
//
#pragma pack(push, 1)
class CSECompetitionsCompetitionDetailsQueryResult
{
public:
    ULONGLONG bi_entity_id;
    ULONGLONG owner_id;
    WCHAR     owner_gamertag[16];
    ULONGLONG att_comp_start;
    ULONGLONG att_comp_cleanup;
    ULONGLONG att_round_frequency;
    ULONGLONG att_round_interval;
    ULONGLONG att_round_day_mask;
    ULONGLONG att_is_team_comp;
    ULONGLONG att_team_size;
    ULONGLONG att_reminder_min;
    ULONGLONG att_rounds;
    ULONGLONG att_current_round;
    ULONGLONG att_current_round_start;
    ULONGLONG att_current_round_end;
    ULONGLONG att_public_entrants;
    ULONGLONG att_private_entrants;
    ULONGLONG att_status;
    ULONGLONG att_leaderboard_id0;
    ULONGLONG att_leaderboard_id1;
    ULONGLONG att_leaderboard_id2;
    ULONGLONG att_map;
    WCHAR     att_name[ATT_COMP_NAME_SIZE];
    __declspec( property( get=Getatt_icon ) ) CBlob att_icon;
    CBlob Getatt_icon() { return CBlob( blobatt_iconLength, blobatt_icon ); }
private:
    WORD      blobatt_iconLength;
    BYTE      blobatt_icon[400];
public:
};
#pragma pack(pop)

#define SE_COMPETITIONS_COMPETITION_DETAILS_NUM_RESULT_ATTRS (23 + 1) // bi_entity_id + custom return values


//  Collection of results for the SECompetitionsCompetitionDetails query
class CSECompetitionsCompetitionDetailsQueryResults
{
public:
    CSECompetitionsCompetitionDetailsQueryResults() { m_dwSize = 0; }

    // This function returns the number of valid
    // elements in the Results vector
    DWORD GetSize() { return m_dwSize; }
    CSECompetitionsCompetitionDetailsQueryResult &operator[]( DWORD i ) { return v[i]; }
private:
    void Clear() { m_dwSize = 0; }
    void Remove( DWORD i )
    {
        assert( i < m_dwSize );
        if( i < m_dwSize )
        {
            m_dwSize--;
            memcpy( &v[i], &v[i+1], sizeof( v[0] ) * ( m_dwSize - i ) );
        }
    }
    void SetSize( DWORD dwSize ) { m_dwSize = dwSize; }
    friend class CSECompetitionsCompetitionDetailsQuery;
    CSECompetitionsCompetitionDetailsQueryResult v[25];
    DWORD m_dwSize;
    static CONST XONLINE_ATTRIBUTE_SPEC ResultSpec[SE_COMPETITIONS_COMPETITION_DETAILS_NUM_RESULT_ATTRS];
};

#define SE_COMPETITIONS_COMPETITION_DETAILS_ID 0x1



//
// Query object for SECompetitionsCompetitionDetails query (id 0x1)
//
class CSECompetitionsCompetitionDetailsQuery : public ICompetitionQuery
{
public:
    CSECompetitionsCompetitionDetailsQuery()
    {
        m_State = STATE_IDLE;
        m_hTask = NULL;
        dwTotalItemsInResult = 0;
        dwItemsReturned = 0;
    }
    ~CSECompetitionsCompetitionDetailsQuery()
    {
        StopTask();
    }
    CSECompetitionsCompetitionDetailsQueryResults Results;
    DWORD dwTotalItemsInResult;
    DWORD dwItemsReturned;

    //--------------------------------------------------------------------------
    // After you've called Query to start a query, call this function about
    // once per frame to pump the task handle.  The HRESULT returned by this
    // function is the return value of XOnlineTaskContinue.  If the task has
    // completed successfully, the returned HRESULT is the return value of the
    // "GetResults" function for this type of query.  If no "GetResults"
    // function exists, the return value is that of XOnlineTaskContinue
    // You can test if a query is finished by testing that the returned HR is
    // not XONLINETASK_S_RUNNING.  In this case, it has either failed or
    // completed successfully.  If it has completed successfully, the results
    // of the query (if requested and if any exist) will be in the
    // dwTotalItemsInResult, dwItemsReturned, and Results members
    //--------------------------------------------------------------------------
    STDMETHOD(Process)()
    {
        HRESULT hr = S_FALSE;

        if(m_State == STATE_IDLE)
        {
            return hr;
        }

        //
        // Continue the task.  If it's completed
        // mark us done and close the task
        //

        switch(m_State)
        {
        case STATE_IDLE:
            // This never happens
            break;

        case STATE_RUNNING:
            hr = XOnlineTaskContinue(m_hTask);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // Is the task still running?
            if(hr == XONLINETASK_S_RUNNING)
            {
                break;
            }

            // The task is completed - get the results
            Results.SetSize(sizeof(Results.v));
            hr = XOnlineQueryFindFromIdsGetResults(m_hTask, &dwTotalItemsInResult, (PBYTE)Results.v);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            dwItemsReturned = dwTotalItemsInResult;
            Results.SetSize(dwItemsReturned);


            // Close the task and mark us done
            StopTask();
            m_State = STATE_DONE;
            break;
        case STATE_DONE:
            break;
        }

        return hr;
    }

    STDMETHOD(StopTask)()
    {
        HRESULT hr = S_FALSE;
        if(m_hTask)
        {
            hr = XOnlineTaskClose(m_hTask);
            m_hTask = NULL;
            m_State = STATE_IDLE;
        }
        return hr;
    }

    STDMETHOD_(VOID, Clear)()
    {
        Results.Clear();
    }

    //--------------------------------------------------------------------------
    // Call this function to start running a query.  You must specify all the
    // arguments listed (there are no optional arguments).
    //--------------------------------------------------------------------------
    STDMETHOD(Query)(
        ULONGLONG qwEntityID /* competition, entrant, or event ID depending on target */)
    {
        //
        // If any previous query is done, go ahead and
        // honor this request
        //

        if(m_State == STATE_DONE)
        {
            StopTask();
            m_State = STATE_IDLE;
        }

        //
        // If we're still not in the idle state
        // then a query is running, so fail
        //

        if(m_State != STATE_IDLE)
        {
            return E_FAIL;
        }

        //
        // Setup the parameters (if there are any)
        //
        //
        // Run the query
        //

        HRESULT hr = XOnlineQueryFindFromIds(SE_COMPETITIONS_ID, 0x1, sizeof(Results.ResultSpec)/sizeof(Results.ResultSpec[0]),
            Results.ResultSpec, 1, &qwEntityID,
            NULL, &m_hTask);

        if(SUCCEEDED(hr)) { m_State = STATE_RUNNING; }
        return hr;
    }

    STDMETHOD_(BOOL, IsDone)()     const { return m_State == STATE_DONE; }
    STDMETHOD_(BOOL, IsRunning)()  const { return m_State == STATE_RUNNING; }
public:
    enum STATE
    {
        STATE_IDLE,
        STATE_RUNNING,
        STATE_DONE
    };

    STATE m_State;
    XONLINETASK_HANDLE m_hTask;
};
#define SE_COMPETITIONS_UPDATE_TITLE_ATTRIBUTES_ID 0x1
#define SE_COMPETITIONS_UPDATE_TITLE_ATTRIBUTES_P_MAP 0x2010001
#define SE_COMPETITIONS_UPDATE_TITLE_ATTRIBUTES_P_NAME 0x2110002
#define SE_COMPETITIONS_UPDATE_TITLE_ATTRIBUTES_P_ICON 0x2210003



//
// Query object for SECompetitionsUpdateTitleAttributes query (id 0x1)
//
class CSECompetitionsUpdateTitleAttributesQuery : public ICompetitionQuery
{
public:
    CSECompetitionsUpdateTitleAttributesQuery()
    {
        m_State = STATE_IDLE;
        m_hTask = NULL;
    }
    ~CSECompetitionsUpdateTitleAttributesQuery()
    {
        StopTask();
    }

    //--------------------------------------------------------------------------
    // After you've called Query to start a query, call this function about
    // once per frame to pump the task handle.  The HRESULT returned by this
    // function is the return value of XOnlineTaskContinue.  If the task has
    // completed successfully, the returned HRESULT is the return value of the
    // "GetResults" function for this type of query.  If no "GetResults"
    // function exists, the return value is that of XOnlineTaskContinue
    // You can test if a query is finished by testing that the returned HR is
    // not XONLINETASK_S_RUNNING.  In this case, it has either failed or
    // completed successfully.  If it has completed successfully, the results
    // of the query (if requested and if any exist) will be in the
    // dwTotalItemsInResult, dwItemsReturned, and Results members
    //--------------------------------------------------------------------------
    STDMETHOD(Process)()
    {
        HRESULT hr = S_FALSE;

        if(m_State == STATE_IDLE)
        {
            return hr;
        }

        //
        // Continue the task.  If it's completed
        // mark us done and close the task
        //

        switch(m_State)
        {
        case STATE_IDLE:
            // This never happens
            break;

        case STATE_RUNNING:
            hr = XOnlineTaskContinue(m_hTask);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // Is the task still running?
            if(hr == XONLINETASK_S_RUNNING)
            {
                break;
            }


            // Close the task and mark us done
            StopTask();
            m_State = STATE_DONE;
            break;
        case STATE_DONE:
            break;
        }

        return hr;
    }

    STDMETHOD(StopTask)()
    {
        HRESULT hr = S_FALSE;
        if(m_hTask)
        {
            hr = XOnlineTaskClose(m_hTask);
            m_hTask = NULL;
            m_State = STATE_IDLE;
        }
        return hr;
    }

    STDMETHOD_(VOID, Clear)()
    {
    }

    //--------------------------------------------------------------------------
    // Call this function to start running a query.  You must specify all the
    // arguments listed (there are no optional arguments).
    //--------------------------------------------------------------------------
    STDMETHOD(Query)(
        ULONGLONG p_map,
        LPWSTR    p_name,
        CBlob&    p_icon,
        DWORD dwUserIndex,
        ULONGLONG qwTeamID,
        XENTITY_ID entityId)
    {
        //
        // If any previous query is done, go ahead and
        // honor this request
        //

        if(m_State == STATE_DONE)
        {
            StopTask();
            m_State = STATE_IDLE;
        }

        //
        // If we're still not in the idle state
        // then a query is running, so fail
        //

        if(m_State != STATE_IDLE)
        {
            return E_FAIL;
        }

        //
        // Setup the parameters (if there are any)
        //
        XONLINE_ATTRIBUTE CustomAttrs[3];
        ZeroMemory(CustomAttrs, sizeof(CustomAttrs));

        CustomAttrs[0].dwAttributeID = SE_COMPETITIONS_UPDATE_TITLE_ATTRIBUTES_P_MAP;
        CustomAttrs[0].info.integer.qwValue = p_map;

        CustomAttrs[1].dwAttributeID = SE_COMPETITIONS_UPDATE_TITLE_ATTRIBUTES_P_NAME;
        CustomAttrs[1].info.string.lpValue = p_name;

        CustomAttrs[2].dwAttributeID = SE_COMPETITIONS_UPDATE_TITLE_ATTRIBUTES_P_ICON;
        CustomAttrs[2].info.blob.pvValue = (PVOID)p_icon.GetData();
        CustomAttrs[2].info.blob.dwLength = p_icon.GetLength();

        //
        // Run the query
        //

        HRESULT hr = XOnlineQueryUpdateId(dwUserIndex, qwTeamID, SE_COMPETITIONS_ID, 0x1, entityId,
            sizeof(CustomAttrs)/sizeof(CustomAttrs[0]), CustomAttrs,
            NULL, &m_hTask);

        if(SUCCEEDED(hr)) { m_State = STATE_RUNNING; }
        return hr;
    }

    STDMETHOD_(BOOL, IsDone)()     const { return m_State == STATE_DONE; }
    STDMETHOD_(BOOL, IsRunning)()  const { return m_State == STATE_RUNNING; }
public:
    enum STATE
    {
        STATE_IDLE,
        STATE_RUNNING,
        STATE_DONE
    };

    STATE m_State;
    XONLINETASK_HANDLE m_hTask;
};




//
// CSEEntrantsMyCompetitionsQueryResult represents a single return result from the
// SEEntrantsMyCompetitionsQuery query
//
#pragma pack(push, 1)
class CSEEntrantsMyCompetitionsQueryResult
{
public:
    ULONGLONG bi_entity_id;
    ULONGLONG att_comp_id;
    ULONGLONG att_comp_status;
    ULONGLONG att_status;
    ULONGLONG att_current_round;
    ULONGLONG att_current_event;
    ULONGLONG att_current_start;
    ULONGLONG att_sort;
    WCHAR     att_comp_name[ATT_COMP_NAME_SIZE];
};
#pragma pack(pop)

#define SE_ENTRANTS_MY_COMPETITIONS_NUM_RESULT_ATTRS (8 + 1) // bi_entity_id + custom return values


//  Collection of results for the SEEntrantsMyCompetitions query
class CSEEntrantsMyCompetitionsQueryResults
{
public:
    CSEEntrantsMyCompetitionsQueryResults() { m_dwSize = 0; }

    // This function returns the number of valid
    // elements in the Results vector
    DWORD GetSize() { return m_dwSize; }
    CSEEntrantsMyCompetitionsQueryResult &operator[]( DWORD i ) { return v[i]; }
private:
    void Clear() { m_dwSize = 0; }
    void Remove( DWORD i )
    {
        assert( i < m_dwSize );
        if( i < m_dwSize )
        {
            m_dwSize--;
            memcpy( &v[i], &v[i+1], sizeof( v[0] ) * ( m_dwSize - i ) );
        }
    }
    void SetSize( DWORD dwSize ) { m_dwSize = dwSize; }
    friend class CSEEntrantsMyCompetitionsQuery;
    CSEEntrantsMyCompetitionsQueryResult v[25];
    DWORD m_dwSize;
    static CONST XONLINE_ATTRIBUTE_SPEC ResultSpec[SE_ENTRANTS_MY_COMPETITIONS_NUM_RESULT_ATTRS];
};

#define SE_ENTRANTS_MY_COMPETITIONS_ID 0x1
#define SE_ENTRANTS_MY_COMPETITIONS_P_PUID 0x82020000
#define SE_ENTRANTS_MY_COMPETITIONS_P_COMP_STATUS 0x8201001d



//
// Query object for SEEntrantsMyCompetitions query (id 0x1)
//
class CSEEntrantsMyCompetitionsQuery : public ICompetitionQuery
{
public:
    CSEEntrantsMyCompetitionsQuery()
    {
        m_State = STATE_IDLE;
        m_hTask = NULL;
        dwTotalItemsInResult = 0;
        dwItemsReturned = 0;
    }
    ~CSEEntrantsMyCompetitionsQuery()
    {
        StopTask();
    }
    CSEEntrantsMyCompetitionsQueryResults Results;
    DWORD dwTotalItemsInResult;
    DWORD dwItemsReturned;

    //--------------------------------------------------------------------------
    // After you've called Query to start a query, call this function about
    // once per frame to pump the task handle.  The HRESULT returned by this
    // function is the return value of XOnlineTaskContinue.  If the task has
    // completed successfully, the returned HRESULT is the return value of the
    // "GetResults" function for this type of query.  If no "GetResults"
    // function exists, the return value is that of XOnlineTaskContinue
    // You can test if a query is finished by testing that the returned HR is
    // not XONLINETASK_S_RUNNING.  In this case, it has either failed or
    // completed successfully.  If it has completed successfully, the results
    // of the query (if requested and if any exist) will be in the
    // dwTotalItemsInResult, dwItemsReturned, and Results members
    //--------------------------------------------------------------------------
    STDMETHOD(Process)()
    {
        HRESULT hr = S_FALSE;

        if(m_State == STATE_IDLE)
        {
            return hr;
        }

        //
        // Continue the task.  If it's completed
        // mark us done and close the task
        //

        switch(m_State)
        {
        case STATE_IDLE:
            // This never happens
            break;

        case STATE_RUNNING:
            hr = XOnlineTaskContinue(m_hTask);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // Is the task still running?
            if(hr == XONLINETASK_S_RUNNING)
            {
                break;
            }

            // The task is completed - get the results
            Results.SetSize(sizeof(Results.v));
            hr = XOnlineCompetitionSearchGetResults(m_hTask, &dwTotalItemsInResult, &dwItemsReturned, &Results.m_dwSize, (PBYTE)Results.v);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // On output, Results.m_dwSize is the number of bytes used, rather
            // than the number of elements that are valid
            Results.SetSize(dwItemsReturned);

            // Close the task and mark us done
            StopTask();
            m_State = STATE_DONE;
            break;
        case STATE_DONE:
            break;
        }

        return hr;
    }

    STDMETHOD(StopTask)()
    {
        HRESULT hr = S_FALSE;
        if(m_hTask)
        {
            hr = XOnlineTaskClose(m_hTask);
            m_hTask = NULL;
            m_State = STATE_IDLE;
        }
        return hr;
    }

    STDMETHOD_(VOID, Clear)()
    {
        Results.Clear();
    }

    //--------------------------------------------------------------------------
    // Call this function to start running a query.  You must specify all the
    // arguments listed (there are no optional arguments).
    //--------------------------------------------------------------------------
    STDMETHOD(Query)(
        ULONGLONG p_puid,
        ULONGLONG p_comp_status,
        DWORD dwPage)
    {
        //
        // If any previous query is done, go ahead and
        // honor this request
        //

        if(m_State == STATE_DONE)
        {
            StopTask();
            m_State = STATE_IDLE;
        }

        //
        // If we're still not in the idle state
        // then a query is running, so fail
        //

        if(m_State != STATE_IDLE)
        {
            return E_FAIL;
        }

        //
        // Setup the parameters (if there are any)
        //
        XONLINE_ATTRIBUTE CustomAttrs[2];
        ZeroMemory(CustomAttrs, sizeof(CustomAttrs));

        CustomAttrs[0].dwAttributeID = SE_ENTRANTS_MY_COMPETITIONS_P_PUID;
        CustomAttrs[0].info.integer.qwValue = p_puid;

        CustomAttrs[1].dwAttributeID = SE_ENTRANTS_MY_COMPETITIONS_P_COMP_STATUS;
        CustomAttrs[1].info.integer.qwValue = p_comp_status;


        //
        // Run the query
        //

        HRESULT hr = XOnlineCompetitionSearch(
                        SE_ENTRANTS_MY_COMPETITIONS_ID,
                        SE_ENTRANTS_ID,
                        dwPage,
                        sizeof(Results.v)/sizeof(Results.v[0]),
                        sizeof(CustomAttrs)/sizeof(CustomAttrs[0]),
                        CustomAttrs,
                        sizeof(Results.ResultSpec)/sizeof(Results.ResultSpec[0]),
                        Results.ResultSpec,
                        NULL,
                        &m_hTask);

        if(SUCCEEDED(hr)) { m_State = STATE_RUNNING; }
        return hr;
    }

    STDMETHOD_(BOOL, IsDone)()     const { return m_State == STATE_DONE; }
    STDMETHOD_(BOOL, IsRunning)()  const { return m_State == STATE_RUNNING; }
public:
    enum STATE
    {
        STATE_IDLE,
        STATE_RUNNING,
        STATE_DONE
    };

    STATE m_State;
    XONLINETASK_HANDLE m_hTask;
};




//
// CSEEntrantsCompetitionStandingsQueryResult represents a single return result from the
// SEEntrantsCompetitionStandingsQuery query
//
#pragma pack(push, 1)
class CSEEntrantsCompetitionStandingsQueryResult
{
public:
    ULONGLONG bi_entity_id;
    ULONGLONG att_puid;
    WCHAR     gamertag[16];
    ULONGLONG att_status;
    ULONGLONG att_current_round;
    ULONGLONG att_current_event;
    ULONGLONG att_current_start;
    ULONGLONG att_sort;
};
#pragma pack(pop)

#define SE_ENTRANTS_COMPETITION_STANDINGS_NUM_RESULT_ATTRS (7 + 1) // bi_entity_id + custom return values


//  Collection of results for the SEEntrantsCompetitionStandings query
class CSEEntrantsCompetitionStandingsQueryResults
{
public:
    CSEEntrantsCompetitionStandingsQueryResults() { m_dwSize = 0; }

    // This function returns the number of valid
    // elements in the Results vector
    DWORD GetSize() { return m_dwSize; }
    CSEEntrantsCompetitionStandingsQueryResult &operator[]( DWORD i ) { return v[i]; }
private:
    void Clear() { m_dwSize = 0; }
    void Remove( DWORD i )
    {
        assert( i < m_dwSize );
        if( i < m_dwSize )
        {
            m_dwSize--;
            memcpy( &v[i], &v[i+1], sizeof( v[0] ) * ( m_dwSize - i ) );
        }
    }
    void SetSize( DWORD dwSize ) { m_dwSize = dwSize; }
    friend class CSEEntrantsCompetitionStandingsQuery;
    CSEEntrantsCompetitionStandingsQueryResult v[25];
    DWORD m_dwSize;
    static CONST XONLINE_ATTRIBUTE_SPEC ResultSpec[SE_ENTRANTS_COMPETITION_STANDINGS_NUM_RESULT_ATTRS];
};

#define SE_ENTRANTS_COMPETITION_STANDINGS_ID 0x2
#define SE_ENTRANTS_COMPETITION_STANDINGS_P_COMP_ID 0x82010000



//
// Query object for SEEntrantsCompetitionStandings query (id 0x2)
//
class CSEEntrantsCompetitionStandingsQuery : public ICompetitionQuery
{
public:
    CSEEntrantsCompetitionStandingsQuery()
    {
        m_State = STATE_IDLE;
        m_hTask = NULL;
        dwTotalItemsInResult = 0;
        dwItemsReturned = 0;
    }
    ~CSEEntrantsCompetitionStandingsQuery()
    {
        StopTask();
    }
    CSEEntrantsCompetitionStandingsQueryResults Results;
    DWORD dwTotalItemsInResult;
    DWORD dwItemsReturned;

    //--------------------------------------------------------------------------
    // After you've called Query to start a query, call this function about
    // once per frame to pump the task handle.  The HRESULT returned by this
    // function is the return value of XOnlineTaskContinue.  If the task has
    // completed successfully, the returned HRESULT is the return value of the
    // "GetResults" function for this type of query.  If no "GetResults"
    // function exists, the return value is that of XOnlineTaskContinue
    // You can test if a query is finished by testing that the returned HR is
    // not XONLINETASK_S_RUNNING.  In this case, it has either failed or
    // completed successfully.  If it has completed successfully, the results
    // of the query (if requested and if any exist) will be in the
    // dwTotalItemsInResult, dwItemsReturned, and Results members
    //--------------------------------------------------------------------------
    STDMETHOD(Process)()
    {
        HRESULT hr = S_FALSE;

        if(m_State == STATE_IDLE)
        {
            return hr;
        }

        //
        // Continue the task.  If it's completed
        // mark us done and close the task
        //

        switch(m_State)
        {
        case STATE_IDLE:
            // This never happens
            break;

        case STATE_RUNNING:
            hr = XOnlineTaskContinue(m_hTask);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // Is the task still running?
            if(hr == XONLINETASK_S_RUNNING)
            {
                break;
            }

            // The task is completed - get the results
            Results.SetSize(sizeof(Results.v));
            hr = XOnlineCompetitionSearchGetResults(m_hTask, &dwTotalItemsInResult, &dwItemsReturned, &Results.m_dwSize, (PBYTE)Results.v);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // On output, Results.m_dwSize is the number of bytes used, rather
            // than the number of elements that are valid
            Results.SetSize(dwItemsReturned);

            // Close the task and mark us done
            StopTask();
            m_State = STATE_DONE;
            break;
        case STATE_DONE:
            break;
        }

        return hr;
    }

    STDMETHOD(StopTask)()
    {
        HRESULT hr = S_FALSE;
        if(m_hTask)
        {
            hr = XOnlineTaskClose(m_hTask);
            m_hTask = NULL;
            m_State = STATE_IDLE;
        }
        return hr;
    }

    STDMETHOD_(VOID, Clear)()
    {
        Results.Clear();
    }

    //--------------------------------------------------------------------------
    // Call this function to start running a query.  You must specify all the
    // arguments listed (there are no optional arguments).
    //--------------------------------------------------------------------------
    STDMETHOD(Query)(
        ULONGLONG p_comp_id,
        DWORD dwPage)
    {
        //
        // If any previous query is done, go ahead and
        // honor this request
        //

        if(m_State == STATE_DONE)
        {
            StopTask();
            m_State = STATE_IDLE;
        }

        //
        // If we're still not in the idle state
        // then a query is running, so fail
        //

        if(m_State != STATE_IDLE)
        {
            return E_FAIL;
        }

        //
        // Setup the parameters (if there are any)
        //
        XONLINE_ATTRIBUTE CustomAttrs[1];
        ZeroMemory(CustomAttrs, sizeof(CustomAttrs));

        CustomAttrs[0].dwAttributeID = SE_ENTRANTS_COMPETITION_STANDINGS_P_COMP_ID;
        CustomAttrs[0].info.integer.qwValue = p_comp_id;


        //
        // Run the query
        //

        HRESULT hr = XOnlineCompetitionSearch(SE_ENTRANTS_COMPETITION_STANDINGS_ID, SE_ENTRANTS_ID, dwPage,
            sizeof(Results.v)/sizeof(Results.v[0]), sizeof(CustomAttrs)/sizeof(CustomAttrs[0]), CustomAttrs,
            sizeof(Results.ResultSpec)/sizeof(Results.ResultSpec[0]), Results.ResultSpec, NULL, &m_hTask);

        if(SUCCEEDED(hr)) { m_State = STATE_RUNNING; }
        return hr;
    }

    STDMETHOD_(BOOL, IsDone)()     const { return m_State == STATE_DONE; }
    STDMETHOD_(BOOL, IsRunning)()  const { return m_State == STATE_RUNNING; }
public:
    enum STATE
    {
        STATE_IDLE,
        STATE_RUNNING,
        STATE_DONE
    };

    STATE m_State;
    XONLINETASK_HANDLE m_hTask;
};




//
// CSEEntrantsCurrentEntrantsQueryResult represents a single return result from the
// SEEntrantsCurrentEntrantsQuery query
//
#pragma pack(push, 1)
class CSEEntrantsCurrentEntrantsQueryResult
{
public:
    ULONGLONG bi_entity_id;
    ULONGLONG att_puid;
    WCHAR     gamertag[16];
    ULONGLONG att_status;
    ULONGLONG att_sort;
};
#pragma pack(pop)

#define SE_ENTRANTS_CURRENT_ENTRANTS_NUM_RESULT_ATTRS (4 + 1) // bi_entity_id + custom return values


//  Collection of results for the SEEntrantsCurrentEntrants query
class CSEEntrantsCurrentEntrantsQueryResults
{
public:
    CSEEntrantsCurrentEntrantsQueryResults() { m_dwSize = 0; }

    // This function returns the number of valid
    // elements in the Results vector
    DWORD GetSize() { return m_dwSize; }
    CSEEntrantsCurrentEntrantsQueryResult &operator[]( DWORD i ) { return v[i]; }
private:
    void Clear() { m_dwSize = 0; }
    void Remove( DWORD i )
    {
        assert( i < m_dwSize );
        if( i < m_dwSize )
        {
            m_dwSize--;
            memcpy( &v[i], &v[i+1], sizeof( v[0] ) * ( m_dwSize - i ) );
        }
    }
    void SetSize( DWORD dwSize ) { m_dwSize = dwSize; }
    friend class CSEEntrantsCurrentEntrantsQuery;
    CSEEntrantsCurrentEntrantsQueryResult v[25];
    DWORD m_dwSize;
    static CONST XONLINE_ATTRIBUTE_SPEC ResultSpec[SE_ENTRANTS_CURRENT_ENTRANTS_NUM_RESULT_ATTRS];
};

#define SE_ENTRANTS_CURRENT_ENTRANTS_ID 0x3
#define SE_ENTRANTS_CURRENT_ENTRANTS_P_COMP_ID 0x82010000



//
// Query object for SEEntrantsCurrentEntrants query (id 0x3)
//
class CSEEntrantsCurrentEntrantsQuery : public ICompetitionQuery
{
public:
    CSEEntrantsCurrentEntrantsQuery()
    {
        m_State = STATE_IDLE;
        m_hTask = NULL;
        dwTotalItemsInResult = 0;
        dwItemsReturned = 0;
    }
    ~CSEEntrantsCurrentEntrantsQuery()
    {
        StopTask();
    }
    CSEEntrantsCurrentEntrantsQueryResults Results;
    DWORD dwTotalItemsInResult;
    DWORD dwItemsReturned;

    //--------------------------------------------------------------------------
    // After you've called Query to start a query, call this function about
    // once per frame to pump the task handle.  The HRESULT returned by this
    // function is the return value of XOnlineTaskContinue.  If the task has
    // completed successfully, the returned HRESULT is the return value of the
    // "GetResults" function for this type of query.  If no "GetResults"
    // function exists, the return value is that of XOnlineTaskContinue
    // You can test if a query is finished by testing that the returned HR is
    // not XONLINETASK_S_RUNNING.  In this case, it has either failed or
    // completed successfully.  If it has completed successfully, the results
    // of the query (if requested and if any exist) will be in the
    // dwTotalItemsInResult, dwItemsReturned, and Results members
    //--------------------------------------------------------------------------
    STDMETHOD(Process)()
    {
        HRESULT hr = S_FALSE;

        if(m_State == STATE_IDLE)
        {
            return hr;
        }

        //
        // Continue the task.  If it's completed
        // mark us done and close the task
        //

        switch(m_State)
        {
        case STATE_IDLE:
            // This never happens
            break;

        case STATE_RUNNING:
            hr = XOnlineTaskContinue(m_hTask);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // Is the task still running?
            if(hr == XONLINETASK_S_RUNNING)
            {
                break;
            }

            // The task is completed - get the results
            Results.SetSize(sizeof(Results.v));
            hr = XOnlineCompetitionSearchGetResults(m_hTask, &dwTotalItemsInResult, &dwItemsReturned, &Results.m_dwSize, (PBYTE)Results.v);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // On output, Results.m_dwSize is the number of bytes used, rather
            // than the number of elements that are valid
            Results.SetSize(dwItemsReturned);

            // Close the task and mark us done
            StopTask();
            m_State = STATE_DONE;
            break;
        case STATE_DONE:
            break;
        }

        return hr;
    }

    STDMETHOD(StopTask)()
    {
        HRESULT hr = S_FALSE;
        if(m_hTask)
        {
            hr = XOnlineTaskClose(m_hTask);
            m_hTask = NULL;
            m_State = STATE_IDLE;
        }
        return hr;
    }

    STDMETHOD_(VOID, Clear)()
    {
        Results.Clear();
    }

    //--------------------------------------------------------------------------
    // Call this function to start running a query.  You must specify all the
    // arguments listed (there are no optional arguments).
    //--------------------------------------------------------------------------
    STDMETHOD(Query)(
        ULONGLONG p_comp_id,
        DWORD dwPage)
    {
        //
        // If any previous query is done, go ahead and
        // honor this request
        //

        if(m_State == STATE_DONE)
        {
            StopTask();
            m_State = STATE_IDLE;
        }

        //
        // If we're still not in the idle state
        // then a query is running, so fail
        //

        if(m_State != STATE_IDLE)
        {
            return E_FAIL;
        }

        //
        // Setup the parameters (if there are any)
        //
        XONLINE_ATTRIBUTE CustomAttrs[1];
        ZeroMemory(CustomAttrs, sizeof(CustomAttrs));

        CustomAttrs[0].dwAttributeID = SE_ENTRANTS_CURRENT_ENTRANTS_P_COMP_ID;
        CustomAttrs[0].info.integer.qwValue = p_comp_id;


        //
        // Run the query
        //

        HRESULT hr = XOnlineCompetitionSearch(SE_ENTRANTS_CURRENT_ENTRANTS_ID, SE_ENTRANTS_ID, dwPage,
            sizeof(Results.v)/sizeof(Results.v[0]), sizeof(CustomAttrs)/sizeof(CustomAttrs[0]), CustomAttrs,
            sizeof(Results.ResultSpec)/sizeof(Results.ResultSpec[0]), Results.ResultSpec, NULL, &m_hTask);

        if(SUCCEEDED(hr)) { m_State = STATE_RUNNING; }
        return hr;
    }

    STDMETHOD_(BOOL, IsDone)()     const { return m_State == STATE_DONE; }
    STDMETHOD_(BOOL, IsRunning)()  const { return m_State == STATE_RUNNING; }
public:
    enum STATE
    {
        STATE_IDLE,
        STATE_RUNNING,
        STATE_DONE
    };

    STATE m_State;
    XONLINETASK_HANDLE m_hTask;
};




//
// CSEEventsTopologyQueryResult represents a single return result from the
// SEEventsTopologyQuery query
//
#pragma pack(push, 1)
class CSEEventsTopologyQueryResult
{
public:
    ULONGLONG bi_entity_id;
    ULONGLONG topology_id;
    ULONGLONG round;
    ULONGLONG start;
    ULONGLONG next_entity;
    ULONGLONG next_start;
    ULONGLONG player1;
    WCHAR     p1_gamertag[16];
    ULONGLONG player2;
    WCHAR     p2_gamertag[16];
    ULONGLONG winner;
    ULONGLONG loser;
    ULONGLONG att_map;
    WCHAR     att_name[200];
    __declspec( property( get=Getatt_icon ) ) CBlob att_icon;
    CBlob Getatt_icon() { return CBlob( blobatt_iconLength, blobatt_icon ); }
private:
    WORD      blobatt_iconLength;
    BYTE      blobatt_icon[400];
public:
};
#pragma pack(pop)

#define SE_EVENTS_TOPOLOGY_NUM_RESULT_ATTRS (14 + 1) // bi_entity_id + custom return values


//  Collection of results for the SEEventsTopology query
class CSEEventsTopologyQueryResults
{
public:
    CSEEventsTopologyQueryResults() { m_dwSize = 0; }

    // This function returns the number of valid
    // elements in the Results vector
    DWORD GetSize() { return m_dwSize; }
    CSEEventsTopologyQueryResult &operator[]( DWORD i ) { return v[i]; }
private:
    void Clear() { m_dwSize = 0; }
    void Remove( DWORD i )
    {
        assert( i < m_dwSize );
        if( i < m_dwSize )
        {
            m_dwSize--;
            memcpy( &v[i], &v[i+1], sizeof( v[0] ) * ( m_dwSize - i ) );
        }
    }
    void SetSize( DWORD dwSize ) { m_dwSize = dwSize; }
    friend class CSEEventsTopologyQuery;
    CSEEventsTopologyQueryResult v[25];
    DWORD m_dwSize;
    static CONST XONLINE_ATTRIBUTE_SPEC ResultSpec[SE_EVENTS_TOPOLOGY_NUM_RESULT_ATTRS];
};

#define SE_EVENTS_TOPOLOGY_ID 0x1
#define SE_EVENTS_TOPOLOGY_P_COMP_ID 0x82010000
#define SE_EVENTS_TOPOLOGY_P_MINIMUM_TOPOLOGY_ID 0x82030010
#define SE_EVENTS_TOPOLOGY_P_MAXIMUM_TOPOLOGY_ID 0x82030011



//
// Query object for SEEventsTopology query (id 0x1)
//
class CSEEventsTopologyQuery : public ICompetitionQuery
{
public:
    CSEEventsTopologyQuery()
    {
        m_State = STATE_IDLE;
        m_hTask = NULL;
        dwTotalItemsInResult = 0;
        dwItemsReturned = 0;
    }
    ~CSEEventsTopologyQuery()
    {
        StopTask();
    }
    CSEEventsTopologyQueryResults Results;
    DWORD dwTotalItemsInResult;
    DWORD dwItemsReturned;

    //--------------------------------------------------------------------------
    // After you've called Query to start a query, call this function about
    // once per frame to pump the task handle.  The HRESULT returned by this
    // function is the return value of XOnlineTaskContinue.  If the task has
    // completed successfully, the returned HRESULT is the return value of the
    // "GetResults" function for this type of query.  If no "GetResults"
    // function exists, the return value is that of XOnlineTaskContinue
    // You can test if a query is finished by testing that the returned HR is
    // not XONLINETASK_S_RUNNING.  In this case, it has either failed or
    // completed successfully.  If it has completed successfully, the results
    // of the query (if requested and if any exist) will be in the
    // dwTotalItemsInResult, dwItemsReturned, and Results members
    //--------------------------------------------------------------------------
    STDMETHOD(Process)()
    {
        HRESULT hr = S_FALSE;

        if(m_State == STATE_IDLE)
        {
            return hr;
        }

        //
        // Continue the task.  If it's completed
        // mark us done and close the task
        //

        switch(m_State)
        {
        case STATE_IDLE:
            // This never happens
            break;

        case STATE_RUNNING:
            hr = XOnlineTaskContinue(m_hTask);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // Is the task still running?
            if(hr == XONLINETASK_S_RUNNING)
            {
                break;
            }

            // The task is completed - get the results
            Results.SetSize(sizeof(Results.v));
            hr = XOnlineCompetitionTopologyGetResults(m_hTask, &dwTotalItemsInResult, &dwItemsReturned, &Results.m_dwSize, (PBYTE)Results.v);
            if(FAILED(hr))
            {
                StopTask();
                break;
            }

            // On output, Results.m_dwSize is the number of bytes used, rather
            // than the number of elements that are valid
            Results.SetSize(dwItemsReturned);

            // Close the task and mark us done
            StopTask();
            m_State = STATE_DONE;
            break;
        case STATE_DONE:
            break;
        }

        return hr;
    }

    STDMETHOD(StopTask)()
    {
        HRESULT hr = S_FALSE;
        if(m_hTask)
        {
            hr = XOnlineTaskClose(m_hTask);
            m_hTask = NULL;
            m_State = STATE_IDLE;
        }
        return hr;
    }

    STDMETHOD_(VOID, Clear)()
    {
        Results.Clear();
    }

    //--------------------------------------------------------------------------
    // Call this function to start running a query.  You must specify all the
    // arguments listed (there are no optional arguments).
    //--------------------------------------------------------------------------
    STDMETHOD(Query)(
        ULONGLONG p_comp_id,
        ULONGLONG p_minimum_topology_id,
        ULONGLONG p_maximum_topology_id,
        DWORD dwPage)
    {
        //
        // If any previous query is done, go ahead and
        // honor this request
        //

        if(m_State == STATE_DONE)
        {
            StopTask();
            m_State = STATE_IDLE;
        }

        //
        // If we're still not in the idle state
        // then a query is running, so fail
        //

        if(m_State != STATE_IDLE)
        {
            return E_FAIL;
        }

        //
        // Setup the parameters (if there are any)
        //
        //
        // Run the query
        //

        HRESULT hr = XOnlineCompetitionTopology(SE_ID, p_comp_id,
            dwPage, sizeof(Results.v)/sizeof(Results.v[0]),
            // Topology IDs are actually DWORDs, so we cast down to DWORD from
            // ULONGLONG here.  Use the TOPOLOGY_ID(round, event) macro defined
            // in xonline.h to make these arguments
            (DWORD)p_minimum_topology_id, (DWORD)p_maximum_topology_id,
            sizeof(Results.ResultSpec)/sizeof(Results.ResultSpec[0]), Results.ResultSpec, NULL, &m_hTask);

        if(SUCCEEDED(hr)) { m_State = STATE_RUNNING; }
        return hr;
    }

    STDMETHOD_(BOOL, IsDone)()     const { return m_State == STATE_DONE; }
    STDMETHOD_(BOOL, IsRunning)()  const { return m_State == STATE_RUNNING; }
public:
    enum STATE
    {
        STATE_IDLE,
        STATE_RUNNING,
        STATE_DONE
    };

    STATE m_State;
    XONLINETASK_HANDLE m_hTask;
};
