//-----------------------------------------------------------------------------
//
// Xbox Matchmaking Definitions for Title: Simple Matchmaking XDK Sample [0xFFFF0114]
// Generated by MatchSim
//
//-----------------------------------------------------------------------------
#pragma once


#include <xtl.h>
#include <xonline.h>
#include <assert.h>




//-----------------------------------------------------------------------------
// Constants
//-----------------------------------------------------------------------------

//
// Attribute IDs                          ID num   Data Type
//                                        ------   ----------------------------
const DWORD XATTRIB_TYPE                 = 0x0001 | X_ATTRIBUTE_DATATYPE_INTEGER;
const DWORD XATTRIB_MAP                  = 0x0002 | X_ATTRIBUTE_DATATYPE_INTEGER;
const DWORD XATTRIB_NAME                 = 0x0003 | X_ATTRIBUTE_DATATYPE_STRING;
const DWORD XATTRIB_AVG_RANK             = 0x0004 | X_ATTRIBUTE_DATATYPE_INTEGER;
const DWORD XATTRIB_CONFIG               = 0x0005 | X_ATTRIBUTE_DATATYPE_BLOB;


//
// Attribute Maximum Lengths
// (for strings, this doesn't include the terminating NULL)
//
const DWORD XATTRIB_NAME_MAX_LEN = 25; // Name attribute
const DWORD XATTRIB_CONFIG_MAX_LEN = 10; // Config attribute


// Specify X_MATCH_NULL_INTEGER for optional integer query arguments
const ULONGLONG X_MATCH_NULL_INTEGER  = 0x7FFFFFFFFFFFFFFFui64;

// Maximum number of sessions returned by FindSessions query
const DWORD MAX_FIND_SESSIONS_RESULTS = 10;

// Maximum number of sessions returned by FindSessionByID query
const DWORD MAX_FIND_SESSION_BY_ID_RESULTS = 1;

// Number of QoS probes
const DWORD NUM_QOS_PROBES   =     8;

// Maximum bandwidth to consume for QoS probes
const DWORD QOS_BITS_PER_SEC = 16000;





//-----------------------------------------------------------------------------
// Types
//-----------------------------------------------------------------------------

// Helper class for getting/setting blob attributes
class CBlob
{
public:
    CBlob() : m_wLength( 0 ), m_pvData( NULL ) {}
    CBlob( WORD wLength, const PVOID pvData ) : m_wLength( wLength), m_pvData( pvData) {}
    CBlob( const CBlob & b ) { *this = b; }
    CBlob & operator=( const CBlob & b ) 
    { m_wLength = b.Length; m_pvData = b.Data; return *this; }
    BOOL operator==( const CBlob & b ) const  
    { return m_wLength == b.Length && memcmp( m_pvData, b.Data, b.Length ) == 0; }
    BOOL IsNull() { return m_pvData == NULL; }
    __declspec( property( put = SetData, get=GetData ) ) const PVOID Data;
    const PVOID GetData() const { return m_pvData; }
    VOID SetData( const PVOID pvData ) { m_pvData = pvData; }
    __declspec( property( put = SetLength, get=GetLength ) ) WORD Length;
    WORD GetLength() const { return m_wLength; }
    VOID SetLength( WORD wLength ) { m_wLength = wLength; }
private:
    WORD m_wLength;
    PVOID m_pvData;
};

// A null blob is defined as having a NULL pointer
#define NULL_BLOB CBlob( 0, NULL )

// Macro for declaring "blob literals" (much like the _T() macro does for strings)
#define B( length, ptr ) CBlob( length, (const PVOID) ptr )

class CSession
{
public:
    CSession();
    ~CSession();

    HRESULT Create();
    HRESULT Update();
    HRESULT Delete();
    HRESULT Process();

    VOID    Reset();

    DWORD PublicFilled;
    DWORD PublicOpen;
    DWORD PrivateFilled;
    DWORD PrivateOpen;
    XNKEY KeyExchangeKey;
    XNKID SessionID;

    BOOL IsUpdating() const { return m_State == STATE_UPDATING; }
    BOOL IsDeleting() const { return m_State == STATE_DELETING; }
    BOOL IsCreating() const { return m_State == STATE_CREATING; }
    BOOL Exists()     const { return m_State == STATE_ACTIVE || IsUpdating(); }

    // Attribute Accessors

    BOOL IsListening() const { return m_bListening; }
    __declspec( property( put = SetQosResponse, get = GetQosResponse ) ) CBlob QosResponse;
    CBlob GetQosResponse();
    VOID SetQosResponse( CBlob Value );
    VOID Listen( BOOL bEnable = TRUE, DWORD dwBitsPerSec = 0 );
    static const DWORD NO_WAIT = 1;

    __declspec( property( put = SetType, get=GetType ) ) ULONGLONG Type;
    ULONGLONG GetType();
    VOID SetType( ULONGLONG Value );

    __declspec( property( put = SetMap, get=GetMap ) ) ULONGLONG Map;
    ULONGLONG GetMap();
    VOID SetMap( ULONGLONG Value );

    __declspec( property( put = SetName, get=GetName ) ) const WCHAR * Name;
    const WCHAR * GetName();
    VOID SetName( const WCHAR * Value );

    __declspec( property( put = SetAvgRank, get=GetAvgRank ) ) ULONGLONG AvgRank;
    ULONGLONG GetAvgRank();
    VOID SetAvgRank( ULONGLONG Value );

    __declspec( property( put = SetConfig, get=GetConfig ) ) CBlob Config;
    CBlob GetConfig();
    VOID SetConfig( CBlob Value );

private:

    // The m_Attributes array is accessed using predefined constants:
    enum
    {
        TYPE_INDEX,
        MAP_INDEX,
        NAME_INDEX,
        AVG_RANK_INDEX,
        CONFIG_INDEX,
        NUM_ATTRIBUTES
    };

    XONLINE_ATTRIBUTE m_Attributes[NUM_ATTRIBUTES];

    // Storage for the Name string attribute
    WCHAR m_strName[XATTRIB_NAME_MAX_LEN+1];

    // Storage for the Config blob attribute
    BYTE  m_blobConfig[XATTRIB_CONFIG_MAX_LEN];


    // Qos listening
    struct QosQEntry
    {
        XNKID  SessionID;            // Session to unregister
        DWORD  dwStartTick;          // Time entry was added
        struct QosQEntry *pNext;     // Next item in the queue
    };
    class CSessionQosQ
    {
    public:
        CSessionQosQ()
        {
            m_pHead = m_pTail = NULL;
        }

        VOID Add( XNKID & SessionID, DWORD dwStartTick )
        {
            assert( m_pHead && m_pTail || !m_pHead && !m_pTail );
            QosQEntry *pItem = new QosQEntry;
            pItem->SessionID = SessionID;
            pItem->dwStartTick = dwStartTick;
            pItem->pNext = NULL;
            if( m_pTail )
                m_pTail->pNext = pItem;
            m_pTail = pItem;
            if( !m_pHead )
                m_pHead = pItem;
        }

        VOID Remove( XNKID &SessionID )
        {
            assert( m_pHead && m_pTail || !m_pHead && !m_pTail );
            QosQEntry *pPrev = NULL;

            for( QosQEntry *pItem = m_pHead; pItem != NULL; pItem = pItem->pNext )
            {
                if( memcmp(&pItem->SessionID, &SessionID, sizeof( XNKID ) ) == 0 )
                {
                    if( pPrev )
                    {
                        pPrev->pNext = pItem->pNext;
                    }
                    else
                    {
                        m_pHead = pItem->pNext;
                    }
                    if( pItem == m_pTail )
                    {
                        m_pTail = pPrev;
                    }
                    delete pItem;
                    break;
                }
                pPrev = pItem;
            }
        }


        VOID Dequeue()
        {
            assert( m_pHead && m_pTail || !m_pHead && !m_pTail );
            QosQEntry *pItem = m_pHead;
            if( pItem )
            {
                m_pHead = pItem->pNext;
                delete pItem;
                if( !m_pHead )
                    m_pTail = NULL;
            }
        }

        const QosQEntry *Head() const { return m_pHead; }
        const QosQEntry *Tail() const { return m_pTail; }
    private:

        QosQEntry *m_pHead;
        QosQEntry *m_pTail;
    };

    CSessionQosQ m_SessionQosQ;
    BOOL  m_bListening;              // Listening for Qos probes
    CBlob m_QosResponse;
    VOID  PurgeSessionQ( BOOL fRemoveAll = FALSE );
    VOID  PurgeSessionQHead();



    HRESULT ProcessStateCreateSession();
    HRESULT ProcessStateUpdateSession();
    HRESULT ProcessStateDeleteSession();
    HRESULT ProcessStateActiveSession();

    VOID    Close();
    VOID    SetupAttributes();

    XONLINETASK_HANDLE m_hSessionTask;

    enum STATE
    {
        STATE_IDLE,
        STATE_CREATING,
        STATE_UPDATING,
        STATE_DELETING,
        STATE_ACTIVE
    };

    STATE m_State;
    BOOL  m_bKeyRegistered;
    BOOL  m_bUpdate;

};




//
// CFindSessionsResult represents a single return result from the
// FindSessions query
//
#pragma pack(push, 1)
class CFindSessionsResult
{
public:
    // The query return attributes must come first, and in the order
    // returned by the query
    WCHAR     Name[XATTRIB_NAME_MAX_LEN+1];
    ULONGLONG AvgRank;
    __declspec( property( get=GetConfig ) ) CBlob Config;
    CBlob GetConfig() { return CBlob( blobConfigLength, blobConfig ); }
private:
    WORD      blobConfigLength;
    BYTE      blobConfig[XATTRIB_CONFIG_MAX_LEN];
public:


    XNKID      SessionID;
    XNKEY      KeyExchangeKey;
    XNADDR     HostAddress;
    DWORD      PublicOpen;
    DWORD      PrivateOpen;
    DWORD      PublicFilled;
    DWORD      PrivateFilled;
    XNQOSINFO* pQosInfo;

};
#pragma pack(pop)



//  Collection of results for the FindSessions query
class CFindSessionsQueryResults
{
public:
    CFindSessionsQueryResults() { m_dwSize = 0; }
    DWORD Size() { return m_dwSize; }
    CFindSessionsResult &operator[]( DWORD i ) { return v[i]; }
private:
    void Clear() { m_dwSize = 0; }
    void Remove( DWORD i )
    {
        assert( i < m_dwSize );
        if( i < m_dwSize )
        {
            m_dwSize--;
            memcpy( &v[i], &v[i+1], sizeof( v[0] ) * ( m_dwSize - i ) );
        }
    }
    void SetSize( DWORD dwSize ) { m_dwSize = dwSize; }
    friend class CFindSessionsQuery;
    CFindSessionsResult v[MAX_FIND_SESSIONS_RESULTS];
    DWORD m_dwSize;
};



//
// Query object for FindSessions query (id 0x1)
//
class CFindSessionsQuery
{
public:
    CFindSessionsQuery();
    ~CFindSessionsQuery();
    CFindSessionsQueryResults Results;

    HRESULT Process();
    void Cancel();
    void Clear();
    BOOL Done()      const { return m_State == STATE_DONE; }
    BOOL Succeeded() const { return SUCCEEDED( m_hrQuery ); }
    HRESULT Query(
                  ULONGLONG Type,
                  ULONGLONG Map,
                  ULONGLONG AvgRank // Optional: X_MATCH_NULL_INTEGER to omit
                 );
    BOOL IsRunning() const { return m_State == STATE_RUNNING || m_State == STATE_PROBING_CONNECTIVITY; }
    BOOL IsProbing() const { return m_State == STATE_PROBING_BANDWIDTH; }
    HRESULT Probe();
private:

    // Quality of Service
    const XNADDR *m_rgpXnAddr[ MAX_FIND_SESSIONS_RESULTS ];
    const XNKID  *m_rgpXnKid [ MAX_FIND_SESSIONS_RESULTS ];
    const XNKEY  *m_rgpXnKey [ MAX_FIND_SESSIONS_RESULTS ];
    XNQOS  *m_pXnQos;
    enum STATE
    {
        STATE_IDLE,
        STATE_RUNNING,
        STATE_PROBING_CONNECTIVITY,
        STATE_PROBING_BANDWIDTH,
        STATE_DONE
    };

    STATE m_State;
    HRESULT m_hrQuery;
    XONLINETASK_HANDLE m_hSearchTask;
};




//
// CFindSessionByIDResult represents a single return result from the
// FindSessionByID query
//
#pragma pack(push, 1)
class CFindSessionByIDResult
{
public:

    XNKID      SessionID;
    XNKEY      KeyExchangeKey;
    XNADDR     HostAddress;
    DWORD      PublicOpen;
    DWORD      PrivateOpen;
    DWORD      PublicFilled;
    DWORD      PrivateFilled;

};
#pragma pack(pop)



//  Collection of results for the FindSessionByID query
class CFindSessionByIDQueryResults
{
public:
    CFindSessionByIDQueryResults() { m_dwSize = 0; }
    DWORD Size() { return m_dwSize; }
    CFindSessionByIDResult &operator[]( DWORD i ) { return v[i]; }
private:
    void Clear() { m_dwSize = 0; }
    void Remove( DWORD i )
    {
        assert( i < m_dwSize );
        if( i < m_dwSize )
        {
            m_dwSize--;
            memcpy( &v[i], &v[i+1], sizeof( v[0] ) * ( m_dwSize - i ) );
        }
    }
    void SetSize( DWORD dwSize ) { m_dwSize = dwSize; }
    friend class CFindSessionByIDQuery;
    CFindSessionByIDResult v[MAX_FIND_SESSION_BY_ID_RESULTS];
    DWORD m_dwSize;
};



//
// Query object for FindSessionByID query (id 0x2)
//
class CFindSessionByIDQuery
{
public:
    CFindSessionByIDQuery();
    ~CFindSessionByIDQuery();
    CFindSessionByIDQueryResults Results;

    HRESULT Process();
    void Cancel();
    void Clear();
    BOOL Done()      const { return m_State == STATE_DONE; }
    BOOL Succeeded() const { return SUCCEEDED( m_hrQuery ); }
    HRESULT Query(
                  ULONGLONG SessionID
                 );
    BOOL IsRunning()  const { return m_State == STATE_RUNNING; }
private:
    enum STATE
    {
        STATE_IDLE,
        STATE_RUNNING,
        STATE_DONE
    };

    STATE m_State;
    HRESULT m_hrQuery;
    XONLINETASK_HANDLE m_hSearchTask;
};
