//-----------------------------------------------------------------------------
// File: SimpleMatch.cpp
//
// Desc: Illustrates online matchmaking on Xbox using the classes generated by
// the MatchSim tool. Game titles use the Xbox Live Matchmaking Service to  
// exchange information about currently running sessions. An Xbox title that 
// is hosting an online-game session uses the API to provide the service with 
// information about its session. Other Xbox systems can then use the API to  
// query the service to find appropriate online-game sessions to join.
//
// Hist: 02.05.03 - New for April release 
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------

#include <xtl.h>                  
#include <xonline.h>              
#include <assert.h> 
#include "Match.h"

//-----------------------------------------------------------------------------
// Constants
//-----------------------------------------------------------------------------

// Each advertised session also specifies a number of
// public and  private slots, or openings that are available for
// players to join.
// A public slot, is an opening that is available to any player who finds
// that session using the matchmaking service.   By contrast,  private      
// slots are available only to players who have been invited to join      
// that session by a  friend.
// The title that is hosting the session determines how many slots
// are available and updates this information as players join and leave the
// session.  The matchmaking query system returns only those sessions      
// where the number of  public slots is greater than or equal to the      
// number of authenticated users and guests on the querying Xbox.      
// This sample specifies MAX_PUBLIC_SLOTS as the
// maximum number of public slots in a session, and MAX_PRIVATE_SLOTS as
// the maximum number of private slots in a session.

const DWORD MAX_PUBLIC_SLOTS  = 5;
const DWORD MAX_PRIVATE_SLOTS = 5;

//-----------------------------------------------------------------------------
// Types
//-----------------------------------------------------------------------------

// There are four types of games:
// *  SLAYER: The classic death-match.
// *  TEAM_SLAYER: A Slayer match, with players split into two teams.
// *  KING_OF_HILL: Players try to control a position for two minutes.
// *  CAPTURE_THE_FLAG: Players form teams and try to capture the enemy
//                      flag.
typedef enum 
{
    SLAYER,             
    TEAM_SLAYER,
    KING_OF_HILL,
    CAPTURE_THE_FLAG
} GAME_TYPE;




//-----------------------------------------------------------------------------
// Prototypes
//-----------------------------------------------------------------------------
DWORD GetAcceptedInviteUsers(
                             XONLINE_ACCEPTED_GAMEINVITE&GameInvite,
                             XONLINE_USER*rgStoredUsers,
                             DWORD dwNumStoredUsers,
                             XONLINE_USER*rgLogonUsers );
BOOL FindSessionByID( XNKID& SessionID, 
                      XNKEY *pKeyExchangeKey, XNADDR *pHostXnAddr );
VOID HostSession();
VOID JoinInvitedSession( XONLINE_ACCEPTED_GAMEINVITE & GameInvite );
VOID JoinSession( XNKID& SessionID, XNKEY& KeyExchangeKey, XNADDR& HostAddress );
VOID PlayJoinedSession();
VOID LeaveJoinedSession();
BOOL FindFirstSession( GAME_TYPE Type, ULONGLONG Map,
                    ULONGLONG AvgPlayerRank,
                    XNKID *pSessionID, XNKEY *pKeyExchangeKey, XNADDR *pHostXnAddr );
VOID SetSignedInUsersPresence( DWORD dwState );
VOID ServiceHostedGameSession();
BOOL SignIn( XONLINE_USER*pLogonUsers );
VOID __cdecl Print( const WCHAR*strFormat, ... );
VOID __cdecl Error( const WCHAR*strFormat, ... );
VOID UIMsg( const WCHAR* strText );
VOID BootToDash( DWORD dwReason );




//-----------------------------------------------------------------------------
// Global variables
//-----------------------------------------------------------------------------

// Each advertised session has a unique  session id and a
// session key-exchange key assigned by the Xbox Live matchmaking service.       
// This sample uses the JoinedSessionID variable to store the session id for the
// current session.  The JoinedKeyExchangeKey variable is used to store the 
// key-exchange key (for secure communications) for the current session.

XNKID JoinedSessionID;
XNKEY JoinedKeyExchangeKey;

// The host Xbox Network Address (XNADDR) and Internet Address (IN_ADDR)
// are stored in JoinedHostXnAddr and JoinedHostInAddr respectively.
XNADDR  JoinedHostXnAddr;
IN_ADDR JoinedHostInAddr;

// The currently hosted session. This class is generated by the MatchSim
// tool.
CSession Session;

// When a title successfully signs in, a task handle is returned that must be
// serviced by the title for the duration of the Xbox Live Session.  The
// global  hLogonTask is used to store this task handle.
XONLINETASK_HANDLE hLogonTask;




//-----------------------------------------------------------------------------
// Name: main()
// Desc: Entry point to the program.
//
// The main function demonstrates key matchmaking tasks:
// *   Checking for, and joining, an existing accepted game invitation.    
// *   Creating (advertising) a new game session.
// *   Updating an existing game session.
// *   Deleting a game session once it is no longer needed.
// *   Querying for game sessions.
// This sample does not have a user-interface and does minimalistic error
// handling.   
//-----------------------------------------------------------------------------
VOID __cdecl main()
{
    OutputDebugStringA( "SAMPLE: SimpleMatch: main\n" );

    XONLINE_USER StoredUsers[XONLINE_MAX_STORED_ONLINE_USERS];
    DWORD dwNumStoredUsers;
    XONLINE_USER LogonUsers[XONLINE_MAX_LOGON_USERS]= {0};
    
   // Initialize Input Devices this is required for account enumeration on 
    // Memory Units
    XInitDevices( 0, NULL );
    
    // Before we can enumerate user accounts on any attached Memory Units, we
    // must first allow them sufficient time to mount. 
    while( XGetDeviceEnumerationStatus() == XDEVICE_ENUMERATION_BUSY ){}

    // Before using the XBox Live APIs, a title  must first call XOnlineStartup.     
    // XOnlineStartup will automatically call XNetStartup and WSAStartup with
    // reasonable defaults in order to initialize the Xbox Secure Networking Library and
    // Winsock respectively. If you require special parameters for those functions
    // your title should can call them first before calling
    // XOnlineStartup.
    HRESULT hr = XOnlineStartup( NULL );
    
    // The XOnlineGetUsers function will enumerate both the hard disk and any     
    // attached memory units looking for user accounts.

    hr = XOnlineGetUsers( StoredUsers, &dwNumStoredUsers );
    assert( SUCCEEDED( hr ) );
    
    // If no accounts were found, a tile must give the player the  option of 
    // going to the online dash to create new account. In addition, it is
    // possible for a player to actually insert/remove an MU while
    // the title account selection UI is active.  A title must
    // call XOnlineGetUsers repeatedly to account for this.
    // For demonstration purposes, we just boot to the account signup section
    // of the online dash if no accounts are found.

    if( dwNumStoredUsers == 0 )
    {
        Print( L"No user accounts found." );
        BootToDash( XLD_LAUNCH_DASHBOARD_NEW_ACCOUNT_SIGNUP );
    }
    
    // After initialization, a title should check for an accepted game     
    // invitation. An accepted game invitation can exist for one of two reasons:
    // 1. A gamer on this console was playing another title and accepted an    
    //    invitation (from a friend) to join a session in this title  
    //    (via XOnlineFriendsAnswerGameInvite).
    // 2. A gamer on this console, who was not playing this title, decided to
    //    join (using XOnlineFriendsJoinGame) the session of a friend
    // who was playing this title.
    //
    // The XOnlineFriendsGetAcceptedGameInvite function is used to check
    // for an accepted cross-title game invitation.    
    // XOnlineFriendsGetAcceptedGameInvite return S_OK if there was
    // an  invitation, and fill an XONLINE_ACCEPTED_GAMEINVITE structure
    // with information about it.  If no accepted game invitation exists,
    // the function returns S_FALSE.
    
    BOOL bGameInvitation;
    XONLINE_ACCEPTED_GAMEINVITE GameInvite;
    hr = XOnlineFriendsGetAcceptedGameInvite( &GameInvite );
    bGameInvitation = ( hr == S_OK );
    
    if( bGameInvitation )
    {
        Print( L"Found an existing accepted Invitation" );

        // For an accepted game invitation, a title should attempt to
        // sign in using the same users that were logged in at the time the    
        // cross-title invitation was accepted.  We call GetAcceptedInviteUsers,
        // a convenience function, to extract the invited users into LogonUsers
        // and then check to see if at least one was found.   

        DWORD dwNumUsers = GetAcceptedInviteUsers( GameInvite, StoredUsers,
            dwNumStoredUsers, LogonUsers );
        
        if( dwNumUsers == 0 ) Error( L"No Users found in Game Invite" );
        
        // To sign in, we call the SignIn function (see signin.cpp).  
        if( !SignIn( LogonUsers ) )
            BootToDash( XLD_LAUNCH_DASHBOARD_MAIN_MENU );

        SetSignedInUsersPresence( XONLINE_FRIENDSTATE_FLAG_ONLINE );

        JoinInvitedSession( GameInvite );
        PlayJoinedSession();
        LeaveJoinedSession();        
    }
    else
    {
        // Sign in the first user account and try to find an
        // existing session to join.
        LogonUsers[0] = StoredUsers[0];
        
        if( !SignIn( LogonUsers ) )
            BootToDash( XLD_LAUNCH_DASHBOARD_MAIN_MENU );

        SetSignedInUsersPresence( XONLINE_FRIENDSTATE_FLAG_ONLINE );
        
        // Locate a session using the FindFirstSession function, 
        // specifying that a SLAYER match on map 4, with an average player
        // rank of 20 (or better) is desired.
        // The first session found is returned.
        XNKID FoundSessionID;
        XNKEY FoundExchangeKey;
        XNADDR FoundHostAddr;
        if( FindFirstSession( SLAYER, 4, 20, &FoundSessionID, &FoundExchangeKey,
                         &FoundHostAddr ) )
        {
            Print( L"Joining Session ..." );

            JoinSession( FoundSessionID, FoundExchangeKey, FoundHostAddr );
            PlayJoinedSession();            
            LeaveJoinedSession();
        }
        else
        {
           HostSession(); // No sessions were found, so host one.
        }
    }

    Print( L"Signing off..." );

    // A title signs off users by calling XOnlineTaskClose on the
    // task handle returned by XOnlineLogon.  Another situation in which users
    // are signed off is if the Xbox Live Service realizes the task handle 
    // returned by XOnlineLogon is not being serviced by the title (
    // e.g. the user turned the console off).
    
    XOnlineTaskClose( hLogonTask );
    
    // When a title is through with the XBox Live APIs, it can call XOnlineCleanup
    // to perform final cleanup for the online functions.
    OutputDebugStringA( "SAMPLE: SimpleMatch: exit\n" );
    XOnlineCleanup();
    
    BootToDash( XLD_LAUNCH_DASHBOARD_MAIN_MENU );
}




//-----------------------------------------------------------------------------
// Name: CreateSession()
// Desc: Advertise a new game session.
//
// The CreateSession function initializes the session attributes and then calls
// CSession::Create to create the new session.   
// Initially, one public player slot is used.  
//-----------------------------------------------------------------------------
VOID CreateSession()
{

    // Set the filled/opened public/private slots for this session
    Session.PublicFilled  = 1;
    Session.PublicOpen     = MAX_PUBLIC_SLOTS - Session.PublicFilled;
    Session.PrivateFilled = 0;
    Session.PrivateOpen    = MAX_PRIVATE_SLOTS - Session.PrivateFilled;

    // Set the title specific attributes
    // Each attribute added using a MatchSim tool results in a property
    // being added to the CSession class.  The code generated by MatchSim
    // uses a Microsoft extension to C++ which allows a convenient syntax
    // for setting these properties.  In addition, the traditional
    // getter/setter methods are also generated, and it's a matter of 
    // personal taste as to which one is used.
    Session.Name = L"The Pit"; // Same as Session.SetName( L"The Pitt" )
    Session.Type = SLAYER; // Same as Session.SetType( SLAYER )
    Session.Map = 4;       // Same as Session.SetMap( 4 )
    Session.AvgRank = 20;  // Same as Session.SetAvgRank( 20 )
    Session.Config = B( 1, "A" ); // Same as Session.SetConfig( B( 1, "A" ) )

    Print( L"Creating new Session" );
    
    HRESULT hr = Session.Create();

    if( hr != S_OK ) Error( L"Session Creation failed with 0x%x", hr );


    // In order to complete the creation process, the
    // session object should be serviced using for as long as 
    // XONLINETASK_S_RUNNING is returned.  The logon task, hLogonTask,
    // must also be serviced in order to remain connected.  
    
    do
    {
        hr = XOnlineTaskContinue( hLogonTask );
        if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x", hr );
        hr = Session.Process();
    } while( hr == XONLINETASK_S_RUNNING );
    
    if( hr != XONLINETASK_S_SUCCESS )
        Error( L"Creation Task Failed with 0x%x", hr );
    
    Print( L"Session Created" );

    // The session id and key-exchange key for the current session is
    // automatically registered, by the CSession class,
    // with the Xbox Secure Networking Library using the 
    // XNetRegisterKey function.  The XNetRegisterKey function informs 
    // the network stack to accept packets from other Xbox consoles 
    // that are using the same session key.  
    
    // Once a game session begins, the title should set the online 
    // notification state for each signed on user to indicate that 
    // they are online, playing, and (if the game supports it) joinable.
    
    SetSignedInUsersPresence(
        XONLINE_FRIENDSTATE_FLAG_ONLINE  | 
        XONLINE_FRIENDSTATE_FLAG_PLAYING |
        XONLINE_FRIENDSTATE_FLAG_JOINABLE );

    // Once a session has been created, it automatically listens for
    // quality of service probes from other consoles.
    // The QosResponse property specifies the data to be returned in
    // response to those probes.  This value can be changed on the fly,
    // and titles might use this data to provide
    // meaningful information about the current state of the game.
    Session.QosResponse = B( 5, "HELLO" );

    // The Listen method can be used to turn on/off Qos listening for
    // a session.  
}



//-----------------------------------------------------------------------------
// Name: ServiceHostedGameSession()
// Desc: Service the session and logon tasks for dwDuration seconds.
//
// This is the type of processing that would be done your game loop.
//-----------------------------------------------------------------------------
VOID ServiceHostedGameSession()
{
    
    DWORD dwTickStart = GetTickCount();
    const DWORD dwDuration = 15000; // 15 seconds 

    while( ( GetTickCount()- dwTickStart ) < dwDuration )
    {
        HRESULT hr = XOnlineTaskContinue( hLogonTask );
        if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x",   hr );
        hr =  Session.Process();
        if( FAILED( hr ) ) Error( L"Session Task Failed with 0x%x", hr );
    }
}




//-----------------------------------------------------------------------------
// Name: UpdateSession()
// Desc: Update an existing session.
//-----------------------------------------------------------------------------
VOID UpdateSession()
{
    // Update session information
    Session.PublicFilled  = 2;
    Session.PublicOpen     = MAX_PUBLIC_SLOTS - Session.PublicFilled;
    Session.PrivateFilled = 1;
    Session.PrivateOpen     = MAX_PRIVATE_SLOTS - Session.PrivateFilled;

    Print( L"Updating Session" );
    
    HRESULT hr = Session.Update();

    // Service the session until updated.  Waiting for the session
    // to update is not required with the CSession object.  A title
    // can simply continue to service the session in the game loop.
    // A title can also call Update again even if an existing Update
    // is in progress (e.g. as players joing the game)
    do
    {
        hr = XOnlineTaskContinue( hLogonTask );
        if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x", hr );
        hr = Session.Process();
    } while ( hr == XONLINETASK_S_RUNNING );

    if( FAILED( hr ) ) Error( L"Update Session failed with 0x%x", hr );

    Print( L"Session Updated" );
}




//-----------------------------------------------------------------------------
// Name: DeleteSession()
// Desc: Delete existing session.
//-----------------------------------------------------------------------------
VOID DeleteSession()
{

    HRESULT hr = Session.Delete();

    if( hr == XONLINETASK_S_RUNNING )
    {
        // In order to complete the removal process, service the session 
        // for as long as XONLINETASK_S_RUNNING is returned.  
        // The logon task, hLogonTask, must also be serviced in 
        // order to remain connected.  
        
        do
        {
            hr = XOnlineTaskContinue( hLogonTask );
            if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x", hr );
            hr = Session.Process();
        } while( hr == XONLINETASK_S_RUNNING );
                
        SetSignedInUsersPresence( XONLINE_FRIENDSTATE_FLAG_ONLINE );
        
        Print( L"Session Deleted" );
    }
    else
        Error( L"Session Delete failed with 0x%x", hr );
}




//-----------------------------------------------------------------------------
// Name: HostSession()
// Desc: Host a session. 
//-----------------------------------------------------------------------------
VOID HostSession()
{
    // When a title decides to host a session it is responsible for:
    //
    // *  Creating the Session:  Title advertises the session with the
    // Xbox Live Matchmaking service.  The console advertising the session,
    // is the  host of the session.  The host, and not the matchmaking
    // service, is responsible for managing game communication between
    // consoles.
    //
    // *  Updating the Session:  As the session state changes (e.g. as
    // players join and leave the session), the title updates the session
    // information on the server.
    //
    // *  Deleting the Session: The lifetime of the session is determined
    // by the title.  Titles that support join-in-progress games might 
    // leave the session advertised for the duration
    // of game play.  Other titles, which do not support join-in-progress, 
    // would remove the session after the game starts.
    
    // Create the new session
    CreateSession();
    
    // The hosting console must service the session task handle
    // as well as the logon task.
    ServiceHostedGameSession();
    
    // Update the session 
    UpdateSession();
    
    // Service the game for a while
    ServiceHostedGameSession();
    
    // Finally, delete the session
    DeleteSession();

    // The hosting console must service the session task handle
    // as well as the logon task. Even though there is no
    // active session, the session task should be serviced
    // so that any quality of service probes from other
    // consoles can be told that the session is no longer
    // active
    ServiceHostedGameSession();
            
}




//-----------------------------------------------------------------------------
// Name: FindFirstSession()
// Desc: Execute the custom query for this sample looking for existing 
//       sessions.
//
// The Xbox Live Matchmaking service provides a powerful search   
// mechanism that titles can use to obtain a list of
// advertised game sessions that meet some matching criteria.  Each
// title defines one or more matchmaking  queries, which
// does the actual filtering of available sessions.   Each query
// is given a unique (to the title) id and is installed onto the matchmaking 
// servers by Xbox Developer Support.
// Queries use the attributes associated with a session when filtering. 
// Queries are created using the  MatchSim tool and submitted to 
// Xbox Developer Support.  A query may allow one or more search parameters
// to be specified by the title.  The FindFirstSession function has a parameter for
// each of the search parameters supported by the query.     
//-----------------------------------------------------------------------------
BOOL FindFirstSession( GAME_TYPE Type, ULONGLONG Map,
                    ULONGLONG AvgPlayerRank,
                    XNKID *pSessionID, XNKEY *pKeyExchangeKey, XNADDR *pHostXnAddr )
{
    // The MatchSim wizard generates an class for each query defined by
    // the title.
    CFindSessionsQuery FindSessionsQuery;

    Print( L"Searching for sessions..." );
    HRESULT hr = FindSessionsQuery.Query( Type, Map, AvgPlayerRank );

   
    if( FAILED( hr ) ) Error( L"Session Search failed with 0x%x", hr );

    // Keep servicing the query until it completes.
    // The logon task, hLogonTask, must also be serviced in order 
    // to remain connected.  
    do
    {
        hr = XOnlineTaskContinue( hLogonTask );
        if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x", hr );
        hr = FindSessionsQuery.Process();
    } while( hr == XONLINETASK_S_RUNNING );

    if( FAILED( hr ) ) Error( L"Search Task Failed with 0x%x", hr );
 
    DWORD dwNumSessions = FindSessionsQuery.Results.Size();

    Print( L"Found %lu sessions", dwNumSessions );

    if( dwNumSessions > 0 )
    {
        // Since Qos support was specified when the CFindSessionsQuery class
        // was generated by the MatchSim tool, basic connectivity checks were
        // performed before the sessions were returned.  A title can now
        // display the sessions to the gamer, while doing additional
        // probing in order to obtain the actual bandwidth measurements.
        // The list should be updated as the results arrive.
   
        hr = FindSessionsQuery.Probe(); // Start full probing
        do
        {
            // Keep servicing the query until probing completes.
            // The logon task, hLogonTask, must also be serviced in order 
            // to remain connected.  As the probes complete, the 
            // 'pQosInfo' each result will change from NULL into a pointer
            // to an XNQOSINFO structure.  Probing is terminated using the
            // Cancel() method of the query object.
            hr = XOnlineTaskContinue( hLogonTask );
            if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x", hr );
            hr = FindSessionsQuery.Process();
        } while ( FindSessionsQuery.IsProbing() );
 
        Print(L"Found Session: '%s', Config Blob Length = %d\n", 
            FindSessionsQuery.Results[0].Name,  FindSessionsQuery.Results[0].Config.Length );
        *pSessionID      = FindSessionsQuery.Results[0].SessionID;
        *pKeyExchangeKey = FindSessionsQuery.Results[0].KeyExchangeKey;
        *pHostXnAddr     = FindSessionsQuery.Results[0].HostAddress;
        return TRUE;
    }

    return FALSE;
}




//-----------------------------------------------------------------------------
// Name: JoinSession()
// Desc: Join an existing game session.
//
// The JoinSession function demonstrates the steps required for
// a title to establish a secure connection to a host machine.
//-----------------------------------------------------------------------------
VOID JoinSession( XNKID& SessionID, XNKEY& KeyExchangeKey, XNADDR& HostAddress )
{
    // Save current session information
    JoinedSessionID      = SessionID;
    JoinedKeyExchangeKey = KeyExchangeKey;
    JoinedHostXnAddr     = HostAddress;
    
    // The session id and key-exchange key for the current session is
    // registered with the Xbox Secure Networking Library using the 
    // XNetRegisterKey function.  The XNetRegisterKey function informs 
    // the network stack to accept packets from other Xbox consoles 
    // that are using the same session key.
    INT iKeyRegistered = XNetRegisterKey( &JoinedSessionID,
        &JoinedKeyExchangeKey );
    assert( iKeyRegistered == NO_ERROR );
    ( VOID ) iKeyRegistered; // Avoid compiler warning
    
    // Network addresses on the Xbox are represented by an XNADDR.
    // The XNADDR structure contains the information required to completely
    // and uniquely identify an Xbox on either a  system-link network   
    // or on the Internet, even if that Xbox is communicating   
    // through network address translation ( NAT). The XNetXnAddrToInAddr  
    // function converts an Xbox XNADDR to an IP address that is usable  
    // by Winsock to communicate directly with that Xbox.
    // The translation requires the session key ID. Be aware that this IN_ADDR
    // is not a  real IP address. It has the format  0.x.y.z.   
    // If an IN_ADDR is transmitted to another Xbox or a PC, the target Xbox/PC
    // cannot use the IN_ADDR, because it is useful only in the context of the 
    // Xbox that converted the address. One way to think of the IN_ADDR is as a    
    // handle to the actual XNADDR. The Xbox SNL knows how to convert this
    // handle into the XNADDR.
    // The Internet address returned by XNetXnAddrToInAddr
    // is not valid outside of the context of the Xbox on which
    // XNetXnAddrToInAddr was called.  By contrast, the XNADDR, can be shared.

    INT err = XNetXnAddrToInAddr( &JoinedHostXnAddr, &JoinedSessionID,
                                 &JoinedHostInAddr );
    assert( err == 0 );
    ( VOID ) err; // Avoid compiler warning

    
    // Once a game session begins, the title should set the online 
    // notification state for each signed on user to indicate that they are
    // online, playing, and (if the game supports it) joinable.      
    SetSignedInUsersPresence(
        XONLINE_FRIENDSTATE_FLAG_ONLINE  |
        XONLINE_FRIENDSTATE_FLAG_PLAYING |
        XONLINE_FRIENDSTATE_FLAG_JOINABLE );

    Print( L"Joined Session" );
}




//-----------------------------------------------------------------------------
// Name: JoinInvitedSession()
// Desc: Join an accepted cross-title invitation
//-----------------------------------------------------------------------------
VOID JoinInvitedSession( XONLINE_ACCEPTED_GAMEINVITE & GameInvite )
{
    
    // After signing-in the invited users, the title joins the inviting session.
    // To do this, the title uses the inviting session id, 
    // GameInvite.InvitingFriend.sessionID, and queries the matchmaking service,
    // to obtain the information about that session.    
    XNADDR InviteHostAddress;
    XNKEY  InviteKeyExchangeKey;
    if( FindSessionByID( GameInvite.InvitingFriend.sessionID, 
                          &InviteKeyExchangeKey, &InviteHostAddress ) )
        JoinSession( GameInvite.InvitingFriend.sessionID, InviteKeyExchangeKey,
                     InviteHostAddress );
    else
        Error( L"Unable to Locate Inviting Session" );

}




//-----------------------------------------------------------------------------
// Name: PlayJoinedSession()
// Desc: Services the logon task for dwDuration seconds.
// This is the type of processing that would be done your game loop.
//-----------------------------------------------------------------------------
VOID PlayJoinedSession()
{
    DWORD dwTickStart = GetTickCount();
    const DWORD dwDuration = 15000; // 15 seconds
    while( ( GetTickCount() - dwTickStart ) < dwDuration )
    {
        HRESULT hr = XOnlineTaskContinue( hLogonTask );
        if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x", hr );
    }
}




//-----------------------------------------------------------------------------
// Name: LeaveJoinedSession()
// Desc: Leave a joined session.
//-----------------------------------------------------------------------------
VOID LeaveJoinedSession()
{
    // To leave a session, the title should notify the host console and
    // unregister the session id/key-exchange key pair with the networking
    // stack.  Since the signed-in users are no longer playing in a session, 
    // presence is set back to just "online".

    XNetUnregisterKey( &JoinedSessionID );
    SetSignedInUsersPresence( XONLINE_FRIENDSTATE_FLAG_ONLINE );
    
    Print( L"Left Session" );
}




//-----------------------------------------------------------------------------
// Name: GetAcceptedInviteUsers()
// Desc:  The GetAcceptedInviteUsers function takes a XONLINE_ACCEPTED_GAMEINVITE
// structure and populates an XONLINE_USER array, rgLogonUsers, with the   
// account information of each invited user that is found  in rgStoredUsers, 
// a list of user accounts found on the console and any attached memory units.
// The function returns the number of users who were copied into rgLogonUsers.
//-----------------------------------------------------------------------------
DWORD GetAcceptedInviteUsers( XONLINE_ACCEPTED_GAMEINVITE& GameInvite,
                              XONLINE_USER* rgStoredUsers,
                              DWORD         dwNumStoredUsers,
                              XONLINE_USER* rgLogonUsers )
{
    DWORD dwNumUsers = 0;

    ZeroMemory( rgLogonUsers, sizeof( XONLINE_USER ) * XONLINE_MAX_LOGON_USERS );
    
    for( DWORD i = 0; i < XONLINE_MAX_LOGON_USERS; ++i )
    {
        if( GameInvite.xuidLogonUsers[i].qwUserID ) // Check for valid user
        {
            // To locate the account information for an invited user, we find
            // the entry in the rgStoredUsers array with a matching XUID and
            // copy the acount information into rgLogonUser.  Since one or 
            // more of the invited users could have been guests, we must also 
            // copy the XUID as well in order to preserve the guest settings.
            
            for( DWORD j = 0; j != dwNumStoredUsers; ++j )
            {
                if( GameInvite.xuidLogonUsers[i].qwUserID ==
                    rgStoredUsers[j].xuid.qwUserID )
                {
                    rgLogonUsers[i]      = rgStoredUsers[j];
                    rgLogonUsers[i].xuid = GameInvite.xuidLogonUsers[i];
                    dwNumUsers++;
                    break;
                }
            }
        }
    }
    
    return dwNumUsers;
}




//-----------------------------------------------------------------------------
// Name: FindSessionByID()
// Desc: Retrieve information for an existing session.
//-----------------------------------------------------------------------------
BOOL FindSessionByID( XNKID& SessionID, 
                      XNKEY *pKeyExchangeKey, XNADDR *pHostXnAddr )
{
    CFindSessionByIDQuery FindQuery;

    // A custom query is used to retrieve the information
    // for a session with a particular id.  A title may
    // decide to use a query that returns additional 
    // attributes for display, etc.
    HRESULT hr = FindQuery.Query( *(ULONGLONG *) &SessionID );

    if( FAILED( hr ) ) Error( L"Search Task Failed with 0x%x", hr );

    // Keep servicing the query until it completes.
    // The logon task, hLogonTask, must also be serviced in order 
    // to remain connected.  
    do
    {
        hr = XOnlineTaskContinue( hLogonTask );
        if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x", hr );
        hr = FindQuery.Process();
    } while( hr == XONLINETASK_S_RUNNING );

    if( FAILED( hr ) ) Error( L"Search Task Failed with 0x%x", hr );
    
    DWORD dwNumSessions = FindQuery.Results.Size();
 
    if( dwNumSessions == 1 )
    {
        *pKeyExchangeKey = FindQuery.Results[0].KeyExchangeKey;
        *pHostXnAddr     = FindQuery.Results[0].HostAddress;
    }
    return dwNumSessions == 1;
}




//-----------------------------------------------------------------------------
// Name: SetSignedInUsersPresence()
// Desc: Set the online notification state for each signed-in player.
// This informs any of their friends of their online state.  The session id is
// also specified so that a friend can join the current game 
// (using XOnlineFriendsJoinGame).
// Note: A real title should also specify XONLINE_FRIENDSTATE_FLAG_VOICE for
// users with voice capability.
//-----------------------------------------------------------------------------
VOID SetSignedInUsersPresence( DWORD dwState )
{
    PXONLINE_USER pLogonUsers = XOnlineGetLogonUsers();
    for( DWORD i = 0; i < XONLINE_MAX_LOGON_USERS; ++i )
    {
        if( pLogonUsers[i].xuid.qwUserID !=0 ) // Check for valid user
        {
            if( !XOnlineIsUserGuest( pLogonUsers[i].xuid.dwUserFlags ) )
            {
                HRESULT hr = XOnlineNotificationSetState( i, dwState,
                    Session.SessionID, 0, NULL );
                assert( SUCCEEDED( hr ) );
                ( VOID ) hr;  // Avoid compiler warning
            }
        }
    }
}




//-----------------------------------------------------------------------------
// Name: Print()
// Desc: Send formatted output to the debug window
//-----------------------------------------------------------------------------
VOID __cdecl Print( const WCHAR* strFormat, ... )
{
    const int MAX_OUTPUT_STR = 512;
    WCHAR strBuffer[MAX_OUTPUT_STR];
    va_list pArglist;
    va_start( pArglist, strFormat );
    INT iChars= wvsprintfW( strBuffer, strFormat, pArglist );
    assert( iChars < MAX_OUTPUT_STR );
    OutputDebugStringW( L"\n*** SimpleMatch: " );
    OutputDebugStringW( strBuffer );
    OutputDebugStringW( L"\n\n" );
    ( VOID ) iChars;
    va_end( pArglist );
}




//-----------------------------------------------------------------------------
// Name: Error()
// Desc: Send formatted output to the debug window and boot back to the dash.
// It is used for reporting fatal errors.
//-----------------------------------------------------------------------------
VOID __cdecl Error( const WCHAR*strFormat, ... )
{
    const int MAX_OUTPUT_STR = 512;
    WCHAR strBuffer[MAX_OUTPUT_STR];
    va_list pArglist;
    va_start( pArglist, strFormat );
    INT iChars= wvsprintfW( strBuffer, strFormat, pArglist );
    assert( iChars < MAX_OUTPUT_STR );
    OutputDebugStringW( L"\n*** SimpleMatch: " );
    OutputDebugStringW( strBuffer );
    OutputDebugStringW( L"\n\n" );
    ( VOID ) iChars;
    va_end( pArglist );
    BootToDash( XLD_LAUNCH_DASHBOARD_MAIN_MENU );
}




//-----------------------------------------------------------------------------
// Name: UIMsg()
// Desc: Display a recommended user interface message
//       See Xbox_Terminology_List.xls for additional information.
//-----------------------------------------------------------------------------
VOID UIMsg( const WCHAR* strText )
{
    OutputDebugStringW( L"\n*** SimpleMatch: UI Message:\n" );
    OutputDebugStringW( strText );
    OutputDebugStringW( L"\n" );
}




//-----------------------------------------------------------------------------
// Name: BootToDash()
// Desc: Boot back into either the main or online dashes
//-----------------------------------------------------------------------------
VOID BootToDash( DWORD dwReason )
{
    LD_LAUNCH_DASHBOARD ld;
    ZeroMemory( &ld, sizeof( ld ) );
    ld.dwReason = dwReason;
    XLaunchNewImage( NULL, PLAUNCH_DATA( &ld ) );
    // XLaunchNewImage should never return
    assert( FALSE );
}


