// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 7UL

#define resource_stonehengeground512_OFFSET 128UL
#define resource_leaf_OFFSET 148UL
#define resource_sun_OFFSET 168UL
#define resource_flare1_OFFSET 188UL
#define resource_flare2_OFFSET 208UL
#define resource_flare3_OFFSET 228UL
#define resource_flare4_OFFSET 248UL
