// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 7UL

#define resource_Ground_OFFSET 112UL
#define resource_Exp1_OFFSET 132UL
#define resource_Exp1d_OFFSET 152UL
#define resource_Exp2_OFFSET 172UL
#define resource_Exp2d_OFFSET 192UL
#define resource_Exp3_OFFSET 212UL
#define resource_Exp3d_OFFSET 232UL
