//
// XactSounds.h - generated by xactbld from the XACT project (.xap).
// Do not edit.
//

#ifndef __XACTSOUNDS_H__
#define __XACTSOUNDS_H__

// Sound bank "Markers" cue indices
typedef enum XACT_SOUNDBANK_MARKERS
{
    XACT_SOUNDBANK_MARKERS_XACT_MARKER = 0,
    XACT_SOUNDBANK_MARKERS_CUE_COUNT = 1,
} XACT_SOUNDBANK_MARKERS;

// Wave bank "Markers" entry indices
typedef enum XACT_WAVEBANK_MARKERS
{
    XACT_WAVEBANK_MARKERS_XACT_MARKER = 0,
    XACT_WAVEBANK_MARKERS_ENTRY_COUNT = 1,
} XACT_WAVEBANK_MARKERS;

#endif
