// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 7UL

#define resource_Light_OFFSET 160UL
#define resource_SkyBoxXP_OFFSET 180UL
#define resource_SkyBoxXN_OFFSET 200UL
#define resource_SkyBoxYP_OFFSET 220UL
#define resource_SkyBoxYN_OFFSET 240UL
#define resource_SkyBoxZP_OFFSET 260UL
#define resource_SkyBoxZN_OFFSET 280UL
