// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 9UL

#define resource_Light_OFFSET 208UL
#define resource_SkyBoxXP_OFFSET 228UL
#define resource_SkyBoxXN_OFFSET 248UL
#define resource_SkyBoxYP_OFFSET 268UL
#define resource_SkyBoxYN_OFFSET 288UL
#define resource_SkyBoxZP_OFFSET 308UL
#define resource_SkyBoxZN_OFFSET 328UL
#define resource_StoneHen_OFFSET 348UL
#define resource_StoneHea_OFFSET 368UL
