// Automatically generated by the bundler tool from rstest.rdf

#define rstest_NUM_RESOURCES 3UL

#define rstest_SCREEN_OFFSET 0UL
#define rstest_CURRENTPLAYERSIMAGEACTIVE_OFFSET 20UL
#define rstest_DEPARTEDPLAYERSIMAGEACTIVE_OFFSET 40UL
