// Automatically generated by the bundler tool from resource2.rdf

#define resource2_NUM_RESOURCES 11UL

#define resource2_T0_OFFSET 144UL
#define resource2_T1_OFFSET 164UL
#define resource2_T2_OFFSET 184UL
#define resource2_T3_OFFSET 204UL
#define resource2_T4_OFFSET 224UL
#define resource2_T5_OFFSET 244UL
#define resource2_T6_OFFSET 264UL
#define resource2_T7_OFFSET 284UL
#define resource2_T8_OFFSET 304UL
#define resource2_T9_OFFSET 324UL
#define resource2_QuadsVB_OFFSET 344UL
