// Automatically generated by the bundler tool from resource0.rdf

#define resource0_NUM_RESOURCES 11UL

#define resource0_T0_OFFSET 144UL
#define resource0_T1_OFFSET 164UL
#define resource0_T2_OFFSET 184UL
#define resource0_T3_OFFSET 204UL
#define resource0_T4_OFFSET 224UL
#define resource0_T5_OFFSET 244UL
#define resource0_T6_OFFSET 264UL
#define resource0_T7_OFFSET 284UL
#define resource0_T8_OFFSET 304UL
#define resource0_T9_OFFSET 324UL
#define resource0_QuadsVB_OFFSET 344UL
