// Automatically generated by the bundler tool from resource1.rdf

#define resource1_NUM_RESOURCES 11UL

#define resource1_T0_OFFSET 144UL
#define resource1_T1_OFFSET 164UL
#define resource1_T2_OFFSET 184UL
#define resource1_T3_OFFSET 204UL
#define resource1_T4_OFFSET 224UL
#define resource1_T5_OFFSET 244UL
#define resource1_T6_OFFSET 264UL
#define resource1_T7_OFFSET 284UL
#define resource1_T8_OFFSET 304UL
#define resource1_T9_OFFSET 324UL
#define resource1_QuadsVB_OFFSET 344UL
