// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 3UL

#define resource_Seafloor_OFFSET 80UL
#define resource_BiHull_OFFSET 100UL
#define resource_Wings_OFFSET 120UL
