// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 3UL

#define resource_MoonPoly1_OFFSET 64UL
#define resource_MoonPoly2_OFFSET 84UL
#define resource_MoonColor_OFFSET 104UL
