//------------------------------------------------------------------------------
//
// Xbox Competitions Implementations
// Generated by XLAST Competitions Version 1.00.5937.1 at Mon, Mar 22, 2004 13:57
// Title ID: ffff4005
// Project Name: comps
//------------------------------------------------------------------------------
#include "comps.h"




//------------------------------------------------------------------------------
// Implementation for the SE competition type
//------------------------------------------------------------------------------
CONST WCHAR wszDefaultSEDisplayName[] = L"";
CONST WCHAR wszDefaultSEDescription[] = L"";
CONST WCHAR wszDefaultSEURL[] = L"";


CONST XONLINE_COMP_SINGLE_ELIMINATION_ATTRIBUTES SECreationStruct =
{
             0,   // dwPrivateSlots
             0,   // dwPublicSlots
    0x2,       // dwMinimumPlayers
             0,   // ftRegistrationOpen
             0,   // ftRegistrationClose
             0,   // ftCompetitionStart
             0,   // ftRoundOneStart
             0,   // ftRoundOneEnd
    0x60,       // dwMatchReminderAdvanceMinutes
    XONLINE_COMP_INTERVAL_MINUTE,           // Interval
    30,           // UnitOrMask
    FALSE,           // fTeamsCompetition
             0,   // dwTeamSize
};

CONST XONLINE_ATTRIBUTE_SPEC CSECompetitionsAvailableCompetitionsQueryResults::ResultSpec[SE_COMPETITIONS_AVAILABLE_COMPETITIONS_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER, sizeof(ULONGLONG) }, // entity_id
    { 0x80010003, sizeof(ULONGLONG) }, // att_comp_start
    { 0x80010005, sizeof(ULONGLONG) }, // att_round_frequency
    { 0x80010006, sizeof(ULONGLONG) }, // att_round_interval
    { 0x80010007, sizeof(ULONGLONG) }, // att_round_day_mask
    { 0x8001000c, sizeof(ULONGLONG) }, // att_round_one_start
    { 0x8001000d, sizeof(ULONGLONG) }, // att_round_one_end
    { 0x80010010, sizeof(ULONGLONG) }, // att_is_team_comp
    { 0x80010011, sizeof(ULONGLONG) }, // att_team_size
    { 0x80010012, sizeof(ULONGLONG) }, // att_max_public_slots
    { 0x80010013, sizeof(ULONGLONG) }, // att_max_private_slots
    { 0x80010018, sizeof(ULONGLONG) }, // att_public_entrants
    { 0x80010019, sizeof(ULONGLONG) }, // att_private_entrants
    { 0x8001001d, sizeof(ULONGLONG) }, // att_status
    { 0x00010001, sizeof(ULONGLONG) }, // att_map
    { 0x00110002,  200 }, // att_name
    { 0x00210003,  400 }, // att_icon
};

CONST XONLINE_ATTRIBUTE_SPEC CSECompetitionsCompetitionsICreatedQueryResults::ResultSpec[SE_COMPETITIONS_COMPETITIONS_I_CREATED_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER, sizeof(ULONGLONG) }, // entity_id
    { 0x80010003, sizeof(ULONGLONG) }, // att_comp_start
    { 0x80010005, sizeof(ULONGLONG) }, // att_round_frequency
    { 0x80010006, sizeof(ULONGLONG) }, // att_round_interval
    { 0x80010007, sizeof(ULONGLONG) }, // att_round_day_mask
    { 0x8001000c, sizeof(ULONGLONG) }, // att_round_one_start
    { 0x8001000d, sizeof(ULONGLONG) }, // att_round_one_end
    { 0x80010010, sizeof(ULONGLONG) }, // att_is_team_comp
    { 0x80010011, sizeof(ULONGLONG) }, // att_team_size
    { 0x80010012, sizeof(ULONGLONG) }, // att_max_public_slots
    { 0x80010013, sizeof(ULONGLONG) }, // att_max_private_slots
    { 0x80010018, sizeof(ULONGLONG) }, // att_public_entrants
    { 0x80010019, sizeof(ULONGLONG) }, // att_private_entrants
    { 0x8001001d, sizeof(ULONGLONG) }, // att_status
    { 0x00010001, sizeof(ULONGLONG) }, // att_map
    { 0x00110002,  200 }, // att_name
    { 0x00210003,  400 }, // att_icon
};

CONST XONLINE_ATTRIBUTE_SPEC CSECompetitionsCompetitionDetailsQueryResults::ResultSpec[SE_COMPETITIONS_COMPETITION_DETAILS_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER, sizeof(ULONGLONG) }, // entity_id
    { 0x80000001, sizeof(ULONGLONG) }, // owner_id
    { 0x81100001,  16 }, // owner_gamertag
    { 0x80010003, sizeof(ULONGLONG) }, // att_comp_start
    { 0x80010004, sizeof(ULONGLONG) }, // att_comp_cleanup
    { 0x80010005, sizeof(ULONGLONG) }, // att_round_frequency
    { 0x80010006, sizeof(ULONGLONG) }, // att_round_interval
    { 0x80010007, sizeof(ULONGLONG) }, // att_round_day_mask
    { 0x80010010, sizeof(ULONGLONG) }, // att_is_team_comp
    { 0x80010011, sizeof(ULONGLONG) }, // att_team_size
    { 0x8001001a, sizeof(ULONGLONG) }, // att_reminder_min
    { 0x80010008, sizeof(ULONGLONG) }, // att_rounds
    { 0x80010009, sizeof(ULONGLONG) }, // att_current_round
    { 0x8001000a, sizeof(ULONGLONG) }, // att_current_round_start
    { 0x8001000b, sizeof(ULONGLONG) }, // att_current_round_end
    { 0x80010018, sizeof(ULONGLONG) }, // att_public_entrants
    { 0x80010019, sizeof(ULONGLONG) }, // att_private_entrants
    { 0x8001001d, sizeof(ULONGLONG) }, // att_status
    { 0x80010020, sizeof(ULONGLONG) }, // att_leaderboard_id0
    { 0x80010021, sizeof(ULONGLONG) }, // att_leaderboard_id1
    { 0x80010022, sizeof(ULONGLONG) }, // att_leaderboard_id2
    { 0x00010001, sizeof(ULONGLONG) }, // att_map
    { 0x00110002,  200 }, // att_name
    { 0x00210003,  400 }, // att_icon
};

CONST XONLINE_ATTRIBUTE_SPEC CSEEntrantsMyCompetitionsQueryResults::ResultSpec[SE_ENTRANTS_MY_COMPETITIONS_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER, sizeof(ULONGLONG) }, // entity_id
    { 0x80010000, sizeof(ULONGLONG) }, // att_comp_id
    { 0x8001001d, sizeof(ULONGLONG) }, // att_comp_status
    { 0x80020001, sizeof(ULONGLONG) }, // att_status
    { 0x80020003, sizeof(ULONGLONG) }, // att_current_round
    { 0x80020007, sizeof(ULONGLONG) }, // att_current_event
    { 0x80020008, sizeof(ULONGLONG) }, // att_current_start
    { 0x80020009, sizeof(ULONGLONG) }, // att_sort
};

CONST XONLINE_ATTRIBUTE_SPEC CSEEntrantsCompetitionStandingsQueryResults::ResultSpec[SE_ENTRANTS_COMPETITION_STANDINGS_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER, sizeof(ULONGLONG) }, // entity_id
    { 0x80020000, sizeof(ULONGLONG) }, // att_puid
    { 0x81120000,  16 }, // gamertag
    { 0x80020001, sizeof(ULONGLONG) }, // att_status
    { 0x80020003, sizeof(ULONGLONG) }, // att_current_round
    { 0x80020007, sizeof(ULONGLONG) }, // att_current_event
    { 0x80020008, sizeof(ULONGLONG) }, // att_current_start
    { 0x80020009, sizeof(ULONGLONG) }, // att_sort
};

CONST XONLINE_ATTRIBUTE_SPEC CSEEventsTopologyQueryResults::ResultSpec[SE_EVENTS_TOPOLOGY_NUM_RESULT_ATTRS] =
{
    { X_ATTRIBUTE_DATATYPE_INTEGER, sizeof(ULONGLONG) }, // entity_id
    { 0x80030001, sizeof(ULONGLONG) }, // topology_id
    { 0x80030002, sizeof(ULONGLONG) }, // round
    { 0x80030003, sizeof(ULONGLONG) }, // start
    { 0x80030006, sizeof(ULONGLONG) }, // next_entity
    { 0x80030007, sizeof(ULONGLONG) }, // next_start
    { 0x80030008, sizeof(ULONGLONG) }, // player1
    { 0x81130008,  16 }, // p1_gamertag
    { 0x8003000b, sizeof(ULONGLONG) }, // player2
    { 0x8113000b,  16 }, // p2_gamertag
    { 0x8003000e, sizeof(ULONGLONG) }, // winner
    { 0x8003000f, sizeof(ULONGLONG) }, // loser
    { 0x00030001, sizeof(ULONGLONG) }, // att_map
    { 0x00130002,  200 }, // att_name
    { 0x00230003,  400 }, // att_icon
};

