//
// XACTSounds.h - generated by xactbld from the XACT project (.xap).
// Do not edit.
//

#ifndef __XACTSOUNDS_H__
#define __XACTSOUNDS_H__

// Sound categories
typedef enum XACT_CATEGORY
{
    XACT_CATEGORY_SFX = 0,
    XACT_CATEGORY_BGMUSIC = 1,
    XACT_CATEGORY_COUNT = 2,
} XACT_CATEGORY;

// Sound bank "game" cue indices
typedef enum XACT_SOUNDBANK_GAME
{
    XACT_SOUNDBANK_GAME_MUSIC = 0,
    XACT_SOUNDBANK_GAME_HONK = 1,
    XACT_SOUNDBANK_GAME_CRASH = 2,
    XACT_SOUNDBANK_GAME_CUE_COUNT = 3,
} XACT_SOUNDBANK_GAME;

// Wave bank "game" entry indices
typedef enum XACT_WAVEBANK_GAME
{
    XACT_WAVEBANK_GAME_HONKA = 0,
    XACT_WAVEBANK_GAME_CRASH3 = 1,
    XACT_WAVEBANK_GAME_CRASH1 = 2,
    XACT_WAVEBANK_GAME_CRASH2 = 3,
    XACT_WAVEBANK_GAME_ENTRY_COUNT = 4,
} XACT_WAVEBANK_GAME;

#endif
