// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 6UL

#define resource_Ceiling_OFFSET 144UL
#define resource_Floor_OFFSET 164UL
#define resource_EastWall_OFFSET 184UL
#define resource_WestWall_OFFSET 204UL
#define resource_NorthWall_OFFSET 224UL
#define resource_SouthWall_OFFSET 244UL
