// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 10UL

#define resource_SkyBoxXN_OFFSET 224UL
#define resource_SkyBoxXP_OFFSET 244UL
#define resource_SkyBoxYN_OFFSET 264UL
#define resource_SkyBoxYP_OFFSET 284UL
#define resource_SkyBoxZN_OFFSET 304UL
#define resource_SkyBoxZP_OFFSET 324UL
#define resource_Fireground_OFFSET 344UL
#define resource_FlameColor_OFFSET 364UL
#define resource_FireNoise_OFFSET 384UL
#define resource_NoiseAlpha_OFFSET 404UL
