// Automatically generated by the bundler tool from Resource.rdf

#define Resource_NUM_RESOURCES 4UL

#define Resource_Fairway_OFFSET 80UL
#define Resource_Football_OFFSET 100UL
#define Resource_GrassStrip_OFFSET 120UL
#define Resource_Grass_OFFSET 140UL
