//-----------------------------------------------------------------------------
// File: SimpleConnect.cpp
//
// Desc: Illustrates online matchmaking on Xbox using the classes generated by
// the MatchSim tool. Game titles use the Xbox Live Matchmaking Service to  
// exchange information about currently running sessions. An Xbox title that 
// is hosting an online-game session uses the API to provide the service with 
// information about its session. Other Xbox systems can then use the API to  
// query the service to find appropriate online-game sessions to join.
//
// Hist: 02.05.03 - New for April release 
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------

#include <xtl.h>                  
#include <xonline.h>              
#include <assert.h> 
#include "match.h"

//-----------------------------------------------------------------------------
// Prototypes
//-----------------------------------------------------------------------------
BOOL FindSessionByID( XNKID& SessionID, 
                      XNKEY *pKeyExchangeKey, XNADDR *pHostXnAddr );
VOID HostSession();
VOID CreateSession();
BOOL FindFirstSession( XNKID *pSessionID, XNKEY *pKeyExchangeKey, XNADDR *pHostXnAddr );


VOID ServiceHostedGameSession();
BOOL SignIn( XONLINE_USER*pLogonUsers );
VOID __cdecl Print( const WCHAR*strFormat, ... );
VOID __cdecl Error( const WCHAR*strFormat, ... );
VOID UIMsg( const WCHAR* strText );
VOID BootToDash( DWORD dwReason );




//-----------------------------------------------------------------------------
// Global variables
//-----------------------------------------------------------------------------

// Each advertised session has a unique  session id and a
// session key-exchange key assigned by the Xbox Live matchmaking service.       
// This sample uses the JoinedSessionID variable to store the session id for the
// current session.  The JoinedKeyExchangeKey variable is used to store the 
// key-exchange key (for secure communications) for the current session.

XNKID JoinedSessionID;
XNKEY JoinedKeyExchangeKey;

// The host Xbox Network Address (XNADDR) and Internet Address (IN_ADDR)
// are stored in JoinedHostXnAddr and JoinedHostInAddr respectively.
XNADDR  JoinedHostXnAddr;
IN_ADDR JoinedHostInAddr;

// The currently hosted session. This class is generated by the MatchSim
// tool.
CSession Session;

// When a title successfully signs in, a task handle is returned that must be
// serviced by the title for the duration of the Xbox Live Session.  The
// global  hLogonTask is used to store this task handle.
XONLINETASK_HANDLE hLogonTask;




//-----------------------------------------------------------------------------
// Name: main()
// Desc: Entry point to the program.
//
// The main function demonstrates key matchmaking tasks:
// *   Checking for, and joining, an existing accepted game invitation.    
// *   Creating (advertising) a new game session.
// *   Updating an existing game session.
// *   Deleting a game session once it is no longer needed.
// *   Querying for game sessions.
// This sample does not have a user-interface and does minimalistic error
// handling.   
//-----------------------------------------------------------------------------
VOID __cdecl main()
{
    OutputDebugStringA( "SAMPLE: SimpleConnect: main\n" );

    XONLINE_USER StoredUsers[XONLINE_MAX_STORED_ONLINE_USERS];
    DWORD dwNumStoredUsers;
    XONLINE_USER LogonUsers[XONLINE_MAX_LOGON_USERS]= {0};
    
   // Initialize Input Devices this is required for account enumeration on 
    // Memory Units
    XInitDevices( 0, NULL );
    
    // Before we can enumerate user accounts on any attached Memory Units, we
    // must first allow them sufficient time to mount. 
    while( XGetDeviceEnumerationStatus() == XDEVICE_ENUMERATION_BUSY ){}

    // Before using the XBox Live APIs, a title  must first call XOnlineStartup.     
    // XOnlineStartup will automatically call XNetStartup and WSAStartup with
    // reasonable defaults in order to initialize the Xbox Secure Networking Library and
    // Winsock respectively. If you require special parameters for those functions
    // your title should can call them first before calling
    // XOnlineStartup.
    HRESULT hr = XOnlineStartup( NULL );
    assert( SUCCEEDED( hr ) );

    // The XOnlineGetUsers function will enumerate both the hard disk and any     
    // attached memory units looking for user accounts.

    hr = XOnlineGetUsers( StoredUsers, &dwNumStoredUsers );
    assert( SUCCEEDED( hr ) );
    
    // If no accounts were found, a tile must give the player the  option of 
    // going to the online dash to create new account. In addition, it is
    // possible for a player to actually insert/remove an MU while
    // the title account selection UI is active.  A title must
    // call XOnlineGetUsers repeatedly to account for this.
    // For demonstration purposes, we just boot to the account signup section
    // of the online dash if no accounts are found.

    if( dwNumStoredUsers == 0 )
    {
        Print( L"No user accounts found." );
        BootToDash( XLD_LAUNCH_DASHBOARD_NEW_ACCOUNT_SIGNUP );
    }
    
    // After initialization, a title should check for an accepted game     
    // invitation. An accepted game invitation can exist for one of two reasons:
    // 1. A gamer on this console was playing another title and accepted an    
    //    invitation (from a friend) to join a session in this title  
    //    (via XOnlineFriendsAnswerGameInvite).
    // 2. A gamer on this console, who was not playing this title, decided to
    //    join (using XOnlineFriendsJoinGame) the session of a friend
    // who was playing this title.
    //
    // The XOnlineFriendsGetAcceptedGameInvite function is used to check
    // for an accepted cross-title game invitation.    
    // XOnlineFriendsGetAcceptedGameInvite return S_OK if there was
    // an  invitation, and fill an XONLINE_ACCEPTED_GAMEINVITE structure
    // with information about it.  If no accepted game invitation exists,
    // the function returns S_FALSE.
    
   
    // Sign in the first user account and try to find an
    // existing session to join.
    LogonUsers[0] = StoredUsers[0];
        
    if( !SignIn( LogonUsers ) )
       BootToDash( XLD_LAUNCH_DASHBOARD_MAIN_MENU );
    
    // Locate a session using the FindFirstSession function, 
    // specifying that a SLAYER match on map 4, with an average player
    // rank of 20 (or better) is desired.
    // The first session found is returned.
    XNKID FoundSessionID;
    XNKEY FoundExchangeKey;
    XNADDR FoundHostAddr;
    IN_ADDR HostInAddr;
    DWORD dwStatus;

    if( FindFirstSession( &FoundSessionID, &FoundExchangeKey, &FoundHostAddr ) )
    {
        Print( L"Initiating NetConnect" );
        
        // register the key
        XNetRegisterKey( &FoundSessionID, &FoundExchangeKey );
        
        // get the in_addr- if the security association is ever lost, we have to call this again        
        XNetXnAddrToInAddr( &FoundHostAddr, &FoundSessionID, &HostInAddr );
        
        // the status of the connection with the ip will be idle at first

        assert( XNetGetConnectStatus( HostInAddr ) == XNET_CONNECT_STATUS_IDLE );

        // kick off security exchange - this also happens if you send any packet, but it's best
        // to do it manually with XNetConnect, so you know you have a good connection before
        // sending and buffering data

        if ( XNetConnect( HostInAddr ) != 0 )
            Error(L"Could not connect to host - invalid INAddr");
                      
        // Here you'd display your UI for connecting to a host
        Print( L"Waiting for security exchange" );
        
        do 
        {
            // in all loops we have to pump the login task
            hr = XOnlineTaskContinue( hLogonTask );
            if ( FAILED( hr )) Error( L"Logon task failed with 0x%x", hr );
        
            // check the status
            dwStatus = XNetGetConnectStatus( HostInAddr );
        } while ( dwStatus == XNET_CONNECT_STATUS_PENDING );
        
        if ( dwStatus == XNET_CONNECT_STATUS_CONNECTED )
        {
            Print( L"Connected - security exchange successful" );        
        }
        else
        {
            Error( L"Could not connect to host- couldn't form security association" );
        }
        
        // Now you start your client-host handshaking, and main game loop
        // .
        // .
        // .

        // Periodically you will want to call XNetGetConnectStatus

        Print( L"Checking for lost security association" );
        dwStatus = XNetGetConnectStatus( HostInAddr );

        if ( dwStatus == XNET_CONNECT_STATUS_LOST )
        {
            // if we lost the security connection, we have to re-establish it
            // first we get a new in-addr
            XNetXnAddrToInAddr( &FoundHostAddr, &FoundSessionID, &HostInAddr );

            // start the security exchange
            if ( XNetConnect( HostInAddr ) != 0 )
                Error(L"Could not connect to host - invalid INAddr");
            
            // again loop while we try to reconnect  (update some UI here)
            do 
            {
                // in all loops we have to pump the login task
                hr = XOnlineTaskContinue( hLogonTask );
                if ( FAILED( hr )) Error( L"Logon task failed with 0x%x", hr );
        
                dwStatus = XNetGetConnectStatus( HostInAddr );
            } while ( dwStatus == XNET_CONNECT_STATUS_PENDING );

            if ( dwStatus == XNET_CONNECT_STATUS_CONNECTED )
            {
                Print( L"Reconnected" );        
            }
            else
            {
                Error( L"Lost connection to host" );
            }
        
        }  

        // .
        // .
        // .
    }
    else
    {
        // No sessions were found, so host one.
        // We don't actually do anything but maintain the matchmaking session here-
        // all we care about is doing security exchange for this sample

        HostSession();
    }

    Print( L"Signing off..." );

    // A title signs off users by calling XOnlineTaskClose on the
    // task handle returned by XOnlineLogon.  Another situation in which users
    // are signed off is if the Xbox Live Service realizes the task handle 
    // returned by XOnlineLogon is not being serviced by the title (
    // e.g. the user turned the console off).
    
    XOnlineTaskClose( hLogonTask );
    
    // When a title is through with the XBox Live APIs, it can call XOnlineCleanup
    // to perform final cleanup for the online functions.
    OutputDebugStringA( "SAMPLE: SimpleConnect: exit\n" );
    XOnlineCleanup();
    
    BootToDash( XLD_LAUNCH_DASHBOARD_MAIN_MENU );
}



//----------------------------------------------------------------------------------
// The following functions do session management, since we need to find a host to 
// XNetConnect to.  For more information on matchmaking, see the matchmaking
// samples.  ( A quick and dirty version is implemeneted here )
//----------------------------------------------------------------------------------


//-----------------------------------------------------------------------------
// Name: HostSession()
// Desc: Host a session. 
//-----------------------------------------------------------------------------
VOID HostSession()
{
    // host a sample session to XNetConnect to.  

    // Create the new session
    CreateSession();
    
    // we're going to loop indefinately with the hosted session
    Print(L"Hosting a session.. run SimpleConnect on another Xbox development kit");
    Print(L"Reboot to cancel out of hosting");

    // this function will never return in this sample; for more information
    // on matchmaking, see the matchmaking samples.
    // This will continue until we lose connection to the match server or logon
    // task, and then end
    
    HRESULT hr;

    do 
    {
        hr = XOnlineTaskContinue( hLogonTask );
        if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x",   hr );
        hr =  Session.Process();        
    }  
    while( !FAILED( hr ) );
}

//-----------------------------------------------------------------------------
// Name: CreateSession()
// Desc: Advertise a new game session.
//
// The CreateSession function initializes the session attributes and then calls
// CSession::Create to create the new session.   
// Initially, one public player slot is used.  
//-----------------------------------------------------------------------------
VOID CreateSession()
{  
    // Set the filled/opened public/private slots for this session -
    // in this case it's just some data so that the session gets advertised
    Session.PublicFilled  = 1;
    Session.PublicOpen     = 1;
    Session.PrivateFilled = 0;
    Session.PrivateOpen    = 0;

    // set the name of the session
    Session.Name = L"The Pit"; // Same as Session.SetName( L"The Pitt" )  
    
    Print( L"Creating new Session" );
    
    HRESULT hr = Session.Create();

    if( hr != S_OK ) Error( L"Session Creation failed with 0x%x", hr );

    // In order to complete the creation process, the
    // session object should be serviced using for as long as 
    // XONLINETASK_S_RUNNING is returned.  The logon task, hLogonTask,
    // must also be serviced in order to remain connected.  
    
    do
    {
        hr = XOnlineTaskContinue( hLogonTask );
        if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x", hr );
        hr = Session.Process();
    } while( hr == XONLINETASK_S_RUNNING );
    
    if( hr != XONLINETASK_S_SUCCESS )
        Error( L"Creation Task Failed with 0x%x", hr );
    
    Print( L"Session Created" );

    Session.QosResponse = B( 5, "HELLO" );
    Session.Listen( TRUE, 16000 );
}


//-----------------------------------------------------------------------------
// Name: FindFirstSession()
// Desc: Execute the custom query for this sample looking for existing 
//       sessions.
//-----------------------------------------------------------------------------
BOOL FindFirstSession( XNKID *pSessionID, XNKEY *pKeyExchangeKey, XNADDR *pHostXnAddr )
{
    CQuickmatchQuery QuickMatchQuery;

    Print( L"Searching for sessions..." );

    QuickMatchQuery.Clear();

    HRESULT hr = QuickMatchQuery.Query();

    // Keep servicing the query until it completes.
    // The logon task, hLogonTask, must also be serviced in order 
    // to remain connected.  
    do
    {
        hr = XOnlineTaskContinue( hLogonTask );
        if( FAILED( hr ) ) Error( L"Logon Task Failed with 0x%x", hr );
        hr = QuickMatchQuery.Process();
    } while( hr == XONLINETASK_S_RUNNING );

    if( FAILED( hr ) ) Error( L"Search Task Failed with 0x%x", hr );
 
    // didn't find any results
    if ( QuickMatchQuery.Results.Size() == 0 ) 
        return FALSE;
 
    *pSessionID      = QuickMatchQuery.Results[0].SessionID;
    *pKeyExchangeKey = QuickMatchQuery.Results[0].KeyExchangeKey;
    *pHostXnAddr     = QuickMatchQuery.Results[0].HostAddress;
    
    return TRUE;
}

//-----------------------------------------------------------------------------
// Name: Print()
// Desc: Send formatted output to the debug window
//-----------------------------------------------------------------------------
VOID __cdecl Print( const WCHAR* strFormat, ... )
{
    const int MAX_OUTPUT_STR = 512;
    WCHAR strBuffer[MAX_OUTPUT_STR];
    va_list pArglist;
    va_start( pArglist, strFormat );
    INT iChars= wvsprintfW( strBuffer, strFormat, pArglist );
    assert( iChars < MAX_OUTPUT_STR );
    OutputDebugStringW( L"\n*** SimpleConnect: " );
    OutputDebugStringW( strBuffer );
    OutputDebugStringW( L"\n\n" );
    ( VOID ) iChars;
    va_end( pArglist );
}




//-----------------------------------------------------------------------------
// Name: Error()
// Desc: Send formatted output to the debug window and boot back to the dash.
// It is used for reporting fatal errors.
//-----------------------------------------------------------------------------
VOID __cdecl Error( const WCHAR*strFormat, ... )
{
    const int MAX_OUTPUT_STR = 512;
    WCHAR strBuffer[MAX_OUTPUT_STR];
    va_list pArglist;
    va_start( pArglist, strFormat );
    INT iChars= wvsprintfW( strBuffer, strFormat, pArglist );
    assert( iChars < MAX_OUTPUT_STR );
    OutputDebugStringW( L"\n*** SimpleConnect: " );
    OutputDebugStringW( strBuffer );
    OutputDebugStringW( L"\n\n" );
    ( VOID ) iChars;
    va_end( pArglist );
    BootToDash( XLD_LAUNCH_DASHBOARD_MAIN_MENU );
}




//-----------------------------------------------------------------------------
// Name: UIMsg()
// Desc: Display a recommended user interface message
//       See Xbox_Terminology_List.xls for additional information.
//-----------------------------------------------------------------------------
VOID UIMsg( const WCHAR* strText )
{
    OutputDebugStringW( L"\n*** SimpleConnect: UI Message:\n" );
    OutputDebugStringW( strText );
    OutputDebugStringW( L"\n" );
}




//-----------------------------------------------------------------------------
// Name: BootToDash()
// Desc: Boot back into either the main or online dashes
//-----------------------------------------------------------------------------
VOID BootToDash( DWORD dwReason )
{
    LD_LAUNCH_DASHBOARD ld;
    ZeroMemory( &ld, sizeof( ld ) );
    ld.dwReason = dwReason;
    XLaunchNewImage( NULL, PLAUNCH_DATA( &ld ) );
    // XLaunchNewImage should never return
    assert( FALSE );
}


