// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 3UL

#define resource_TerrainTexture_OFFSET 64UL
#define resource_undergrass_OFFSET 84UL
#define resource_leaf2_OFFSET 104UL
