//-----------------------------------------------------------------------------
// File: SpeechRecognition.cpp
//
// Desc: This sample demonstrates how to use the new Speech Recognition
//       features in the new High-Level Voice library (xhv.lib)
//
//       Note that in this early release of the SR functionality, only one
//       vocabulary at a time can be active.
//
// Hist: 01.09.03 - New for the February 2003 XDK Release
//       03.14.03 - Added support for multiple languages
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------
#include <xbapp.h>
#include <xbfont.h>
#include <xbhelp.h>
#include <xgraphics.h>
#include <xonline.h>
#include <xhv.h>
#include "WordList.h"

// This header file is generated by the BuildSpeechRecBank tool
// For this sample, we're assuming that each language has the
// same vocabularies with the same vocab indices
#include "SampleSRBank_en.h"




//-----------------------------------------------------------------------------
// Callouts for labelling the gamepad on the help screen
//-----------------------------------------------------------------------------
XBHELP_CALLOUT g_HelpCallouts[] = 
{
    { XBHELP_BACK_BUTTON,  XBHELP_PLACEMENT_1, L"Display help" },
    { XBHELP_A_BUTTON,     XBHELP_PLACEMENT_2, L"Enter\nrecognition\nmode" },
    { XBHELP_B_BUTTON,     XBHELP_PLACEMENT_2, L"Next\nvocabulary" },
    { XBHELP_RIGHTSTICK,   XBHELP_PLACEMENT_2, L"Adjust confidence\nthreshold" },
    { XBHELP_Y_BUTTON,     XBHELP_PLACEMENT_1, L"Next language" },
    { XBHELP_X_BUTTON,     XBHELP_PLACEMENT_2, L"Toggle vocabulary\non/off" },
};
static const DWORD NUM_HELP_CALLOUTS = sizeof(g_HelpCallouts) / sizeof(g_HelpCallouts[0]);

// The LANGUAGE struct allows us to specify language-specific
// speech recognition data.  
struct LANGUAGE
{
    WCHAR*  strLanguage;        // Name of language
    CHAR*   strXSRFilename;     // XSR file to load
    CHAR*   strWordFilename;    // Vocabulary TXT file
    CHAR*   strFontFilename;    // Font for rendering words
};

static const LANGUAGE g_aLanguages[] = 
{
    { (WCHAR*)L"English",       (CHAR*)"SampleSRBank_en.xsr", (CHAR*)"SampleSRBank_en.txt", (CHAR*)"font.xpr" },
    { (WCHAR*)L"Japanese",      (CHAR*)"SampleSRBank_jp.xsr", (CHAR*)"SampleSRBank_jp.txt", (CHAR*)"font_jp.xpr" },
//    { L"French",        "SampleSRBank_fr.xsr", "SampleSRBank_fr.txt", "font.xpr" },
//    { L"German",        "SampleSRBank_de.xsr", "SampleSRBank_de.txt", "font.xpr" },
//    { L"UK English",    "SampleSRBank_uk.xsr", "SampleSRBank_uk.txt", "font.xpr" },
};
static const DWORD NUM_LANGUAGES = sizeof( g_aLanguages ) / sizeof( g_aLanguages[0] );

// The VOCABULARY struct is used to keep track of the various 
// vocabularies in the speech recognition bank
struct VOCABULARY
{
    WCHAR*                  strVocabName;   // Name
    XHV_SR_VOCAB_SELECTION  VocabID;        // Selector for XHV
    BOOL                    bActive;        // Active?
};

static VOCABULARY g_aVocabularies[] = 
{
    { (WCHAR*)L"Weapons",   XHV_SR_VOCAB_WEAPONS, TRUE },
    { (WCHAR*)L"Foods",     XHV_SR_VOCAB_FOODS, FALSE },
};
static const DWORD NUM_VOCABULARIES = sizeof( g_aVocabularies ) / sizeof( g_aVocabularies[0] );




// Define a structure to keep track of local talkers and their
// associated speech recognition state
struct LOCALTALKER_DATA
{
    BOOL            bCommunicatorPresent;
    LONG            lLastWord;
    FLOAT           fConfidence;
    BOOL            bActive;
    FLOAT           fActiveTime;
};

static const FLOAT SPEECH_REC_TIMEOUT      = 5.0f;     // 5 second timeout



//-----------------------------------------------------------------------------
// Name: class CXBoxSample
// Desc: Main class to run this application. Most functionality is inherited
//       from the CXBApplication base class.  Note that we also inherit from
//       ITitleXHV in order to implement callbacks for the high-level voice
//       engine
//-----------------------------------------------------------------------------
class CXBoxSample : public CXBApplication, public ITitleXHV
{
    CXBFont          m_Font;                            // Font object
    CXBFont          m_FontLang;                        // Language-specific font
    CXBHelp          m_Help;                            // Help object
    BOOL             m_bDrawHelp;                       // TRUE to draw help screen

    XHVEngine*       m_pXHVEngine;                      // Voice engine
    LOCALTALKER_DATA m_aLocalTalkers[XGetPortCount()];  // Local talkers + data
    VOID*            m_pSRBank;                         // Pointer to SR Bank data

    DWORD            m_dwLanguage;                      // Current language
    DWORD            m_dwVocabulary;                    // Current vocabulary
    DWORD            m_dwNumActive;                     // Number of active vocabularies
    FLOAT            m_fConfidenceThreshold;            // Minimum confidence level

    CWordList        m_WordList;

public:
    virtual HRESULT Initialize();
    virtual HRESULT Render();
    virtual HRESULT FrameMove();

    HRESULT LoadSpeechRecognitionBank( CHAR* strFilename );
    HRESULT SetSpeechRecMode( DWORD dwPort, BOOL bSpeechRecOn );
    HRESULT SetActiveVocabularies();
    HRESULT SelectLanguage( DWORD dwLanguage );

    STDMETHODIMP CommunicatorStatusUpdate( DWORD dwPort, XHV_VOICE_COMMUNICATOR_STATUS status );
    STDMETHODIMP SpeechRecognized( DWORD dwPort, PXHV_SR_ITEM pSRArray, DWORD dwNSRItems );
    STDMETHODIMP LocalChatDataReady( DWORD, DWORD, PVOID ) { return E_NOTIMPL; }

    CXBoxSample();
};




//-----------------------------------------------------------------------------
// Name: main()
// Desc: Entry point to the program.
//-----------------------------------------------------------------------------
VOID __cdecl main()
{
    CXBoxSample xbApp;
    if( FAILED( xbApp.Create() ) )
        return;
    xbApp.Run();
}




//-----------------------------------------------------------------------------
// Name: CXBoxSample()
// Desc: Constructor for CXBoxSample class
//-----------------------------------------------------------------------------
CXBoxSample::CXBoxSample() 
            :CXBApplication()
{
    m_bDrawHelp     = FALSE;
    m_pSRBank       = NULL;
    m_dwLanguage    = 0;
    m_dwVocabulary  = 0;
    m_dwNumActive   = 0;

    ZeroMemory( m_aLocalTalkers, sizeof(m_aLocalTalkers) );
}




//-----------------------------------------------------------------------------
// Name: LoadSpeechRecognitionBank
// Desc: Unloads the previous speech recognition bank (if any), and loads
//          the specified one
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::LoadSpeechRecognitionBank( CHAR* strFilename )
{
    // If we had an existing bank, we should free it now
    if( m_pSRBank != NULL )
    {
        // Un-register it from the engine
        m_pXHVEngine->RegisterSpeechRecognitionBank( NULL );

        // Free the memory that we allocated when loading the file
        free( m_pSRBank );
        m_pSRBank = NULL;
    }

    // If we're being asked to load a new one, go ahead and do so
    if( strFilename != NULL )
    {
        DWORD dwBankSize;
        CHAR strFullpath[MAX_PATH + 1];

        if( FAILED( XBUtil_FindMediaFile( strFullpath, strFilename ) ) )
        {
            XBUtil_DebugPrint( "Couldn't find media file %s\n", strFilename  );
            return E_FAIL;
        }

        if( FAILED( XBUtil_LoadFile( strFullpath, &m_pSRBank, &dwBankSize ) ) )
        {
            XBUtil_DebugPrint( "Couldn't load media file %s\n", strFullpath );
            return E_FAIL;
        }

        if( FAILED( m_pXHVEngine->RegisterSpeechRecognitionBank( m_pSRBank ) ) )
        {
            free( m_pSRBank );
            m_pSRBank = NULL;
            XBUtil_DebugPrint( "Couldn't register speech recognition bank %s", strFullpath );
            return E_FAIL;
        }
    }

    return S_OK;
}



//-----------------------------------------------------------------------------
// Name: Initialize()
// Desc: Performs initialization
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::Initialize()
{
    // Create a font
    if( FAILED( m_Font.Create( "Font.xpr" ) ) )
        return XBAPPERR_MEDIANOTFOUND;

    // Create help
    if( FAILED( m_Help.Create( "Gamepad.xpr" ) ) )
        return XBAPPERR_MEDIANOTFOUND;

    // Set up the runtime parameters for the voice engine.  Note that we
    // set max remote talkers to zero since we're just doing speech 
    // recognition, not voice chat.
    XHV_RUNTIME_PARAMS xhvParams     = {0};
    xhvParams.dwMaxRemoteTalkers     = 0;       
    xhvParams.dwMaxLocalTalkers      = 4;
    xhvParams.pEffectImageDesc       = NULL;

    // Create the voice engine
    if( FAILED( XHVEngineCreate( &xhvParams, &m_pXHVEngine ) ) )
        return E_FAIL;

    // Tell the voice engine to use this object for callbacks
    m_pXHVEngine->SetCallbackInterface( this );
    m_pXHVEngine->EnableProcessingMode( XHV_SR_MODE );

    // Register each local talker, but leave them inactive
    for( DWORD i = 0; i < XGetPortCount(); i++ )
    {
        if( FAILED( m_pXHVEngine->RegisterLocalTalker( i ) ) )
            return E_FAIL;

        m_pXHVEngine->SetProcessingMode( i, XHV_INACTIVE_MODE );
    }

    // Select our default language - this will also select the default
    // vocabulary for each local talker
    SelectLanguage( 0 );

    // Set default confidence threshold of 20.0f.  You should tune
    // this value to what works well for the vocabularies used in
    // your title.  
    m_fConfidenceThreshold = 20.0f;

    return S_OK;
}



//-----------------------------------------------------------------------------
// Name: CommunicatorStatusUpdate()
// Desc: XHV Callback - called whenever a communicator is inserted or removed
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::CommunicatorStatusUpdate( DWORD dwPort, XHV_VOICE_COMMUNICATOR_STATUS status )
{
    HRESULT hr = S_OK;

    switch( status )
    {
    case XHV_VOICE_COMMUNICATOR_STATUS_INSERTED:
        {
            m_aLocalTalkers[dwPort].bCommunicatorPresent = TRUE;
        }
        break;

    case XHV_VOICE_COMMUNICATOR_STATUS_REMOVED:
        {
            SetSpeechRecMode( dwPort, FALSE );
            m_aLocalTalkers[dwPort].bCommunicatorPresent = FALSE;
            m_aLocalTalkers[dwPort].lLastWord = -1;
        }
        break;

    default:
        // The only status we should expect is "inserted" or "removed"
        assert( FALSE );
    }

    return hr;
}




//-----------------------------------------------------------------------------
// Name: SpeechRecognized()
// Desc: XHV Callback - called whenever the voice engine has recognized a
//       speech phrase
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::SpeechRecognized( DWORD dwPort, PXHV_SR_ITEM pSRArray, 
                                       DWORD dwNSRItems )
{
    if( dwNSRItems == 0 )
    {
        // No results - this means we gave up on the user and switched out
        // of speech recognition mode before anything was recognized
        return S_OK;
    }

    // We don't expect more than 1 word to be returned...
    assert( dwNSRItems == 1 );

    // Unless the confidence value is greater than some positive value, there
    // probably wasn't a clearly recognized word.  You'll need to fine-tune
    // this threshold for the words in your particular vocabulary
    if( pSRArray[0].fConfidence > m_fConfidenceThreshold )
    {
        m_aLocalTalkers[ dwPort ].lLastWord = pSRArray[0].dwWordID;
        m_aLocalTalkers[dwPort].fConfidence = pSRArray[0].fConfidence;
        assert( m_WordList.FindWord( pSRArray[0].dwWordID ) != NULL );
    }

    // Turn speech recognition off after we get a result.  We check to see
    // if the local talker is still active, because the callback may have
    // come from us disabling speech recognition mode in FrameMove()
    if( m_aLocalTalkers[dwPort].bActive )
    {
        SetSpeechRecMode( dwPort, FALSE );
    }

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: SetSpeechRecMode
// Desc: Handles turning speech recognition mode on and off, and setting
//       other associated bookeeping data at the same time.
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::SetSpeechRecMode( DWORD dwPort, BOOL bSpeechRecOn )
{
    assert( m_aLocalTalkers[dwPort].bCommunicatorPresent );

    if( bSpeechRecOn )
    {
        // Turn speech recognition on for this local talker
        m_aLocalTalkers[dwPort].fActiveTime = 0.0f;
        m_aLocalTalkers[dwPort].bActive = TRUE;

        m_pXHVEngine->SetProcessingMode( dwPort, XHV_SR_MODE );
    }
    else
    {
        // Turn off speech recognition for this local talker.  Note that this
        // will force a SpeechRecognized callback, which may have partial
        // results, or no results at all.
        // If we supported voice chat, we would put the local talker into
        // voice chat mode instead of inactive mode.
        m_aLocalTalkers[dwPort].bActive = FALSE;

        m_pXHVEngine->SetProcessingMode( dwPort, XHV_INACTIVE_MODE );
    }

    return S_OK;
}



//-----------------------------------------------------------------------------
// Name: SetActiveVocabularies
// Desc: Builds up a list of all active vocabularies and activates them
//          within XHV.
// Note: For simplicity in this sample, all users have the same set of active
//          vocabularies, but that is not a requirement.  Each user can have
//          completely independent sets of active vocabularies, as long as all
//          vocabularies are contained in the same Speech Recognition Bank.
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::SetActiveVocabularies()
{
    HRESULT hr = S_OK;

    // Build up a list of all currently active vocabularies.  
    XHV_SR_VOCAB_SELECTION dwActiveVocabularies[ NUM_VOCABULARIES ];
    m_dwNumActive = 0;
    for( DWORD i = 0; i < NUM_VOCABULARIES; i++ )
    {
        if( g_aVocabularies[ i ].bActive )
        {
            dwActiveVocabularies[ m_dwNumActive ] = g_aVocabularies[ i ].VocabID;
            ++m_dwNumActive;
        }
    }

    // Notify XHV of the new active vocabulary set for each user.
    for( DWORD dwPort = 0; dwPort < XGetPortCount(); dwPort++ )
    {
        // If this fails, it's probably because the code and speech recognition
        // bank have gotten out of sync.  Re-build the speech recognition bank.
        hr = m_pXHVEngine->SelectVocabulary( dwPort, m_dwNumActive, dwActiveVocabularies );
        if( FAILED( hr ) )
            return hr;
    }

    return hr;
}


//-----------------------------------------------------------------------------
// Name: SelectLanguage
// Desc: Handles all the work of selecting a new language and re-loading all
//          appopriate files
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::SelectLanguage( DWORD dwLanguage )
{
    m_dwLanguage = dwLanguage;

    // Load up our speech recognition bank
    if( FAILED( LoadSpeechRecognitionBank( g_aLanguages[ m_dwLanguage ].strXSRFilename ) ) )
        return E_FAIL;

    // SAMPLE ONLY: Load up the word list used to generate the speech
    // recognition bank - this lets us display all the words on screen.
    // In a real game, you would just use the word IDs as defined in 
    // the generated header file.
    if( FAILED( m_WordList.LoadWordList( g_aLanguages[ m_dwLanguage ].strWordFilename ) ) )
        return E_FAIL;

    // Load the language-specific font for rendering words
    if( FAILED( m_FontLang.Create( g_aLanguages[ m_dwLanguage ].strFontFilename ) ) )
        return XBAPPERR_MEDIANOTFOUND;

    // Set the active vocabularies in this new language.
    SetActiveVocabularies();

    // Clear the last recognized word
    for( DWORD dwPort = 0; dwPort < XGetPortCount(); dwPort++ )
    {
        m_aLocalTalkers[ dwPort ].lLastWord = -1;
    }

    return S_OK;
}



//-----------------------------------------------------------------------------
// Name: FrameMove()
// Desc: Performs per-frame updates
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::FrameMove()
{
    // Toggle help
    if( m_DefaultGamepad.wPressedButtons & XINPUT_GAMEPAD_BACK ) 
    {
        m_bDrawHelp = !m_bDrawHelp;
    }

    // Handle input and timing for each local player
    for( DWORD dwPort = 0; dwPort < XGetPortCount(); dwPort++ )
    {
        if( m_aLocalTalkers[dwPort].bCommunicatorPresent )
        {
            // We time out the recognition attempt after a little while..
            if( m_aLocalTalkers[dwPort].bActive )
            {
                m_aLocalTalkers[dwPort].fActiveTime += m_fElapsedTime;
                if( m_aLocalTalkers[dwPort].fActiveTime > SPEECH_REC_TIMEOUT )
                {
                    SetSpeechRecMode( dwPort, FALSE );
                }
            }

            // Pressing the "A" button toggles speech rec mode on/off
            if( g_Gamepads[dwPort].bPressedAnalogButtons[ XINPUT_GAMEPAD_A ] )
            {
                SetSpeechRecMode( dwPort, !m_aLocalTalkers[dwPort].bActive );

                // Re-set the result
                m_aLocalTalkers[dwPort].lLastWord = -1;
            }
        }
    }

    // Pressing the "B" button moves to the next vocabulary
    if( m_DefaultGamepad.bPressedAnalogButtons[ XINPUT_GAMEPAD_B ] )
    {
        // Select the next vocabulary
        m_dwVocabulary = ( m_dwVocabulary + 1 ) % NUM_VOCABULARIES;
    }

    // Check to see if any speech recognition attempts are active.  There
    // are certain things you can't do when recognition is active, including
    // changing languages and/or the active vocabulary set.
    BOOL bSpeechRecActive = FALSE;
    for( DWORD dwPort = 0; dwPort < XGetPortCount(); dwPort++ )
    {
        if( m_aLocalTalkers[dwPort].bActive )
        {
            bSpeechRecActive = TRUE;
            break;
        }
    }

    if( !bSpeechRecActive )
    {
        // Pressing the "X" button toggles the current vocabulary on/off.
        if( m_DefaultGamepad.bPressedAnalogButtons[ XINPUT_GAMEPAD_X ] )
        {
            if( g_aVocabularies[ m_dwVocabulary ].bActive )
            {
                // At least one vocabulary must always be active, so don't let
                // the user turn off the last active vocabulary.
                if( m_dwNumActive > 1 )
                    g_aVocabularies[ m_dwVocabulary ].bActive = FALSE;
            }
            else
            {
                g_aVocabularies[ m_dwVocabulary ].bActive = TRUE;
            }

            SetActiveVocabularies();
        }

        // Pressing the "Y" button changes to another langauge by
        // re-loading a new speech recognition bank
        if( m_DefaultGamepad.bPressedAnalogButtons[ XINPUT_GAMEPAD_Y ] )
        {
            SelectLanguage( ( m_dwLanguage + 1 ) % NUM_LANGUAGES ); 
        }
    }

    // Adjust confidence threshold.  This is done in the sample 
    // for illustrative purpose only - you should find the appropriate
    // threshold for your title through usability tests, rather than
    // letting the user configure it.
    m_fConfidenceThreshold += 5.0f * m_DefaultGamepad.fX2 * m_fElapsedTime;
    if( m_fConfidenceThreshold < 0.0f )
    {
        m_fConfidenceThreshold = 0.0f;
    }

    // Pump the voice engine
    m_pXHVEngine->DoWork();

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: Render()
// Desc: Renders the scene
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::Render()
{
    // Draw a gradient filled background and clear the zbuffer
    RenderGradientBackground( 0xff404040, 0xff404080 );

    // Show title, frame rate, and help
    if( m_bDrawHelp )
        m_Help.Render( &m_Font, g_HelpCallouts, NUM_HELP_CALLOUTS );
    else
    {
        WCHAR str[256];

        m_Font.Begin();
        m_Font.SetScaleFactors( 1.2f, 1.2f );
        m_Font.DrawText( 48, 36, 0xffffffff, L"SpeechRecognition" );
        m_Font.SetScaleFactors( 1.0f, 1.0f );

        // Draw status for each controller
        FLOAT fX =  64.0f;
        FLOAT fY = 100.0f;
        for( DWORD dwPort = 0; dwPort < XGetPortCount(); dwPort++ )
        {
            swprintf( str, L"Controller Port %d: ", dwPort );
            m_Font.DrawText( fX, fY, 0xffffffff, str );
            fY += 30.0f;

            if( !m_aLocalTalkers[dwPort].bCommunicatorPresent )
            {
                m_Font.DrawText( fX + 20.0f, fY, 0xff808080, L"[Insert communicator]" );
            }
            else
            {
                if( m_aLocalTalkers[dwPort].bActive )
                {
                    m_Font.DrawText( fX + 20.0f, fY, 0xffffff00, L"Recognizing" );

                    // Draw dots as time elapses to indicate that there's a time limit
                    DWORD dwNumDots = DWORD( 20 * m_aLocalTalkers[dwPort].fActiveTime / SPEECH_REC_TIMEOUT );
                    for( DWORD j = 0; j < dwNumDots; j++ )
                    {
                        m_Font.DrawText( 0xffffff00, L"." );
                    }
                }
                else
                {
                    if( m_aLocalTalkers[dwPort].lLastWord != -1 )
                    {
                        WCHAR* pstr = m_WordList.FindWord( m_aLocalTalkers[dwPort].lLastWord );
                        m_Font.End();
                        m_FontLang.Begin();
                        m_FontLang.DrawText( fX + 20.0f, fY, 0xff00ff00, pstr );
                        m_FontLang.End();
                        m_Font.Begin();

                        FLOAT fWordWidth = m_FontLang.GetTextWidth( pstr );
                        swprintf( str, L" (%.1f)", m_aLocalTalkers[dwPort].fConfidence );
                        m_Font.DrawText( fX + fWordWidth + 20.0f, fY, 0xff00ff00, str );
                    }
                    else
                    {
                        m_Font.DrawText( fX + 20.0f, fY, 0xffff0000, L"Nothing recognized" );
                    }
                }
            }

            fY += 30.0f;
        }

        // Display the currently selected language and vocabulary
        swprintf( str, L"%s Words:", g_aLanguages[ m_dwLanguage ].strLanguage );
        m_Font.DrawText( 576.0f, 100.0f, 0xffffffff, str, XBFONT_RIGHT );

        fY = 125.0f;
        for( DWORD i = 0; i < NUM_VOCABULARIES; i++ )
        {
            BOOL bActive = g_aVocabularies[ i ].bActive;
            swprintf( str, L"%s\"%s\": %s", 
                        i == m_dwVocabulary ? GLYPH_RIGHT_TICK : L"",
                        g_aVocabularies[ i ].strVocabName, 
                        bActive ? L"enabled" : L"disabled" );
            m_Font.DrawText( 576.0f, fY, bActive ? 0xffffffff : 0xff808080, str, XBFONT_RIGHT );
            fY += 25.0f;
        }

        // We need to switch to our language-specific font for drawing the 
        // current vocabulary
        m_Font.End();
        m_FontLang.Begin();

        // Iterate over the list of words we loaded from the text file 
        // for the current vocabulary
        for( SR_WORDLIST::iterator it = m_WordList.m_VocabList[ m_dwVocabulary ].words.begin();
                it < m_WordList.m_VocabList[ m_dwVocabulary ].words.end();
                ++it )
        {
            m_FontLang.DrawText( 576, fY, 0xffffff00, it->strWord, XBFONT_RIGHT );
            fY += 25.0f;
        }

        // Switch back to regular font
        m_FontLang.End();
        m_Font.Begin();

        swprintf( str, L"Confidence Threshold: %.1f", m_fConfidenceThreshold );
        m_Font.DrawText( 64.0f, 360.0f, 0xffffff00, str );
        
        m_Font.End();
    }

    // Present the scene
    m_pd3dDevice->Present( NULL, NULL, NULL, NULL );

    return S_OK;
}

