// Automatically generated by the bundler tool from loadsaveresource.rdf

#define loadsaveresource_NUM_RESOURCES 11UL

#define loadsaveresource_Background_OFFSET 176UL
#define loadsaveresource_PlainBack_OFFSET 196UL
#define loadsaveresource_Up_OFFSET 216UL
#define loadsaveresource_Down_OFFSET 236UL
#define loadsaveresource_MsgBox_OFFSET 256UL
#define loadsaveresource_MU_OFFSET 276UL
#define loadsaveresource_MUWide_OFFSET 296UL
#define loadsaveresource_MU_Sel_OFFSET 316UL
#define loadsaveresource_Xbox_OFFSET 336UL
#define loadsaveresource_Xbox_Sel_OFFSET 356UL
#define loadsaveresource_MU_Bad_OFFSET 376UL
