// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 8UL

#define resource_LobbyXP_OFFSET 176UL
#define resource_LobbyXN_OFFSET 196UL
#define resource_LobbyYP_OFFSET 216UL
#define resource_LobbyYN_OFFSET 236UL
#define resource_LobbyZP_OFFSET 256UL
#define resource_LobbyZN_OFFSET 276UL
#define resource_BiHull_OFFSET 296UL
#define resource_Wings_OFFSET 316UL
