// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 4UL

#define resource_Block_OFFSET 80UL
#define resource_Earth_OFFSET 100UL
#define resource_EarthBump_OFFSET 120UL
#define resource_EarthEnvMap_OFFSET 140UL
