// Automatically generated by the bundler tool from Resource.rdf

#define Resource_NUM_RESOURCES 3UL

#define Resource_Seafloor_OFFSET 80UL
#define Resource_BiHull_OFFSET 100UL
#define Resource_Wings_OFFSET 120UL
