//-----------------------------------------------------------------------------
// File: ZSprite.cpp
//
// Desc: Demonstrates how to create and render a z-sprite. The z-sprite is 
//       generated by rendering a model into an offscreen texture and an
//       offscreen z-buffer. It is then rendered with a pixel shader using
//       the Dot_ZW texture address mode to recreate the original image with
//       correct z values.
//
//       Z-sprites are useful to decouple the update rate of an object from
//       the global frame rate. For instance, even if the framerate is 60Hz,
//       objects can be updated at 30Hz to lighten the load. Note that this
//       is really a tradeoff between the cost of rendering the object from
//       scratch and the (hopefully, much cheaper) cost of rendering the
//       z-sprite.
//
//       Note that for best performance, you will want to:
//          (a) Use the two-pass z-sprite rendering method
//          (b) Use a z-buffer format of D3DFMT_LIN_D16
//          (c) Minimize the # of pixels in your z-sprite (use a rect
//              just big enough to bound your objects)
//
// Hist: 02.28.01 - New for April XDK
//       10.30.02 - Revised to use 640x480 linear textures, and improve perf
//       11.06.02 - Revamped to use two-pass rendering method
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//-----------------------------------------------------------------------------
#include <xbapp.h>
#include <xbfont.h>
#include <xbhelp.h>
#include <xbmesh.h>
#include <xbutil.h>
#include <xgraphics.h>




//-----------------------------------------------------------------------------
// Callouts for labelling the gamepad on the help screen
//-----------------------------------------------------------------------------
XBHELP_CALLOUT g_HelpCallouts[] = 
{
    { XBHELP_A_BUTTON,     XBHELP_PLACEMENT_2, L"Toggle render\nmethod" },
    { XBHELP_X_BUTTON,     XBHELP_PLACEMENT_2, L"Toggle z-buffer\ndepth" },
    { XBHELP_BLACK_BUTTON, XBHELP_PLACEMENT_1, L"Tile render\ntarget" },
    { XBHELP_WHITE_BUTTON, XBHELP_PLACEMENT_1, L"Tile z-buffer" },
    { XBHELP_BACK_BUTTON,  XBHELP_PLACEMENT_1, L"Display help" },
    { XBHELP_LEFTSTICK,    XBHELP_PLACEMENT_1, L"Move camera" },
    { XBHELP_START_BUTTON, XBHELP_PLACEMENT_1, L"Pause" },
};

const DWORD NUM_HELP_CALLOUTS = sizeof(g_HelpCallouts)/sizeof(g_HelpCallouts[0]);



    
//-----------------------------------------------------------------------------
// Name: class CZSprite
// Desc: Class to implement a zsprite
//-----------------------------------------------------------------------------
class CZSprite
{
    D3DSurface* m_pZSpriteImageSurface;       // Surface for image data
    D3DTexture  m_ZSpriteImageTexture;        // Texture for image data
    D3DTexture* m_pZSpriteImageTexture;       // Texture ptr for image data

    D3DSurface* m_pZSpriteDepthBufferSurface; // Surface for depth data
    D3DTexture  m_ZSpriteDepthBufferTexture;  // Texture for depth data
    D3DTexture* m_pZSpriteDepthBufferTexture; // Texture ptr for depth data

    D3DXVECTOR2 m_ZSpriteVertices[4];         // Vertices for the quad

    DWORD       m_dwZSpriteVertexShader;      // Vertex shader handle
    DWORD       m_dwZSpritePixelShader;       // Pixel shader handle

    // Options
    BOOL        m_bUsingD16ZTexture;          // Using 16- or 24- bit depthbuffer
    BOOL        m_bRenderTargetIsTiled;       // Render target is tiled
    BOOL        m_bDepthBufferIsTiled;        // Depth buffer is tiled

public:
    // Creation function
    HRESULT Create( DWORD dwWidth, DWORD dwHeight );

    // Access functions
    D3DSurface*  GetImageSurface()       { return m_pZSpriteImageSurface; }
    D3DTexture*  GetImageTexture()       { return m_pZSpriteImageTexture; }
    D3DSurface*  GetDepthBufferSurface() { return m_pZSpriteDepthBufferSurface; }
    D3DTexture*  GetDepthBufferTexture() { return m_pZSpriteDepthBufferTexture; }
    D3DXVECTOR2* GetVertices()           { return m_ZSpriteVertices; }

    // Switch between 16-bit and 24-bit depth for the z-texture
    HRESULT ToggleZTextureDepth();
    BOOL    IsUsingD16DepthBuffer() { return m_bUsingD16ZTexture; }

    // Switch between using tiles and not using tiles
    VOID    TileRenderTarget( BOOL bValue );
    VOID    TileDepthBuffer( BOOL bValue );
    BOOL    IsRenderTargetTiled() { return m_bRenderTargetIsTiled; }
    BOOL    IsDepthBufferTiled()  { return m_bDepthBufferIsTiled; }

    // Render the z-sprite in either one or two passes
    HRESULT Render1Pass();
    HRESULT Render2Pass();

    CZSprite();
};




//-----------------------------------------------------------------------------
// Name: class CXBoxSample
// Desc: Main class to run this application. Most functionality is inherited
//       from the CXBApplication base class.
//-----------------------------------------------------------------------------
class CXBoxSample : public CXBApplication
{
    CXBFont     m_Font;                  // Font for text display
    CXBHelp     m_Help;                  // Help object
    BOOL        m_bDrawHelp;             // Should we draw help?

    CXBMesh     m_Mesh;                  // Mesh for teapot model

    D3DXVECTOR3 m_vViewAngle;            // View angle of camera

    CZSprite    m_pZSprite;              // The z-sprite
    BOOL        m_bRenderZSpriteIn1Pass; // Whether to render in 1 or 2 passes

    FLOAT       m_fPlaneZCoord;          // Attributes of an intersecting plane

    VOID    SetViewTransform();          // Sets the view transform
    HRESULT RenderToZSprite();           // Render a scene into the z-sprite
    HRESULT RenderZSprite();             // Renders the z-sprite on a quad

public:
    HRESULT Initialize();                // Initialize the sample
    HRESULT Render();                    // Render the scene
    HRESULT FrameMove();                 // Perform per-frame updates

    CXBoxSample();
};




//-----------------------------------------------------------------------------
// Name: main()
// Desc: Entry point to the program.
//-----------------------------------------------------------------------------
VOID __cdecl main()
{
    CXBoxSample xbApp;
    if( FAILED( xbApp.Create() ) )
        return;
    xbApp.Run();
}




//-----------------------------------------------------------------------------
// Name: CXBoxSample()
// Desc: Constructor for CXBoxSample class
//-----------------------------------------------------------------------------
CXBoxSample::CXBoxSample() 
            :CXBApplication()
{
    // Allow unlimited frame rate
    m_d3dpp.FullScreen_PresentationInterval = D3DPRESENT_INTERVAL_IMMEDIATE;

    m_bDrawHelp              = FALSE;
    m_bRenderZSpriteIn1Pass  = FALSE;
}




//-----------------------------------------------------------------------------
// Name: Initialize()
// Desc: Performs initialization
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::Initialize()
{
    // Create the font
    if( FAILED( m_Font.Create( "Font.xpr" ) ) )
        return XBAPPERR_MEDIANOTFOUND;

    // Create the help
    if( FAILED( m_Help.Create( "Gamepad.xpr" ) ) )
        return XBAPPERR_MEDIANOTFOUND;

    // Load our geometry
    if( FAILED( m_Mesh.Create( "Models\\Teapot.xbg" ) ) )
        return XBAPPERR_MEDIANOTFOUND;

    // Create a 640x480 zsprite
    if( FAILED( m_pZSprite.Create( 640, 480 ) ) )
        return E_FAIL;

    // World transform is just identity
    D3DXMATRIX matWorld;
    D3DXMatrixIdentity( &matWorld );
    m_pd3dDevice->SetTransform( D3DTS_WORLD, &matWorld );

    // Set the view transform based on view angle
    m_vViewAngle = D3DXVECTOR3( 0.0f, 0.0f, 0.0f );
    SetViewTransform();

    // Projection transform
    D3DXMATRIX matProj;
    D3DXMatrixPerspectiveFovLH( &matProj, D3DX_PI/3, 4.0f/3.0f, 2.0f, 15.0f );
    m_pd3dDevice->SetTransform( D3DTS_PROJECTION, &matProj );

    // Render some objects to the z-sprite
    if( FAILED( RenderToZSprite() ) )
        return E_FAIL;

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: SetViewTransform()
// Desc: Sets the view transform based on the view angle
//-----------------------------------------------------------------------------
VOID CXBoxSample::SetViewTransform()
{
    D3DXVECTOR3 vCameraPos( 0.0f, 0.0f, -8.0f );
    D3DXVECTOR3 vLookAt( 0.0f, 0.0f, 0.0f );
    D3DXVECTOR3 vUp( 0.0f, 1.0f, 0.0f);

    // Create a rotation matrix for our view angle
    D3DXMATRIX matRotate;
    D3DXMatrixRotationYawPitchRoll( &matRotate, m_vViewAngle.y, m_vViewAngle.x, 
                                                m_vViewAngle.z );

    // Transform our camera position (on the Z axis)
    D3DXVECTOR3 vEyePos;
    D3DXVec3TransformCoord( &vEyePos, &vCameraPos, &matRotate );
    
    // Use that eye position and look at the origin
    D3DXMATRIX matView;
    D3DXMatrixLookAtLH( &matView, &vEyePos, &vLookAt, &vUp );

    m_pd3dDevice->SetTransform( D3DTS_VIEW, &matView );
}




//-----------------------------------------------------------------------------
// Name: FrameMove()
// Desc: Performs per-frame updates
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::FrameMove()
{
    // Toggle help
    if( m_DefaultGamepad.wPressedButtons & XINPUT_GAMEPAD_BACK ) 
        m_bDrawHelp = !m_bDrawHelp;

    // Toggle the z-sprite rendering method
    if( m_DefaultGamepad.bPressedAnalogButtons[XINPUT_GAMEPAD_A] ) 
        m_bRenderZSpriteIn1Pass = !m_bRenderZSpriteIn1Pass;

    // Toggle the z-sprite depth
    if( m_DefaultGamepad.bPressedAnalogButtons[XINPUT_GAMEPAD_X] ) 
    {
        m_pZSprite.ToggleZTextureDepth();
        RenderToZSprite();
    }

    // Toggle use of tiles
    if( m_DefaultGamepad.bPressedAnalogButtons[XINPUT_GAMEPAD_WHITE] ) 
    {
        m_pZSprite.TileRenderTarget( !m_pZSprite.IsRenderTargetTiled() );
        RenderToZSprite();
    }
    if( m_DefaultGamepad.bPressedAnalogButtons[XINPUT_GAMEPAD_BLACK] ) 
    {
        m_pZSprite.TileDepthBuffer( !m_pZSprite.IsDepthBufferTiled() );
        RenderToZSprite();
    }

    // Move the camera based off the gamepad
    if( m_DefaultGamepad.fX1 != 0.0f || m_DefaultGamepad.fY1 != 0.0f )
    {
        m_vViewAngle.y -= m_DefaultGamepad.fX1*1.0f*m_fElapsedTime;
        if( m_vViewAngle.y > D3DX_PI*2 ) m_vViewAngle.y -= D3DX_PI*2;
        else if( m_vViewAngle.y < 0.0f)  m_vViewAngle.y += D3DX_PI*2;

        m_vViewAngle.x += m_DefaultGamepad.fY1*1.0f*m_fElapsedTime;
        if( m_vViewAngle.x > +1.0f )      m_vViewAngle.x = +1.0f;
        else if( m_vViewAngle.x < -1.0f ) m_vViewAngle.x = -1.0f;

        SetViewTransform();

        // Since the camera moved, we need to re-render to the Z-sprite.
        // Note: we don't want to do this every frame, as that would defeat
        // the point of using z-sprites. A sophisticated app might use an
        // error metric to determine re-render conditions
        RenderToZSprite();
    }

    // Move the plane back and forth
    m_fPlaneZCoord = cosf( m_fAppTime ) * 3.0f;

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: RenderToZSprite()
// Desc: Renders some stuff for our z-sprite. Actually renders the object
//       into a texture and a depth buffer.
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::RenderToZSprite()
{
    // Set the rendertarget to be our z-sprite surfaces
    m_pd3dDevice->SetRenderTarget( m_pZSprite.GetImageSurface(), 
                                   m_pZSprite.GetDepthBufferSurface() );

    // Clear the render target
    m_pd3dDevice->Clear( 0, NULL, D3DCLEAR_TARGET|D3DCLEAR_ZBUFFER|D3DCLEAR_STENCIL, 
                         0x00000000, 1.0f, 0L );

    // Set up our render state
    // Create a light for rendering to the texture and depth map
    D3DLIGHT8 light;
    ZeroMemory( &light, sizeof(D3DLIGHT8) );
    light.Type      = D3DLIGHT_DIRECTIONAL;
    light.Diffuse.r = 1.0f;
    light.Diffuse.g = 1.0f;
    light.Diffuse.b = 1.0f; 
    light.Diffuse.a = 1.0f;
    light.Direction = D3DXVECTOR3( -0.5f, -1.0f, 1.0f );
    m_pd3dDevice->SetLight( 0, &light );
    m_pd3dDevice->LightEnable( 0, TRUE );
    m_pd3dDevice->SetRenderState( D3DRS_LIGHTING, TRUE );
    m_pd3dDevice->SetRenderState( D3DRS_ZENABLE,  TRUE );
    m_pd3dDevice->SetRenderState( D3DRS_CULLMODE, D3DCULL_CCW );
    m_pd3dDevice->SetTextureStageState( 0, D3DTSS_COLOROP, D3DTOP_SELECTARG1 );
    m_pd3dDevice->SetTextureStageState( 0, D3DTSS_COLORARG1, D3DTA_DIFFUSE );

    // Save old state
    D3DXMATRIX matWorldSave;
    m_pd3dDevice->GetTransform( D3DTS_WORLD, &matWorldSave );

    // List of positions for our models
    static D3DXVECTOR3 vTeapotPositions[] = 
    {
        D3DXVECTOR3( 1.0f, 0.0f,-2.0f ),
        D3DXVECTOR3(-1.0f, 0.0f, 0.0f ),
        D3DXVECTOR3(-2.0f, 0.0f,-1.5f ),
        D3DXVECTOR3( 3.0f, 0.0f, 2.0f ),
    };
    
    // Render each teapot
    // RXDK: hoisted out of the for-init (MSVC's old for-scope leaked it past the loop)
    DWORD i;
    for( i = 0; i < 4; i++ )
    {
        light.Diffuse.r = (i==0||i==2) ? 1.0f : 0.0f;
        light.Diffuse.g = (i==1||i==2) ? 1.0f : 0.0f;
        light.Diffuse.b = (i==1||i==3) ? 1.0f : 0.0f;
        light.Diffuse.a = 1.0f;
        light.Direction = D3DXVECTOR3( -0.5f, -1.0f, 1.0f );
        m_pd3dDevice->SetLight( 0, &light );

        // Render the object
        D3DXMATRIX matWorld;
        D3DXMatrixTranslation( &matWorld, vTeapotPositions[i].x, 
                                          vTeapotPositions[i].y, 
                                          vTeapotPositions[i].z );
        m_pd3dDevice->SetTransform( D3DTS_WORLD, &matWorld );
        m_Mesh.Render();
    }

    // Restore state
    m_pd3dDevice->SetRenderTarget( m_pBackBuffer, m_pDepthBuffer );
    m_pd3dDevice->SetRenderState( D3DRS_LIGHTING, FALSE );
    m_pd3dDevice->SetTransform( D3DTS_WORLD, &matWorldSave );

    // Since drawing z-sprites is expensive, let's implement an optimization
    // to make the z-sprite to be just big enough to hold the rendered image.
    // Here we are using bounding spheres, but a real app may do something
    // more sophisticated. All those undrawn pixels will save lots of fillrate.

    // Calculate screen extents for the geometry drawn
    FLOAT xmin = +1.0f, xmax = -1.0f;
    FLOAT ymin = +1.0f, ymax = -1.0f;

    D3DXMATRIX matView, matProj;
    m_pd3dDevice->GetTransform( D3DTS_VIEW, &matView );
    m_pd3dDevice->GetTransform( D3DTS_PROJECTION, &matProj );
    static FLOAT fZNear        = 2.0f;
    static FLOAT fTeapotRadius = 0.0f;
    if( 0.0f == fTeapotRadius )
        fTeapotRadius = m_Mesh.ComputeRadius();

    for( i = 0; i < 4; i++ )
    {
        // Compute the screen space position of each object's bounding sphere
        D3DXVECTOR4 vPosView, vScreenPos;
        D3DXVec3Transform( &vPosView, &vTeapotPositions[i], &matView );
        D3DXVec4Transform( &vScreenPos, &vPosView, &matProj );
        vScreenPos.x /= vScreenPos.w;
        vScreenPos.y /= vScreenPos.w;
        FLOAT fScreenRadius = fTeapotRadius * fZNear / vPosView.z;

        // Record min/max extents
        xmin = min( xmin, max( -1.0f, vScreenPos.x - fScreenRadius ) );
        xmax = max( xmax, min( +1.0f, vScreenPos.x + fScreenRadius ) );
        ymin = min( ymin, max( -1.0f, vScreenPos.y - fScreenRadius ) );
        ymax = max( ymax, min( +1.0f, vScreenPos.y + fScreenRadius ) );
    }

    // Setup the z-sprite quad to use the smallest rect possible
    D3DXVECTOR2* pVertices = m_pZSprite.GetVertices();
    pVertices[0] = D3DXVECTOR2( 320*(1+xmin), 240*(1-ymin) );
    pVertices[1] = D3DXVECTOR2( 320*(1+xmax), 240*(1-ymin) );
    pVertices[2] = D3DXVECTOR2( 320*(1+xmax), 240*(1-ymax) );
    pVertices[3] = D3DXVECTOR2( 320*(1+xmin), 240*(1-ymax) );

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: Render()
// Desc: Renders the scene
//-----------------------------------------------------------------------------
HRESULT CXBoxSample::Render()
{
    // Draw a gradient filled background
    RenderGradientBackground( 0xff404040, 0xff404080 );

    // Set our render state
    m_pd3dDevice->SetRenderState( D3DRS_ZENABLE, TRUE );
    m_pd3dDevice->SetRenderState( D3DRS_LIGHTING, FALSE );
    m_pd3dDevice->SetRenderState( D3DRS_ALPHABLENDENABLE, TRUE );

    // Draw a plane. Note that the z-sprite will intersect correctly with the
    // plane regardless of whether we draw the plane first, or the z-sprite.
    {
        m_pd3dDevice->SetRenderState( D3DRS_CULLMODE, D3DCULL_NONE );
        m_pd3dDevice->SetRenderState( D3DRS_ALPHABLENDENABLE, FALSE );
        m_pd3dDevice->SetTextureStageState( 0, D3DTSS_COLOROP,   D3DTOP_SELECTARG1 );
        m_pd3dDevice->SetTextureStageState( 0, D3DTSS_COLORARG1, D3DTA_TFACTOR );
        m_pd3dDevice->SetTextureStageState( 0, D3DTSS_ALPHAOP,   D3DTOP_DISABLE );
        m_pd3dDevice->SetTextureStageState( 1, D3DTSS_COLOROP,   D3DTOP_DISABLE );
        m_pd3dDevice->SetRenderState( D3DRS_TEXTUREFACTOR, 0xff00cc00 );
        m_pd3dDevice->SetVertexShader( D3DFVF_XYZ );

        m_pd3dDevice->Begin( D3DPT_QUADLIST );
        m_pd3dDevice->SetVertexData4f( D3DVSDE_VERTEX, -5.0f,-1.0f, m_fPlaneZCoord, 1.0f );
        m_pd3dDevice->SetVertexData4f( D3DVSDE_VERTEX,  5.0f,-1.0f, m_fPlaneZCoord, 1.0f );
        m_pd3dDevice->SetVertexData4f( D3DVSDE_VERTEX,  5.0f, 1.0f, m_fPlaneZCoord, 1.0f );
        m_pd3dDevice->SetVertexData4f( D3DVSDE_VERTEX, -5.0f, 1.0f, m_fPlaneZCoord, 1.0f );
        m_pd3dDevice->End();
    }

    // Render the zsprite
    if( m_bRenderZSpriteIn1Pass )
        m_pZSprite.Render1Pass();
    else
        m_pZSprite.Render2Pass();
    
    // Show title, frame rate, and help
    if( m_bDrawHelp )
        m_Help.Render( &m_Font, g_HelpCallouts, NUM_HELP_CALLOUTS );
    else
    {
        m_Font.Begin();
        m_Font.SetScaleFactors( 1.2f, 1.2f );
        m_Font.DrawText( 48, 36, 0xffffffff,  L"ZSprite" );
        m_Font.SetScaleFactors( 1.0f, 1.0f );
        m_Font.DrawText( 592, 38, 0xffffff00, m_strFrameRate, XBFONT_RIGHT );

        m_Font.DrawText( 64,  80, 0xffffffff, L"Rendering in: " );
        m_Font.DrawText( 0xffffff00, m_bRenderZSpriteIn1Pass ? L"One pass" : L"Two passes" );
        m_Font.DrawText( 64, 110, 0xffffffff, L"Render target: " );
        m_Font.DrawText( 0xffffff00, L"A8R8G8B8" );
        m_Font.DrawText( 0xffffff00, m_pZSprite.IsRenderTargetTiled() ? L" (tiled)" : L" (not-tiled)");
        m_Font.DrawText( 64, 140, 0xffffffff, L"Depth buffer: " );
        m_Font.DrawText( 0xffffff00, m_pZSprite.IsUsingD16DepthBuffer() ? L"D16" : L"D24S8" );
        m_Font.DrawText( 0xffffff00, m_pZSprite.IsDepthBufferTiled() ? L" (tiled)" : L" (not-tiled)" );

        m_Font.End();
    }

    // Present the scene
    m_pd3dDevice->Present( NULL, NULL, NULL, NULL );

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: CZSprite()
// Desc: Constructor
//-----------------------------------------------------------------------------
CZSprite::CZSprite()
{
    m_pZSpriteImageSurface       = NULL;
    m_pZSpriteImageTexture       = NULL;
    m_pZSpriteDepthBufferSurface = NULL;
    m_pZSpriteDepthBufferTexture = NULL;

    m_dwZSpriteVertexShader      = 0;
    m_dwZSpritePixelShader       = 0;

    m_bUsingD16ZTexture          = FALSE;
    m_bRenderTargetIsTiled       = FALSE;
    m_bDepthBufferIsTiled        = FALSE;
}




//-----------------------------------------------------------------------------
// Name: CreateZSprite()
// Desc: Performs initialization
//-----------------------------------------------------------------------------
HRESULT CZSprite::Create( DWORD dwWidth, DWORD dwHeight )
{
    // Create a depth buffer for the z-sprite
    if( FAILED( D3DDevice::CreateImageSurface( dwWidth, dwHeight,
                                               D3DFMT_LIN_A8R8G8B8, 
                                               &m_pZSpriteImageSurface ) ) )
        return E_FAIL;

    // Create a texture for the image surface
    XGSetTextureHeader( dwWidth, dwHeight, 1, 0, D3DFMT_LIN_A8R8G8B8, 0,
                        &m_ZSpriteImageTexture, m_pZSpriteImageSurface->Data, 0 );
    m_pZSpriteImageTexture = &m_ZSpriteImageTexture;

    // Create a depth buffer for the z-sprite
    if( FAILED( D3DDevice::CreateImageSurface( dwWidth, dwHeight, D3DFMT_LIN_D24S8, 
                                               &m_pZSpriteDepthBufferSurface ) ) )
        return E_FAIL;

    // Create a texture for the z-buffer. Note the change to make the z-texture
    // look like an A8R8G8B8 surface. This is so our pixel shader texture
    // addressing mode deals with the pixels correctly.
    XGSetTextureHeader( dwWidth, dwHeight, 1, 0, D3DFMT_LIN_A8R8G8B8, 0,
                        &m_ZSpriteDepthBufferTexture, m_pZSpriteDepthBufferSurface->Data, 0 );
    m_pZSpriteDepthBufferTexture = &m_ZSpriteDepthBufferTexture;

    // Use tiles to improve rendering performance when using alternate rendertargets.
    TileRenderTarget( TRUE );
    TileDepthBuffer( TRUE );

    // Create the z-sprite vertex shaders
    {
        // Setup the vertex declaration
        DWORD dwDecl[] =
        {
            D3DVSD_STREAM( 0 ),
            D3DVSD_REG( 0, D3DVSDT_FLOAT2 ), // v0  = Position
            D3DVSD_END()
        };

        // Create the vertex shader
        if( FAILED( XBUtil_CreateVertexShader( "Shaders\\ZSprite.xvu", dwDecl,
                                               &m_dwZSpriteVertexShader ) ) )
        {
            OUTPUT_DEBUG_STRING( "Couldn't create vertex shader.\n" );
            return E_FAIL;
        }
    }
    
    // Create the z-sprite pixel shader
    {
        D3DPIXELSHADERDEF psd;
        ZeroMemory( &psd, sizeof(D3DPIXELSHADERDEF) );
        psd.PSTextureModes  = PS_TEXTUREMODES( PS_TEXTUREMODES_PROJECT2D,  // Real texture
                                               PS_TEXTUREMODES_PROJECT2D,  // Z texture
                                               PS_TEXTUREMODES_DOTPRODUCT, // (s0, t0, r0).(z, w, 1)
                                               PS_TEXTUREMODES_DOT_ZW );   // (s1, t1, r1).(z, w, 1)
        psd.PSInputTexture  = PS_INPUTTEXTURE( 0, 0, 1, 1 );
        psd.PSDotMapping    = PS_DOTMAPPING( 0, 0, PS_DOTMAPPING_HILO_1, PS_DOTMAPPING_HILO_1 );
        psd.PSCombinerCount = PS_COMBINERCOUNT( 1, 0 );
        psd.PSFinalCombinerInputsABCD = PS_COMBINERINPUTS( PS_REGISTER_ONE, PS_REGISTER_T0, 0, 0 );
        psd.PSFinalCombinerInputsEFG  = PS_COMBINERINPUTS( 0, 0, PS_REGISTER_T0|PS_CHANNEL_ALPHA, 0 );

        if( FAILED( D3DDevice::CreatePixelShader( &psd, &m_dwZSpritePixelShader ) ) )
        {
            OUTPUT_DEBUG_STRING( "Couldn't create pixel shader.\n" );
            return E_FAIL;
        }
    }

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: ToggleZTextureDepth()
// Desc: Performs initialization
//-----------------------------------------------------------------------------
HRESULT CZSprite::ToggleZTextureDepth()
{
    D3DSURFACE_DESC desc;
    m_pZSpriteImageSurface->GetDesc( &desc );

    // Toggle the z-texture depth
    m_bUsingD16ZTexture = !m_bUsingD16ZTexture;

    if( m_bUsingD16ZTexture )
    {
        // Use 16-bit (D16) texture and surface for the z-texture
        XGSetSurfaceHeader( desc.Width, desc.Height, D3DFMT_LIN_D16,
                            m_pZSpriteDepthBufferSurface, m_pZSpriteDepthBufferSurface->Data, 0x0500 );
        XGSetTextureHeader( desc.Width, desc.Height, 1, 0, D3DFMT_LIN_L16, 0,
                            &m_ZSpriteDepthBufferTexture, m_pZSpriteDepthBufferSurface->Data, 0x0500 );
        m_pZSpriteDepthBufferTexture = &m_ZSpriteDepthBufferTexture;
    }
    else
    {
        // Use 32-bit (D24S8) texture and surface for the z-texture
        XGSetSurfaceHeader( desc.Width, desc.Height, D3DFMT_LIN_D24S8,
                            m_pZSpriteDepthBufferSurface, m_pZSpriteDepthBufferSurface->Data, 0x0a00 );
        XGSetTextureHeader( desc.Width, desc.Height, 1, 0, D3DFMT_LIN_A8R8G8B8, 0,
                            &m_ZSpriteDepthBufferTexture, m_pZSpriteDepthBufferSurface->Data, 0x0a00 );
        m_pZSpriteDepthBufferTexture = &m_ZSpriteDepthBufferTexture;
    }

    // Set the tile
    TileDepthBuffer( m_bDepthBufferIsTiled );

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: TileRenderTarget()
// Desc: Enables/disables the use of a tile for the zsprite rendertarget
//-----------------------------------------------------------------------------
VOID CZSprite::TileRenderTarget( BOOL bValue )
{
    // Store the flag
    m_bRenderTargetIsTiled = bValue;

    // Reset existing tiles
    D3DDevice::SetTile( 2, NULL );

    // Set the tile for the render target
    if( m_bRenderTargetIsTiled )
    {
        D3DSURFACE_DESC desc;
        m_pZSpriteImageSurface->GetDesc( &desc );

        D3DTILE ZSpriteRenderTargetTile = 
        {
            0, 
            (VOID*)( 0x80000000 | m_pZSpriteImageSurface->Data ),
            desc.Width*desc.Height*4, desc.Width*4
        };
        D3DDevice::SetTile( 2, &ZSpriteRenderTargetTile );
    }
}




//-----------------------------------------------------------------------------
// Name: EnableZSpriteDepthBufferTile()
// Desc: Enables/disables the use of a tile for the zsprite depth buffer
//-----------------------------------------------------------------------------
VOID CZSprite::TileDepthBuffer( BOOL bValue )
{
    // Store the flag
    m_bDepthBufferIsTiled = bValue;

    // Reset existing tiles
    D3DDevice::SetTile( 3, NULL );

    // Set the tile for the zbuffer
    if( m_bDepthBufferIsTiled )
    {
        D3DSURFACE_DESC desc;
        m_pZSpriteDepthBufferSurface->GetDesc( &desc );

        D3DTILE ZSpriteDepthBufferTile = 
        {
            D3DTILE_FLAGS_ZBUFFER | ( desc.Format == D3DFMT_LIN_D24S8 ? D3DTILE_FLAGS_Z32BITS : D3DTILE_FLAGS_Z16BITS),
            (VOID*)( 0x80000000 | m_pZSpriteDepthBufferSurface->Data ),
            desc.Width*desc.Height*4,
            desc.Width*XGBytesPerPixelFromFormat(desc.Format)
        };
        D3DDevice::SetTile( 3, &ZSpriteDepthBufferTile );
    }
}




//-----------------------------------------------------------------------------
// Vertex shader constants for using ZSprites
//-----------------------------------------------------------------------------
FLOAT g_vD16VertexShaderConstants[12] = 
{
    // Vertex shift constants
    -0.5f,-0.5f, 0.0f, 0.0f,

    // Constants for the DotZW texture address op using D16 zsprites:
    //    Zfinal = (Zin) / (1/Zmax)
    //           = Zin * Zmax
    // Where Zin ranges [0..1] and Zfinal ranges [0..Zmax]
    0.0f, 1.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 1.0f/(FLOAT)D3DZ_MAX_D24S8, 0.0f
};

FLOAT g_vD24S8VertexShaderConstants[12] = 
{ 
    // Vertex shift constants
    -0.5f,-0.5f, 0.0f, 0.0f,

    // Constants for the DotZW texture address op using D24S8 zsprites:
    //    Zfinal = (Zhi16 + ZLo16/0xffff) / (1/Zmax)
    //           = Zin * Zmax
    // Where Zin ranges [0..1] and Zfinal ranges [0..Zmax]
    1.0f, 1.0f/0xffff, 0.0f, 0.0f,                
    0.0f, 0.0f, 1.0f/(FLOAT)D3DZ_MAX_D24S8, 0.0f 
};




//-----------------------------------------------------------------------------
// Name: Render1Pass()
// Desc: Renders the ZSprite in one pass, using all 4 texture stages.
//       Surprisingly, this method is slower than the two-pass method.
//-----------------------------------------------------------------------------
HRESULT CZSprite::Render1Pass()
{
    // For drawing the zbuffer, we want both the ztest and zwrite enabled
    D3DDevice::SetRenderState( D3DRS_ZENABLE,      TRUE );
    D3DDevice::SetRenderState( D3DRS_ZWRITEENABLE, TRUE );

    D3DDevice::SetRenderState( D3DRS_ALPHABLENDENABLE, FALSE );
    D3DDevice::SetRenderState( D3DRS_ALPHATESTENABLE, FALSE );

    // Set up our source & textures for the z-sprite. Note that the textures 
    // for stage 3 doesn't matter but we have to specify SOMETHING in order
    // to make the pixel shader hardware happy.
    D3DDevice::SetTexture( 0, m_pZSpriteImageTexture );
    D3DDevice::SetTexture( 1, m_pZSpriteDepthBufferTexture );
    D3DDevice::SetTexture( 2, NULL );
    D3DDevice::SetTexture( 3, m_pZSpriteDepthBufferTexture );
    D3DDevice::SetTextureStageState( 0, D3DTSS_ADDRESSU, D3DTADDRESS_CLAMP );
    D3DDevice::SetTextureStageState( 0, D3DTSS_ADDRESSV, D3DTADDRESS_CLAMP );
    D3DDevice::SetTextureStageState( 1, D3DTSS_ADDRESSU, D3DTADDRESS_CLAMP );
    D3DDevice::SetTextureStageState( 1, D3DTSS_ADDRESSV, D3DTADDRESS_CLAMP );
    D3DDevice::SetTextureStageState( 3, D3DTSS_ADDRESSU, D3DTADDRESS_CLAMP );
    D3DDevice::SetTextureStageState( 3, D3DTSS_ADDRESSV, D3DTADDRESS_CLAMP );

    D3DDevice::SetTextureStageState( 0, D3DTSS_MINFILTER, D3DTEXF_POINT );
    D3DDevice::SetTextureStageState( 0, D3DTSS_MAGFILTER, D3DTEXF_POINT );
    D3DDevice::SetTextureStageState( 1, D3DTSS_MINFILTER, D3DTEXF_POINT );
    D3DDevice::SetTextureStageState( 1, D3DTSS_MAGFILTER, D3DTEXF_POINT );
    D3DDevice::SetTextureStageState( 3, D3DTSS_MINFILTER, D3DTEXF_POINT );
    D3DDevice::SetTextureStageState( 3, D3DTSS_MAGFILTER, D3DTEXF_POINT );

    // Z-sprites are likely to have lots of empty pixels, so enable alphakill
    D3DDevice::SetTextureStageState( 0, D3DTSS_ALPHAKILL, D3DTALPHAKILL_ENABLE );

    // Set the vertex shader for rendering z-sprites
    D3DDevice::SetVertexShader( m_dwZSpriteVertexShader );
    if( m_bUsingD16ZTexture )
        D3DDevice::SetVertexShaderConstant( 0, &g_vD16VertexShaderConstants, 3 );
    else
        D3DDevice::SetVertexShaderConstant( 0, &g_vD24S8VertexShaderConstants, 3 );

    // Set the pixel shader for rendering z-sprites in one pass
    D3DDevice::SetPixelShader( m_dwZSpritePixelShader );
    D3DDevice::SetRenderState( D3DRS_PSTEXTUREMODES, PS_TEXTUREMODES( PS_TEXTUREMODES_PROJECT2D,  // Real texture
                                                                      PS_TEXTUREMODES_PROJECT2D,  // Z texture
                                                                      PS_TEXTUREMODES_DOTPRODUCT, // (s0, t0, r0).(z, w, 1)
                                                                      PS_TEXTUREMODES_DOT_ZW ) ); // (s1, t1, r1).(z, w, 1)

    // Draw the ZSprite
    D3DDevice::DrawVerticesUP( D3DPT_QUADLIST, 4, m_ZSpriteVertices, sizeof(D3DXVECTOR2) );

    // Restore state
    D3DDevice::SetTextureStageState( 0, D3DTSS_ALPHAKILL, D3DTALPHAKILL_DISABLE );
    D3DDevice::SetPixelShader( 0 );
    D3DDevice::SetTexture( 0, NULL );
    D3DDevice::SetTexture( 1, NULL );
    D3DDevice::SetTexture( 3, NULL );

    return S_OK;
}




//-----------------------------------------------------------------------------
// Name: Render2Pass()
// Desc: Renders the ZSprite in two passes. The first pass does the z-test and
//       z-writes, and records the z-test in the stencil buffer. The second
//       pass draws the z-sprite image texture, masked by the stencil.
//
//       Surprisingly, this method is faster than the one-pass method.
//-----------------------------------------------------------------------------
HRESULT CZSprite::Render2Pass()
{
    // For drawing the zbuffer, we want both the ztest and zwrite enabled
    D3DDevice::SetRenderState( D3DRS_ZENABLE,      TRUE );
    D3DDevice::SetRenderState( D3DRS_ZWRITEENABLE, TRUE );

    // Turn on stenciling
    D3DDevice::SetRenderState( D3DRS_STENCILENABLE,   TRUE );
    D3DDevice::SetRenderState( D3DRS_STENCILFUNC,     D3DCMP_ALWAYS );
    D3DDevice::SetRenderState( D3DRS_STENCILREF,      0 );
    D3DDevice::SetRenderState( D3DRS_STENCILMASK,     0x00000000 );
    D3DDevice::SetRenderState( D3DRS_STENCILWRITEMASK,0xffffffff );

    // Increment the stencil buffer for each pixel drawn
    D3DDevice::SetRenderState( D3DRS_STENCILZFAIL, D3DSTENCILOP_INCRSAT );
    D3DDevice::SetRenderState( D3DRS_STENCILFAIL,  D3DSTENCILOP_KEEP );
    D3DDevice::SetRenderState( D3DRS_STENCILPASS,  D3DSTENCILOP_KEEP );

    // Since we are only writing into the stencil buffer, we can turn off the
    // frame buffer.
    D3DDevice::SetRenderState( D3DRS_COLORWRITEENABLE, 0x00000000 );

    // Set up our source & textures for the z-sprite. Note that the textures 
    // for stage 3 doesn't matter but we have to specify SOMETHING in order
    // to make the pixel shader hardware happy.
    D3DDevice::SetTexture( 0, NULL );
    D3DDevice::SetTexture( 1, m_pZSpriteDepthBufferTexture );
    D3DDevice::SetTexture( 2, NULL );
    D3DDevice::SetTexture( 3, m_pZSpriteDepthBufferTexture );
    D3DDevice::SetTextureStageState( 0, D3DTSS_ADDRESSU, D3DTADDRESS_CLAMP );
    D3DDevice::SetTextureStageState( 0, D3DTSS_ADDRESSV, D3DTADDRESS_CLAMP );
    D3DDevice::SetTextureStageState( 1, D3DTSS_ADDRESSU, D3DTADDRESS_CLAMP );
    D3DDevice::SetTextureStageState( 1, D3DTSS_ADDRESSV, D3DTADDRESS_CLAMP );
    D3DDevice::SetTextureStageState( 3, D3DTSS_ADDRESSU, D3DTADDRESS_CLAMP );
    D3DDevice::SetTextureStageState( 3, D3DTSS_ADDRESSV, D3DTADDRESS_CLAMP );

    D3DDevice::SetTextureStageState( 0, D3DTSS_MINFILTER, D3DTEXF_POINT );
    D3DDevice::SetTextureStageState( 0, D3DTSS_MAGFILTER, D3DTEXF_POINT );
    D3DDevice::SetTextureStageState( 1, D3DTSS_MINFILTER, D3DTEXF_POINT );
    D3DDevice::SetTextureStageState( 1, D3DTSS_MAGFILTER, D3DTEXF_POINT );
    D3DDevice::SetTextureStageState( 3, D3DTSS_MINFILTER, D3DTEXF_POINT );
    D3DDevice::SetTextureStageState( 3, D3DTSS_MAGFILTER, D3DTEXF_POINT );

    // Set the vertex shader for rendering z-sprites
    D3DDevice::SetVertexShader( m_dwZSpriteVertexShader );
    if( m_bUsingD16ZTexture )
        D3DDevice::SetVertexShaderConstant( 0, &g_vD16VertexShaderConstants, 3 );
    else
        D3DDevice::SetVertexShaderConstant( 0, &g_vD24S8VertexShaderConstants, 3 );

    // Set the pixel shader for rendering z-sprites in the frist of two passes
    D3DDevice::SetPixelShader( m_dwZSpritePixelShader );
    D3DDevice::SetRenderState( D3DRS_PSTEXTUREMODES, PS_TEXTUREMODES( PS_TEXTUREMODES_NONE,       // Not used
                                                                      PS_TEXTUREMODES_PROJECT2D,  // Z texture
                                                                      PS_TEXTUREMODES_DOTPRODUCT, // (s0, t0, r0).(z, w, 1)
                                                                      PS_TEXTUREMODES_DOT_ZW ) ); // (s1, t1, r1).(z, w, 1)

    // Draw the z-portion of the ZSprite, such that we write new z-values to
    // the real z-buffer, and record the result of the ztest in the stencil
    // buffer.
    D3DDevice::DrawVerticesUP( D3DPT_QUADLIST, 4, m_ZSpriteVertices, sizeof(D3DXVECTOR2) );

    // Restore state
    D3DDevice::SetPixelShader( 0 );
    D3DDevice::SetTexture( 1, NULL );
    D3DDevice::SetTexture( 3, NULL );
    D3DDevice::SetRenderState( D3DRS_COLORWRITEENABLE, D3DCOLORWRITEENABLE_ALL );

    // Now, draw the image portion of the zsprite, masked out by the stencil mask

    // Set states for optimal performance
    D3DDevice::SetRenderState( D3DRS_ZENABLE,          FALSE );
    D3DDevice::SetRenderState( D3DRS_ALPHABLENDENABLE, FALSE );
    D3DDevice::SetTextureStageState( 0, D3DTSS_ALPHAKILL, D3DTALPHAKILL_ENABLE );

    // Turn on the stencil buffer to use as a mask
    D3DDevice::SetRenderState( D3DRS_STENCILZFAIL, D3DSTENCILOP_KEEP );
    D3DDevice::SetRenderState( D3DRS_STENCILFAIL,  D3DSTENCILOP_KEEP );
    D3DDevice::SetRenderState( D3DRS_STENCILPASS,  D3DSTENCILOP_KEEP );
    D3DDevice::SetRenderState( D3DRS_STENCILFUNC,  D3DCMP_EQUAL );
    D3DDevice::SetRenderState( D3DRS_STENCILMASK,  0xffffffff );
    D3DDevice::SetRenderState( D3DRS_STENCILREF,   0 );

    // Draw the image portion of the zsprite
    D3DDevice::SetTextureStageState( 0, D3DTSS_COLORARG1, D3DTA_TEXTURE );
    D3DDevice::SetTextureStageState( 0, D3DTSS_COLOROP,   D3DTOP_SELECTARG1 );
    D3DDevice::SetTextureStageState( 0, D3DTSS_ALPHAOP,   D3DTOP_DISABLE );
    D3DDevice::SetTextureStageState( 1, D3DTSS_COLOROP,   D3DTOP_DISABLE );
    D3DDevice::SetTexture( 0, m_pZSpriteImageTexture );
    D3DDevice::DrawVerticesUP( D3DPT_QUADLIST, 4, m_ZSpriteVertices, sizeof(D3DXVECTOR2) );

    // Restore states
    D3DDevice::SetRenderState( D3DRS_ZENABLE,          TRUE );
    D3DDevice::SetRenderState( D3DRS_STENCILENABLE,    FALSE );
    D3DDevice::SetTextureStageState( 0, D3DTSS_ALPHAKILL, D3DTALPHAKILL_DISABLE );
    D3DDevice::SetTexture( 0, NULL );

    return S_OK;
}




